Use AG_{Push,Pop}BlendingMode() wherever blending is needed.
AG_Box: Make the former AG_HBox and AG_VBox aliases deprecated since they
are not useful and likely to create confusion.

AG_Button: Indicate focus more clearly using two lines in SELECTION_COLOR.

AG_Console: Treat the selection offset "sel" as inclusive. Fix scrolling
behavior and the ability to include the first line when selecting. Added
new export option "Strip ANSI" to remove ANSI SGR sequences from output.

AG_Editable: Fix upward vertical scrolling behavior during selection.

AG_Event: When parsing a (malformed) format string, prevent an uninitialized
read in AG_EVENT_PUSH_ARG() if a named argument is missing its type specifier.

AG_GuiDebugger: Add a button to control autorefresh. Display stats about
number of containers and leaves. Add flags and texture mapping information
to the "Surfaces" listing.

AG_Pane: Cull the decorative dots when undersize.

AG_Scrollbar: Cosmetic and legibility fixes.

AG_Widget: Remove NOSPACING flag (replaced by "spacing" style attribute).

core/dir.c: Don't redefine _DARWIN_C_SOURCE.

Adjust color scheme to improve contrast across different devices.

Remove unused "child-attached" and "child-detached" events.

Remove --enable-debug-core and --enable-debug-gui build options. Added new
extended debug options DEBUG_EVENTS, DEBUG_OBJECT & DEBUG_SERIALIZATION.

Various adjustments to struct paddings; compiler warnings fixes.

Various updates to the manual pages. Improved wording, examples. Use
"<MAJOR>.<MINOR>.<PATCH>" consistently in HISTORY sections.



git-svn-id: https://dev.csoft.net/agar/trunk@10900 86a84d31-9702-0410-8f1e-a60cab7bd424

diff --git a/tools/rgedit/configure b/tools/rgedit/configure
--- a/tools/rgedit/configure
+++ b/tools/rgedit/configure
@@ -879,7 +879,14 @@ if [ "${mandir}" != '' ]; then
 	MANDIR="${mandir}"
 	MANDIR_SPECIFIED='yes'
 else
-	MANDIR="${PREFIX}/man"
+	case "${host}" in
+	*-*-darwin*)
+		MANDIR="${PREFIX}/share/man"
+		;;
+	*)
+		MANDIR="${PREFIX}/man"
+		;;
+	esac
 fi
 bb_o=$bb_incdir/mandir.h
 echo '#ifndef MANDIR' >$bb_o
@@ -1086,6 +1093,84 @@ echo "hdefs[\"EXECSUFFIX\"] = \"$EXECSUFFIX\"" >>configure.lua
 	TEST_CFLAGS=''
 fi
 if [ "${HAVE_CC}" = "yes" ]; then
+$ECHO_N 'cc: checking whether compiler is Clang...'
+$ECHO_N '# cc: checking whether compiler is Clang...' >>config.log
+MK_COMPILE_STATUS=OK
+cat << EOT >conftest$$.c
+#if !defined(__clang__)
+# error "is not clang"
+#endif
+int main(int argc, char *argv[]) { return (0); }
+EOT
+echo >>config.log
+echo '# C: HAVE_CC_CLANG' >>config.log
+echo "cat << EOT >conftest$$.c" >>config.log
+cat conftest$$.c>>config.log
+echo EOT >>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest$$ conftest$$.c  2>>config.log">>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest$$ conftest$$.c  2>>config.log
+if [ "$?" != "0" ]; then
+echo "# failed $?" >>config.log
+MK_COMPILE_STATUS="FAIL $?"
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo 'yes'
+echo '# yes' >>config.log
+HAVE_CC_CLANG=yes
+bb_o=$bb_incdir/have_cc_clang.h
+echo '#ifndef HAVE_CC_CLANG' >$bb_o
+echo "#define HAVE_CC_CLANG \"$HAVE_CC_CLANG\"" >>$bb_o
+echo '#endif' >>$bb_o
+echo "hdefs[\"HAVE_CC_CLANG\"] = \"$HAVE_CC_CLANG\"" >>configure.lua
+else
+echo 'no'
+echo '# no' >>config.log
+HAVE_CC_CLANG=no
+echo '#undef HAVE_CC_CLANG' >$bb_incdir/have_cc_clang.h
+echo 'hdefs["HAVE_CC_CLANG"] = nil' >>configure.lua
+fi
+if [ "${keep_conftest}" != "yes" ]; then
+rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
+fi
+$ECHO_N 'cc: checking whether compiler is GCC...'
+$ECHO_N '# cc: checking whether compiler is GCC...' >>config.log
+MK_COMPILE_STATUS=OK
+cat << EOT >conftest$$.c
+#if !defined(__GNUC__) || defined(__clang__)
+# error "is not gcc"
+#endif
+int main(int argc, char *argv[]) { return (0); }
+EOT
+echo >>config.log
+echo '# C: HAVE_CC_GCC' >>config.log
+echo "cat << EOT >conftest$$.c" >>config.log
+cat conftest$$.c>>config.log
+echo EOT >>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest$$ conftest$$.c  2>>config.log">>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest$$ conftest$$.c  2>>config.log
+if [ "$?" != "0" ]; then
+echo "# failed $?" >>config.log
+MK_COMPILE_STATUS="FAIL $?"
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo 'yes'
+echo '# yes' >>config.log
+HAVE_CC_GCC=yes
+bb_o=$bb_incdir/have_cc_gcc.h
+echo '#ifndef HAVE_CC_GCC' >$bb_o
+echo "#define HAVE_CC_GCC \"$HAVE_CC_GCC\"" >>$bb_o
+echo '#endif' >>$bb_o
+echo "hdefs[\"HAVE_CC_GCC\"] = \"$HAVE_CC_GCC\"" >>configure.lua
+else
+echo 'no'
+echo '# no' >>config.log
+HAVE_CC_GCC=no
+echo '#undef HAVE_CC_GCC' >$bb_incdir/have_cc_gcc.h
+echo 'hdefs["HAVE_CC_GCC"] = nil' >>configure.lua
+fi
+if [ "${keep_conftest}" != "yes" ]; then
+rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
+fi
 $ECHO_N 'cc: checking for compiler warning options...'
 $ECHO_N '# cc: checking for compiler warning options...' >>config.log
 MK_COMPILE_STATUS=OK
@@ -1503,6 +1588,10 @@ LIBTOOLOPTS_SHARED=""
 TEST_CFLAGS=""
 echo '#undef HAVE_CC' >$bb_incdir/have_cc.h
 echo 'hdefs["HAVE_CC"] = nil' >>configure.lua
+echo '#undef HAVE_CC_CLANG' >$bb_incdir/have_cc_clang.h
+echo 'hdefs["HAVE_CC_CLANG"] = nil' >>configure.lua
+echo '#undef HAVE_CC_GCC' >$bb_incdir/have_cc_gcc.h
+echo 'hdefs["HAVE_CC_GCC"] = nil' >>configure.lua
 echo '#undef HAVE_CC65' >$bb_incdir/have_cc65.h
 echo 'hdefs["HAVE_CC65"] = nil' >>configure.lua
 echo '#undef HAVE_CC_WARNINGS' >$bb_incdir/have_cc_warnings.h
@@ -1780,13 +1869,13 @@ exit 1
 fi
 $ECHO_N 'checking for Agar-MAP...'
 $ECHO_N '# checking for Agar-MAP...' >>config.log
-# BEGIN agar-map(1.6.0 ${prefix_agar})
+# BEGIN agar-map(1.6.0 ${prefix_agar_map})
 AGAR_MAP_VERSION=
-if [ "${prefix_agar}" != "" ]; then
-if [ -e "${prefix_agar}/bin/agar-map-config" ]; then
-AGAR_MAP_VERSION=`${prefix_agar}/bin/agar-map-config --version`
+if [ "${prefix_agar_map}" != "" ]; then
+if [ -e "${prefix_agar_map}/bin/agar-map-config" ]; then
+AGAR_MAP_VERSION=`${prefix_agar_map}/bin/agar-map-config --version`
 MK_EXEC_FOUND=Yes
-MK_EXEC_PATH="${prefix_agar}/bin/agar-map-config"
+MK_EXEC_PATH="${prefix_agar_map}/bin/agar-map-config"
 fi
 else
 bb_save_IFS=$IFS
@@ -1807,9 +1896,9 @@ done
 IFS=$bb_save_IFS
 fi
 if [ "${AGAR_MAP_VERSION}" != "" ]; then
-if [ "${prefix_agar}" != "" ]; then
-echo "yes ($AGAR_MAP_VERSION in ${prefix_agar})"
-echo "# yes ($AGAR_MAP_VERSION in ${prefix_agar})" >>config.log
+if [ "${prefix_agar_map}" != "" ]; then
+echo "yes ($AGAR_MAP_VERSION in ${prefix_agar_map})"
+echo "# yes ($AGAR_MAP_VERSION in ${prefix_agar_map})" >>config.log
 else
 echo "yes ($AGAR_MAP_VERSION)"
 echo "# yes ($AGAR_MAP_VERSION)" >>config.log
@@ -1846,9 +1935,9 @@ echo '*'
 echo '# *' >>config.log
 fi
 else
-if [ "${prefix_agar}" != "" ]; then
-echo "no (not in ${prefix_agar})"
-echo "# no (not in ${prefix_agar})" >>config.log
+if [ "${prefix_agar_map}" != "" ]; then
+echo "no (not in ${prefix_agar_map})"
+echo "# no (not in ${prefix_agar_map})" >>config.log
 else
 echo 'no'
 echo '# no' >>config.log
@@ -1859,11 +1948,11 @@ if [ "${MK_VERSION_OK}" = "yes" ]; then
 $ECHO_N 'checking whether Agar-MAP works...'
 $ECHO_N '# checking whether Agar-MAP works...' >>config.log
 AGAR_CFLAGS=
-if [ "${prefix_agar}" != "" ]; then
-if [ -e "${prefix_agar}/bin/agar-config" ]; then
-AGAR_CFLAGS=`${prefix_agar}/bin/agar-config --cflags`
+if [ "${prefix_agar_map}" != "" ]; then
+if [ -e "${prefix_agar_map}/bin/agar-config" ]; then
+AGAR_CFLAGS=`${prefix_agar_map}/bin/agar-config --cflags`
 MK_EXEC_FOUND=Yes
-MK_EXEC_PATH="${prefix_agar}/bin/agar-config"
+MK_EXEC_PATH="${prefix_agar_map}/bin/agar-config"
 fi
 else
 bb_save_IFS=$IFS
@@ -1884,11 +1973,11 @@ done
 IFS=$bb_save_IFS
 fi
 AGAR_LIBS=
-if [ "${prefix_agar}" != "" ]; then
-if [ -e "${prefix_agar}/bin/agar-config" ]; then
-AGAR_LIBS=`${prefix_agar}/bin/agar-config --libs`
+if [ "${prefix_agar_map}" != "" ]; then
+if [ -e "${prefix_agar_map}/bin/agar-config" ]; then
+AGAR_LIBS=`${prefix_agar_map}/bin/agar-config --libs`
 MK_EXEC_FOUND=Yes
-MK_EXEC_PATH="${prefix_agar}/bin/agar-config"
+MK_EXEC_PATH="${prefix_agar_map}/bin/agar-config"
 fi
 else
 bb_save_IFS=$IFS
@@ -1909,11 +1998,11 @@ done
 IFS=$bb_save_IFS
 fi
 AGAR_MAP_CFLAGS=
-if [ "${prefix_agar}" != "" ]; then
-if [ -e "${prefix_agar}/bin/agar-map-config" ]; then
-AGAR_MAP_CFLAGS=`${prefix_agar}/bin/agar-map-config --cflags`
+if [ "${prefix_agar_map}" != "" ]; then
+if [ -e "${prefix_agar_map}/bin/agar-map-config" ]; then
+AGAR_MAP_CFLAGS=`${prefix_agar_map}/bin/agar-map-config --cflags`
 MK_EXEC_FOUND=Yes
-MK_EXEC_PATH="${prefix_agar}/bin/agar-map-config"
+MK_EXEC_PATH="${prefix_agar_map}/bin/agar-map-config"
 fi
 else
 bb_save_IFS=$IFS
@@ -1934,11 +2023,11 @@ done
 IFS=$bb_save_IFS
 fi
 AGAR_MAP_LIBS=
-if [ "${prefix_agar}" != "" ]; then
-if [ -e "${prefix_agar}/bin/agar-map-config" ]; then
-AGAR_MAP_LIBS=`${prefix_agar}/bin/agar-map-config --libs`
+if [ "${prefix_agar_map}" != "" ]; then
+if [ -e "${prefix_agar_map}/bin/agar-map-config" ]; then
+AGAR_MAP_LIBS=`${prefix_agar_map}/bin/agar-map-config --libs`
 MK_EXEC_FOUND=Yes
-MK_EXEC_PATH="${prefix_agar}/bin/agar-map-config"
+MK_EXEC_PATH="${prefix_agar_map}/bin/agar-map-config"
 fi
 else
 bb_save_IFS=$IFS
@@ -2370,6 +2459,10 @@ echo "HAVE_CC=$HAVE_CC" >>Makefile.config
 echo "mdefs[\"HAVE_CC\"] = \"$HAVE_CC\"" >>configure.lua
 echo "HAVE_CC65=$HAVE_CC65" >>Makefile.config
 echo "mdefs[\"HAVE_CC65\"] = \"$HAVE_CC65\"" >>configure.lua
+echo "HAVE_CC_CLANG=$HAVE_CC_CLANG" >>Makefile.config
+echo "mdefs[\"HAVE_CC_CLANG\"] = \"$HAVE_CC_CLANG\"" >>configure.lua
+echo "HAVE_CC_GCC=$HAVE_CC_GCC" >>Makefile.config
+echo "mdefs[\"HAVE_CC_GCC\"] = \"$HAVE_CC_GCC\"" >>configure.lua
 echo "HAVE_CC_MCONSOLE=$HAVE_CC_MCONSOLE" >>Makefile.config
 echo "mdefs[\"HAVE_CC_MCONSOLE\"] = \"$HAVE_CC_MCONSOLE\"" >>configure.lua
 echo "HAVE_CC_MWINDOWS=$HAVE_CC_MWINDOWS" >>Makefile.config
diff --git a/tools/sgedit/configure b/tools/sgedit/configure
--- a/tools/sgedit/configure
+++ b/tools/sgedit/configure
@@ -880,7 +880,14 @@ if [ "${mandir}" != '' ]; then
 	MANDIR="${mandir}"
 	MANDIR_SPECIFIED='yes'
 else
-	MANDIR="${PREFIX}/man"
+	case "${host}" in
+	*-*-darwin*)
+		MANDIR="${PREFIX}/share/man"
+		;;
+	*)
+		MANDIR="${PREFIX}/man"
+		;;
+	esac
 fi
 bb_o=$bb_incdir/mandir.h
 echo '#ifndef MANDIR' >$bb_o
@@ -1079,6 +1086,84 @@ echo "hdefs[\"EXECSUFFIX\"] = \"$EXECSUFFIX\"" >>configure.lua
 	TEST_CFLAGS=''
 fi
 if [ "${HAVE_CC}" = "yes" ]; then
+$ECHO_N 'cc: checking whether compiler is Clang...'
+$ECHO_N '# cc: checking whether compiler is Clang...' >>config.log
+MK_COMPILE_STATUS=OK
+cat << EOT >conftest$$.c
+#if !defined(__clang__)
+# error "is not clang"
+#endif
+int main(int argc, char *argv[]) { return (0); }
+EOT
+echo >>config.log
+echo '# C: HAVE_CC_CLANG' >>config.log
+echo "cat << EOT >conftest$$.c" >>config.log
+cat conftest$$.c>>config.log
+echo EOT >>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest$$ conftest$$.c  2>>config.log">>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest$$ conftest$$.c  2>>config.log
+if [ "$?" != "0" ]; then
+echo "# failed $?" >>config.log
+MK_COMPILE_STATUS="FAIL $?"
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo 'yes'
+echo '# yes' >>config.log
+HAVE_CC_CLANG=yes
+bb_o=$bb_incdir/have_cc_clang.h
+echo '#ifndef HAVE_CC_CLANG' >$bb_o
+echo "#define HAVE_CC_CLANG \"$HAVE_CC_CLANG\"" >>$bb_o
+echo '#endif' >>$bb_o
+echo "hdefs[\"HAVE_CC_CLANG\"] = \"$HAVE_CC_CLANG\"" >>configure.lua
+else
+echo 'no'
+echo '# no' >>config.log
+HAVE_CC_CLANG=no
+echo '#undef HAVE_CC_CLANG' >$bb_incdir/have_cc_clang.h
+echo 'hdefs["HAVE_CC_CLANG"] = nil' >>configure.lua
+fi
+if [ "${keep_conftest}" != "yes" ]; then
+rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
+fi
+$ECHO_N 'cc: checking whether compiler is GCC...'
+$ECHO_N '# cc: checking whether compiler is GCC...' >>config.log
+MK_COMPILE_STATUS=OK
+cat << EOT >conftest$$.c
+#if !defined(__GNUC__) || defined(__clang__)
+# error "is not gcc"
+#endif
+int main(int argc, char *argv[]) { return (0); }
+EOT
+echo >>config.log
+echo '# C: HAVE_CC_GCC' >>config.log
+echo "cat << EOT >conftest$$.c" >>config.log
+cat conftest$$.c>>config.log
+echo EOT >>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest$$ conftest$$.c  2>>config.log">>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest$$ conftest$$.c  2>>config.log
+if [ "$?" != "0" ]; then
+echo "# failed $?" >>config.log
+MK_COMPILE_STATUS="FAIL $?"
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo 'yes'
+echo '# yes' >>config.log
+HAVE_CC_GCC=yes
+bb_o=$bb_incdir/have_cc_gcc.h
+echo '#ifndef HAVE_CC_GCC' >$bb_o
+echo "#define HAVE_CC_GCC \"$HAVE_CC_GCC\"" >>$bb_o
+echo '#endif' >>$bb_o
+echo "hdefs[\"HAVE_CC_GCC\"] = \"$HAVE_CC_GCC\"" >>configure.lua
+else
+echo 'no'
+echo '# no' >>config.log
+HAVE_CC_GCC=no
+echo '#undef HAVE_CC_GCC' >$bb_incdir/have_cc_gcc.h
+echo 'hdefs["HAVE_CC_GCC"] = nil' >>configure.lua
+fi
+if [ "${keep_conftest}" != "yes" ]; then
+rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
+fi
 $ECHO_N 'cc: checking for compiler warning options...'
 $ECHO_N '# cc: checking for compiler warning options...' >>config.log
 MK_COMPILE_STATUS=OK
@@ -1496,6 +1581,10 @@ LIBTOOLOPTS_SHARED=""
 TEST_CFLAGS=""
 echo '#undef HAVE_CC' >$bb_incdir/have_cc.h
 echo 'hdefs["HAVE_CC"] = nil' >>configure.lua
+echo '#undef HAVE_CC_CLANG' >$bb_incdir/have_cc_clang.h
+echo 'hdefs["HAVE_CC_CLANG"] = nil' >>configure.lua
+echo '#undef HAVE_CC_GCC' >$bb_incdir/have_cc_gcc.h
+echo 'hdefs["HAVE_CC_GCC"] = nil' >>configure.lua
 echo '#undef HAVE_CC65' >$bb_incdir/have_cc65.h
 echo 'hdefs["HAVE_CC65"] = nil' >>configure.lua
 echo '#undef HAVE_CC_WARNINGS' >$bb_incdir/have_cc_warnings.h
@@ -1525,7 +1614,10 @@ echo '* This software requires a C compiler'
 echo '# * This software requires a C compiler' >>config.log
 echo '* '
 echo '# * ' >>config.log
-echo "Required dependency cc not found"
+echo "***"
+echo "*** ERROR: Required dependency cc not found"
+echo "*** Failed! See ./config.log for more details."
+echo "***"
 exit 1
 fi
 $ECHO_N 'checking for Agar...'
@@ -1745,7 +1837,10 @@ echo '* WWW: http://libagar.org'
 echo '# * WWW: http://libagar.org' >>config.log
 echo '* '
 echo '# * ' >>config.log
-echo "Required dependency agar not found"
+echo "***"
+echo "*** ERROR: Required dependency agar not found"
+echo "*** Failed! See ./config.log for more details."
+echo "***"
 exit 1
 fi
 if [ "${MK_VERSION_OK}" != "yes" ]; then
@@ -1759,7 +1854,10 @@ echo '* WWW: http://libagar.org'
 echo '# * WWW: http://libagar.org' >>config.log
 echo '* '
 echo '# * ' >>config.log
-echo "Required dependency agar version mismatch"
+echo "***"
+echo "*** ERROR: Required dependency agar version mismatch"
+echo "*** Failed! See ./config.log for more details."
+echo "***"
 exit 1
 fi
 $ECHO_N 'checking for Agar-Math...'
@@ -1945,7 +2043,8 @@ fi
 MK_COMPILE_STATUS=OK
 cat << EOT >conftest$$.c
 #include <agar/core.h>
-#include <agar/math.h>
+#include <agar/gui.h>
+#include <agar/math/m.h>
 
 int main(int argc, char *argv[]) {
 	M_Matrix *A = M_New(2,2);
@@ -2026,7 +2125,10 @@ echo '* WWW: http://libagar.org'
 echo '# * WWW: http://libagar.org' >>config.log
 echo '* '
 echo '# * ' >>config.log
-echo "Required dependency agar-math not found"
+echo "***"
+echo "*** ERROR: Required dependency agar-math not found"
+echo "*** Failed! See ./config.log for more details."
+echo "***"
 exit 1
 fi
 if [ "${MK_VERSION_OK}" != "yes" ]; then
@@ -2040,7 +2142,10 @@ echo '* WWW: http://libagar.org'
 echo '# * WWW: http://libagar.org' >>config.log
 echo '* '
 echo '# * ' >>config.log
-echo "Required dependency agar-math version mismatch"
+echo "***"
+echo "*** ERROR: Required dependency agar-math version mismatch"
+echo "*** Failed! See ./config.log for more details."
+echo "***"
 exit 1
 fi
 $ECHO_N 'checking for Agar-SG...'
@@ -2306,7 +2411,10 @@ echo '* WWW: http://libagar.org'
 echo '# * WWW: http://libagar.org' >>config.log
 echo '* '
 echo '# * ' >>config.log
-echo "Required dependency agar-sg not found"
+echo "***"
+echo "*** ERROR: Required dependency agar-sg not found"
+echo "*** Failed! See ./config.log for more details."
+echo "***"
 exit 1
 fi
 if [ "${MK_VERSION_OK}" != "yes" ]; then
@@ -2320,7 +2428,10 @@ echo '* WWW: http://libagar.org'
 echo '# * WWW: http://libagar.org' >>config.log
 echo '* '
 echo '# * ' >>config.log
-echo "Required dependency agar-sg version mismatch"
+echo "***"
+echo "*** ERROR: Required dependency agar-sg version mismatch"
+echo "*** Failed! See ./config.log for more details."
+echo "***"
 exit 1
 fi
 if [ "${enable_nls}" = "yes" ]
@@ -2572,7 +2683,10 @@ echo '* This software requires a gettext library in libc'
 echo '# * This software requires a gettext library in libc' >>config.log
 echo '* '
 echo '# * ' >>config.log
-echo "Required dependency gettext not found"
+echo "***"
+echo "*** ERROR: Required dependency gettext not found"
+echo "*** Failed! See ./config.log for more details."
+echo "***"
 exit 1
 fi
 fi
@@ -2630,6 +2744,10 @@ echo "HAVE_CC=$HAVE_CC" >>Makefile.config
 echo "mdefs[\"HAVE_CC\"] = \"$HAVE_CC\"" >>configure.lua
 echo "HAVE_CC65=$HAVE_CC65" >>Makefile.config
 echo "mdefs[\"HAVE_CC65\"] = \"$HAVE_CC65\"" >>configure.lua
+echo "HAVE_CC_CLANG=$HAVE_CC_CLANG" >>Makefile.config
+echo "mdefs[\"HAVE_CC_CLANG\"] = \"$HAVE_CC_CLANG\"" >>configure.lua
+echo "HAVE_CC_GCC=$HAVE_CC_GCC" >>Makefile.config
+echo "mdefs[\"HAVE_CC_GCC\"] = \"$HAVE_CC_GCC\"" >>configure.lua
 echo "HAVE_CC_MCONSOLE=$HAVE_CC_MCONSOLE" >>Makefile.config
 echo "mdefs[\"HAVE_CC_MCONSOLE\"] = \"$HAVE_CC_MCONSOLE\"" >>configure.lua
 echo "HAVE_CC_MWINDOWS=$HAVE_CC_MWINDOWS" >>Makefile.config
@@ -2694,10 +2812,10 @@ if [ "${srcdir}" != '' ]; then
 	fi
 	echo 'ok'
 fi
-echo '*'
-echo '* Configuration successful!'
-echo '*'
-echo '* Use "make depend all" to compile. When finished,'
-$ECHO_N '* run "make install" to install under '
+echo '**'
+echo '** Configuration successful!'
+echo '**'
+echo '** Use "make depend all" to compile. When finished,'
+$ECHO_N '** run "make install" to install under '
 echo "${PREFIX}."
-echo '*'
+echo '**'
