regen
git-svn-id: https://dev.csoft.net/agar/trunk@6848 86a84d31-9702-0410-8f1e-a60cab7bd424

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2305,6 +2305,164 @@ echo "ALTIVEC_CFLAGS=$ALTIVEC_CFLAGS" >> Makefile.config
 fi;
 echo "#undef HAVE_ALTIVEC_H" > config/have_altivec_h.h
 fi;
+echo -n "checking for byte order..."
+echo -n "checking for byte order..." >> config.log
+echo ""
+echo "" >> config.log
+echo -n "checking for BIG_ENDIAN..."
+echo -n "checking for BIG_ENDIAN..." >> config.log
+cat << EOT > conftest.c
+#include <sys/types.h>
+#include <sys/param.h>
+int
+main(int argc, char *argv[])
+{
+#if BYTE_ORDER == BIG_ENDIAN
+	return (0);
+#else
+	return (1);
+#endif
+}
+bad
+
+EOT
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+if [ $? != 0 ]; then
+echo "no (compile failed)"
+echo "no (compile failed)" >> config.log
+compile="failed"
+_MK_BIG_ENDIAN="no"
+echo "_MK_BIG_ENDIAN=$_MK_BIG_ENDIAN" >> Makefile.config
+echo "#undef _MK_BIG_ENDIAN" > config/_mk_big_endian.h
+else
+compile="ok"
+(cd $testdir && ./conftest) >> config.log
+if [ "$?" = "0" ]; then
+echo "yes"
+echo "yes" >> config.log
+_MK_BIG_ENDIAN="yes"
+echo "_MK_BIG_ENDIAN=$_MK_BIG_ENDIAN" >> Makefile.config
+echo "#ifndef _MK_BIG_ENDIAN" > config/_mk_big_endian.h
+echo "#define _MK_BIG_ENDIAN \"$_MK_BIG_ENDIAN\"" >> config/_mk_big_endian.h
+echo "#endif" >> config/_mk_big_endian.h
+else
+echo "no (exec failed)"
+echo "no (exec failed)" >> config.log
+_MK_BIG_ENDIAN="no"
+echo "_MK_BIG_ENDIAN=$_MK_BIG_ENDIAN" >> Makefile.config
+echo "#undef _MK_BIG_ENDIAN" > config/_mk_big_endian.h
+fi;
+fi;
+rm -f $testdir/conftest conftest.c
+if [ "${_MK_BIG_ENDIAN}" = "yes" ]; then
+_MK_LITTLE_ENDIAN="no"
+echo "#undef _MK_LITTLE_ENDIAN" > config/_mk_little_endian.h
+else
+echo -n "checking for LITTLE_ENDIAN..."
+echo -n "checking for LITTLE_ENDIAN..." >> config.log
+cat << EOT > conftest.c
+#include <sys/types.h>
+#include <sys/param.h>
+int
+main(int argc, char *argv[])
+{
+#if BYTE_ORDER == LITTLE_ENDIAN
+	return (0);
+#else
+	return (1);
+#endif
+}
+bad
+
+EOT
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+if [ $? != 0 ]; then
+echo "no (compile failed)"
+echo "no (compile failed)" >> config.log
+compile="failed"
+_MK_LITTLE_ENDIAN="no"
+echo "_MK_LITTLE_ENDIAN=$_MK_LITTLE_ENDIAN" >> Makefile.config
+echo "#undef _MK_LITTLE_ENDIAN" > config/_mk_little_endian.h
+else
+compile="ok"
+(cd $testdir && ./conftest) >> config.log
+if [ "$?" = "0" ]; then
+echo "yes"
+echo "yes" >> config.log
+_MK_LITTLE_ENDIAN="yes"
+echo "_MK_LITTLE_ENDIAN=$_MK_LITTLE_ENDIAN" >> Makefile.config
+echo "#ifndef _MK_LITTLE_ENDIAN" > config/_mk_little_endian.h
+echo "#define _MK_LITTLE_ENDIAN \"$_MK_LITTLE_ENDIAN\"" >> config/_mk_little_endian.h
+echo "#endif" >> config/_mk_little_endian.h
+else
+echo "no (exec failed)"
+echo "no (exec failed)" >> config.log
+_MK_LITTLE_ENDIAN="no"
+echo "_MK_LITTLE_ENDIAN=$_MK_LITTLE_ENDIAN" >> Makefile.config
+echo "#undef _MK_LITTLE_ENDIAN" > config/_mk_little_endian.h
+fi;
+fi;
+rm -f $testdir/conftest conftest.c
+if [ "${_MK_LITTLE_ENDIAN}" = "yes" ]; then
+_MK_BIG_ENDIAN="no"
+echo "#undef _MK_BIG_ENDIAN" > config/_mk_big_endian.h
+else
+echo -n "checking for little endian byte order..."
+echo -n "checking for little endian byte order..." >> config.log
+cat << EOT > conftest.c
+int
+main(int argc, char *argv[])
+{
+	union {
+		long l;
+		char c[sizeof (long)];
+	} u;
+	u.l = 1;
+	return (u.c[sizeof (long) - 1] == 1);
+}
+
+EOT
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+if [ $? != 0 ]; then
+echo "no (compile failed)"
+echo "no (compile failed)" >> config.log
+compile="failed"
+_MK_LITTLE_ENDIAN="no"
+echo "_MK_LITTLE_ENDIAN=$_MK_LITTLE_ENDIAN" >> Makefile.config
+echo "#undef _MK_LITTLE_ENDIAN" > config/_mk_little_endian.h
+else
+compile="ok"
+(cd $testdir && ./conftest) >> config.log
+if [ "$?" = "0" ]; then
+echo "yes"
+echo "yes" >> config.log
+_MK_LITTLE_ENDIAN="yes"
+echo "_MK_LITTLE_ENDIAN=$_MK_LITTLE_ENDIAN" >> Makefile.config
+echo "#ifndef _MK_LITTLE_ENDIAN" > config/_mk_little_endian.h
+echo "#define _MK_LITTLE_ENDIAN \"$_MK_LITTLE_ENDIAN\"" >> config/_mk_little_endian.h
+echo "#endif" >> config/_mk_little_endian.h
+else
+echo "no (exec failed)"
+echo "no (exec failed)" >> config.log
+_MK_LITTLE_ENDIAN="no"
+echo "_MK_LITTLE_ENDIAN=$_MK_LITTLE_ENDIAN" >> Makefile.config
+echo "#undef _MK_LITTLE_ENDIAN" > config/_mk_little_endian.h
+fi;
+fi;
+rm -f $testdir/conftest conftest.c
+if [ "${compile}" = "failed" ]; then
+echo "Unable to determine byte order"
+exit 1
+fi;
+if [ "${_MK_LITTLE_ENDIAN}" = "yes" ]; then
+_MK_BIG_ENDIAN="no"
+echo "#undef _MK_BIG_ENDIAN" > config/_mk_big_endian.h
+fi;
+fi;
+fi;
 CFLAGS="$CFLAGS -D_AGAR_INTERNAL"
 CXXFLAGS="$CXXFLAGS -D_AGAR_INTERNAL"
 echo "CFLAGS=$CFLAGS" >> Makefile.config
