sync; rien
git-svn-id: https://dev.csoft.net/agar/trunk@1998 86a84d31-9702-0410-8f1e-a60cab7bd424

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -92,10 +92,17 @@ else
     PREFIX=/usr/local
 fi
 
-SRC=.
-BUILD=.
+if [ "${srcdir}" != "" ]; then
+	if [ ! -e "${srcdir}" ]; then
+		echo "Cannot find source directory `${srcdir}'"
+		exit 1
+	fi
+	SRC=${srcdir}
+else
+	SRC=.
+fi
 
-echo > $BUILD/config.log
+echo > config.log
 
 echo >Makefile.config
 if [ "${help}" = "yes" ]
@@ -131,8 +138,8 @@ echo FOBJDIR=$FOBJDIR >> Makefile.config
 INST_MANDIR="$PREFIX/share/agar/man"
 echo INST_MANDIR=$INST_MANDIR >> Makefile.config
 echo -n "checking for a usable C compiler..."
-echo -n "checking for a usable C compiler..." >> $BUILD/config.log
-echo "checking for a usable C compiler..." >> $BUILD/config.log
+echo -n "checking for a usable C compiler..." >> config.log
+echo "checking for a usable C compiler..." >> config.log
 if [ "$CC" = "" ]; then
 	for i in `echo $PATH |sed 's/:/ /g'`; do
 		if [ -x "${i}/cc" ]; then
@@ -159,10 +166,10 @@ main(int argc, char *argv[])
 }
 EOT
 
-echo "$CC -o .cctest .cctest.c" >>$BUILD/config.log
-$CC -o .cctest .cctest.c 2>>$BUILD/config.log
+echo "$CC -o .cctest .cctest.c" >>config.log
+$CC -o .cctest .cctest.c 2>>config.log
 if [ $? != 0 -o ! -e .cctest ]; then
-    echo "-> failure" >> $BUILD/config.log
+    echo "-> failure" >> config.log
     echo "no"
     exit 1
 fi
@@ -170,16 +177,16 @@ fi
 cc_is_gcc=no
 if ./.cctest; then
     cc_is_gcc=yes
-    echo "-> success: gcc" >> $BUILD/config.log
+    echo "-> success: gcc" >> config.log
     echo "yes"
 else
     echo "yes"
-    echo "-> success" >> $BUILD/config.log
+    echo "-> success" >> config.log
 fi
 
 rm -f .cctest .cctest.c
 echo -n "checking for IEEE 754 floating point..."
-echo -n "checking for IEEE 754 floating point..." >> $BUILD/config.log
+echo -n "checking for IEEE 754 floating point..." >> config.log
 cat << EOT > conftest.c
 #include <stdio.h>
 
@@ -195,20 +202,20 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-echo "$CC -o conftest conftest.c" >> $BUILD/config.log
-$CC -o conftest conftest.c 2>>$BUILD/config.log
+echo "$CC -o conftest conftest.c" >> config.log
+$CC -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
-	echo "-> failed: non-zero exit status" >> $BUILD/config.log
+	echo "-> failed: non-zero exit status" >> config.log
 	compile="failed"
 else
     if [ ! -e "conftest" ]; then
-	    echo "-> failed: compiler did not produce an executable" >> $BUILD/config.log
+	    echo "-> failed: compiler did not produce an executable" >> config.log
 	    compile="failed"
     fi
 fi
 rm -f conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "-> success" >> $BUILD/config.log
+	echo "-> success" >> config.log
 	echo "#ifndef HAVE_IEEE754" > engine/config/have_ieee754.h
 echo "#define HAVE_IEEE754" $HAVE_IEEE754 >> engine/config/have_ieee754.h
 echo "#endif /* HAVE_IEEE754 */" >> engine/config/have_ieee754.h
@@ -220,7 +227,7 @@ else
 	echo "no"
 fi
 echo -n "checking for long double..."
-echo -n "checking for long double..." >> $BUILD/config.log
+echo -n "checking for long double..." >> config.log
 cat << EOT > conftest.c
 int
 main(int argc, char *argv[])
@@ -233,20 +240,20 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-echo "$CC -o conftest conftest.c" >> $BUILD/config.log
-$CC -o conftest conftest.c 2>>$BUILD/config.log
+echo "$CC -o conftest conftest.c" >> config.log
+$CC -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
-	echo "-> failed: non-zero exit status" >> $BUILD/config.log
+	echo "-> failed: non-zero exit status" >> config.log
 	compile="failed"
 else
     if [ ! -e "conftest" ]; then
-	    echo "-> failed: compiler did not produce an executable" >> $BUILD/config.log
+	    echo "-> failed: compiler did not produce an executable" >> config.log
 	    compile="failed"
     fi
 fi
 rm -f conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "-> success" >> $BUILD/config.log
+	echo "-> success" >> config.log
 	echo "#ifndef HAVE_LONG_DOUBLE" > engine/config/have_long_double.h
 echo "#define HAVE_LONG_DOUBLE" $HAVE_LONG_DOUBLE >> engine/config/have_long_double.h
 echo "#endif /* HAVE_LONG_DOUBLE */" >> engine/config/have_long_double.h
@@ -258,8 +265,8 @@ else
 	echo "no"
 fi
 echo -n "checking for a getenv() function..."
-echo -n "checking for a getenv() function..." >> $BUILD/config.log
-echo "checking for a getenv() function..." >> $BUILD/config.log
+echo -n "checking for a getenv() function..." >> config.log
+echo "checking for a getenv() function..." >> config.log
 cat << EOT > conftest.c
 #include <stdlib.h>
 int
@@ -271,20 +278,20 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-echo "$CC -o conftest conftest.c" >> $BUILD/config.log
-$CC -o conftest conftest.c 2>>$BUILD/config.log
+echo "$CC -o conftest conftest.c" >> config.log
+$CC -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
-	echo "-> failed: non-zero exit status" >> $BUILD/config.log
+	echo "-> failed: non-zero exit status" >> config.log
 	compile="failed"
 else
     if [ ! -e "conftest" ]; then
-	    echo "-> failed: compiler did not produce an executable" >> $BUILD/config.log
+	    echo "-> failed: compiler did not produce an executable" >> config.log
 	    compile="failed"
     fi
 fi
 rm -f conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "-> success" >> $BUILD/config.log
+	echo "-> success" >> config.log
 	echo "#ifndef HAVE_GETENV" > engine/config/have_getenv.h
 echo "#define HAVE_GETENV" $HAVE_GETENV >> engine/config/have_getenv.h
 echo "#endif /* HAVE_GETENV */" >> engine/config/have_getenv.h
@@ -296,8 +303,8 @@ else
 	echo "no"
 fi
 echo -n "checking for setenv() and unsetenv() functions..."
-echo -n "checking for setenv() and unsetenv() functions..." >> $BUILD/config.log
-echo "checking for setenv() and unsetenv() functions..." >> $BUILD/config.log
+echo -n "checking for setenv() and unsetenv() functions..." >> config.log
+echo "checking for setenv() and unsetenv() functions..." >> config.log
 cat << EOT > conftest.c
 #include <stdlib.h>
 int
@@ -311,20 +318,20 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-echo "$CC -o conftest conftest.c" >> $BUILD/config.log
-$CC -o conftest conftest.c 2>>$BUILD/config.log
+echo "$CC -o conftest conftest.c" >> config.log
+$CC -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
-	echo "-> failed: non-zero exit status" >> $BUILD/config.log
+	echo "-> failed: non-zero exit status" >> config.log
 	compile="failed"
 else
     if [ ! -e "conftest" ]; then
-	    echo "-> failed: compiler did not produce an executable" >> $BUILD/config.log
+	    echo "-> failed: compiler did not produce an executable" >> config.log
 	    compile="failed"
     fi
 fi
 rm -f conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "-> success" >> $BUILD/config.log
+	echo "-> success" >> config.log
 	echo "#ifndef HAVE_SETENV" > engine/config/have_setenv.h
 echo "#define HAVE_SETENV" $HAVE_SETENV >> engine/config/have_setenv.h
 echo "#endif /* HAVE_SETENV */" >> engine/config/have_setenv.h
@@ -336,8 +343,8 @@ else
 	echo "no"
 fi
 echo -n "checking for a strsep() function..."
-echo -n "checking for a strsep() function..." >> $BUILD/config.log
-echo "checking for a strsep() function..." >> $BUILD/config.log
+echo -n "checking for a strsep() function..." >> config.log
+echo "checking for a strsep() function..." >> config.log
 cat << EOT > conftest.c
 #include <string.h>
 int
@@ -349,20 +356,20 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-echo "$CC -o conftest conftest.c" >> $BUILD/config.log
-$CC -o conftest conftest.c 2>>$BUILD/config.log
+echo "$CC -o conftest conftest.c" >> config.log
+$CC -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
-	echo "-> failed: non-zero exit status" >> $BUILD/config.log
+	echo "-> failed: non-zero exit status" >> config.log
 	compile="failed"
 else
     if [ ! -e "conftest" ]; then
-	    echo "-> failed: compiler did not produce an executable" >> $BUILD/config.log
+	    echo "-> failed: compiler did not produce an executable" >> config.log
 	    compile="failed"
     fi
 fi
 rm -f conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "-> success" >> $BUILD/config.log
+	echo "-> success" >> config.log
 	echo "#ifndef HAVE_STRSEP" > engine/config/have_strsep.h
 echo "#define HAVE_STRSEP" $HAVE_STRSEP >> engine/config/have_strsep.h
 echo "#endif /* HAVE_STRSEP */" >> engine/config/have_strsep.h
@@ -374,8 +381,8 @@ else
 	echo "no"
 fi
 echo -n "checking for a strlcat() function..."
-echo -n "checking for a strlcat() function..." >> $BUILD/config.log
-echo "checking for a strlcat() function..." >> $BUILD/config.log
+echo -n "checking for a strlcat() function..." >> config.log
+echo "checking for a strlcat() function..." >> config.log
 cat << EOT > conftest.c
 #include <string.h>
 int
@@ -387,20 +394,20 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-echo "$CC -o conftest conftest.c" >> $BUILD/config.log
-$CC -o conftest conftest.c 2>>$BUILD/config.log
+echo "$CC -o conftest conftest.c" >> config.log
+$CC -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
-	echo "-> failed: non-zero exit status" >> $BUILD/config.log
+	echo "-> failed: non-zero exit status" >> config.log
 	compile="failed"
 else
     if [ ! -e "conftest" ]; then
-	    echo "-> failed: compiler did not produce an executable" >> $BUILD/config.log
+	    echo "-> failed: compiler did not produce an executable" >> config.log
 	    compile="failed"
     fi
 fi
 rm -f conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "-> success" >> $BUILD/config.log
+	echo "-> success" >> config.log
 	echo "#ifndef HAVE_STRLCAT" > engine/config/have_strlcat.h
 echo "#define HAVE_STRLCAT" $HAVE_STRLCAT >> engine/config/have_strlcat.h
 echo "#endif /* HAVE_STRLCAT */" >> engine/config/have_strlcat.h
@@ -412,8 +419,8 @@ else
 	echo "no"
 fi
 echo -n "checking for a strlcpy() function..."
-echo -n "checking for a strlcpy() function..." >> $BUILD/config.log
-echo "checking for a strlcpy() function..." >> $BUILD/config.log
+echo -n "checking for a strlcpy() function..." >> config.log
+echo "checking for a strlcpy() function..." >> config.log
 cat << EOT > conftest.c
 #include <string.h>
 int
@@ -425,20 +432,20 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-echo "$CC -o conftest conftest.c" >> $BUILD/config.log
-$CC -o conftest conftest.c 2>>$BUILD/config.log
+echo "$CC -o conftest conftest.c" >> config.log
+$CC -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
-	echo "-> failed: non-zero exit status" >> $BUILD/config.log
+	echo "-> failed: non-zero exit status" >> config.log
 	compile="failed"
 else
     if [ ! -e "conftest" ]; then
-	    echo "-> failed: compiler did not produce an executable" >> $BUILD/config.log
+	    echo "-> failed: compiler did not produce an executable" >> config.log
 	    compile="failed"
     fi
 fi
 rm -f conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "-> success" >> $BUILD/config.log
+	echo "-> success" >> config.log
 	echo "#ifndef HAVE_STRLCPY" > engine/config/have_strlcpy.h
 echo "#define HAVE_STRLCPY" $HAVE_STRLCPY >> engine/config/have_strlcpy.h
 echo "#endif /* HAVE_STRLCPY */" >> engine/config/have_strlcpy.h
@@ -450,8 +457,8 @@ else
 	echo "no"
 fi
 echo -n "checking for an asprintf() function..."
-echo -n "checking for an asprintf() function..." >> $BUILD/config.log
-echo "checking for an asprintf() function..." >> $BUILD/config.log
+echo -n "checking for an asprintf() function..." >> config.log
+echo "checking for an asprintf() function..." >> config.log
 cat << EOT > conftest.c
 #include <stdio.h>
 
@@ -469,20 +476,20 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-echo "$CC -o conftest conftest.c" >> $BUILD/config.log
-$CC -o conftest conftest.c 2>>$BUILD/config.log
+echo "$CC -o conftest conftest.c" >> config.log
+$CC -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
-	echo "-> failed: non-zero exit status" >> $BUILD/config.log
+	echo "-> failed: non-zero exit status" >> config.log
 	compile="failed"
 else
     if [ ! -e "conftest" ]; then
-	    echo "-> failed: compiler did not produce an executable" >> $BUILD/config.log
+	    echo "-> failed: compiler did not produce an executable" >> config.log
 	    compile="failed"
     fi
 fi
 rm -f conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "-> success" >> $BUILD/config.log
+	echo "-> success" >> config.log
 	echo "#ifndef HAVE_ASPRINTF" > engine/config/have_asprintf.h
 echo "#define HAVE_ASPRINTF" $HAVE_ASPRINTF >> engine/config/have_asprintf.h
 echo "#endif /* HAVE_ASPRINTF */" >> engine/config/have_asprintf.h
@@ -494,8 +501,8 @@ else
 	echo "no"
 fi
 echo -n "checking for a vasprintf() function..."
-echo -n "checking for a vasprintf() function..." >> $BUILD/config.log
-echo "checking for a vasprintf() function..." >> $BUILD/config.log
+echo -n "checking for a vasprintf() function..." >> config.log
+echo "checking for a vasprintf() function..." >> config.log
 cat << EOT > conftest.c
 #include <stdio.h>
 #include <stdarg.h>
@@ -524,20 +531,20 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-echo "$CC -o conftest conftest.c" >> $BUILD/config.log
-$CC -o conftest conftest.c 2>>$BUILD/config.log
+echo "$CC -o conftest conftest.c" >> config.log
+$CC -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
-	echo "-> failed: non-zero exit status" >> $BUILD/config.log
+	echo "-> failed: non-zero exit status" >> config.log
 	compile="failed"
 else
     if [ ! -e "conftest" ]; then
-	    echo "-> failed: compiler did not produce an executable" >> $BUILD/config.log
+	    echo "-> failed: compiler did not produce an executable" >> config.log
 	    compile="failed"
     fi
 fi
 rm -f conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "-> success" >> $BUILD/config.log
+	echo "-> success" >> config.log
 	echo "#ifndef HAVE_VASPRINTF" > engine/config/have_vasprintf.h
 echo "#define HAVE_VASPRINTF" $HAVE_VASPRINTF >> engine/config/have_vasprintf.h
 echo "#endif /* HAVE_VASPRINTF */" >> engine/config/have_vasprintf.h
@@ -556,8 +563,8 @@ CFLAGS="$CFLAGS -Wall -Werror -Wmissing-prototypes -Wno-unused"
 echo CFLAGS=$CFLAGS >> Makefile.config
 fi
 echo -n "checking for SDL (http://www.libsdl.org)..."
-echo -n "checking for SDL (http://www.libsdl.org)..." >> $BUILD/config.log
-echo "checking for SDL (http://www.libsdl.org)..." >> $BUILD/config.log
+echo -n "checking for SDL (http://www.libsdl.org)..." >> config.log
+echo "checking for SDL (http://www.libsdl.org)..." >> config.log
 sdl_version=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/sdl-config" ]; then
@@ -612,13 +619,13 @@ NONE=1
 fi
 if [ "${sdl_found}" = "yes" ]; then
 echo "ok"
-echo "ok" >> $BUILD/config.log
+echo "ok" >> config.log
 else
 echo "Could not find the SDL library. Make sure sdl-config is in $PATH."
 exit 1
 fi
 echo -n "checking whether SDL works..."
-echo -n "checking whether SDL works..." >> $BUILD/config.log
+echo -n "checking whether SDL works..." >> config.log
 cat << EOT > conftest.c
 
 #include <stdio.h>
@@ -650,19 +657,19 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-echo $CC ${SDL_CFLAGS} -o conftest conftest.c ${SDL_LIBS} >> $BUILD/config.log
-$CC ${SDL_CFLAGS} -o conftest conftest.c ${SDL_LIBS} 2>>$BUILD/config.log
+echo $CC ${SDL_CFLAGS} -o conftest conftest.c ${SDL_LIBS} >> config.log
+$CC ${SDL_CFLAGS} -o conftest conftest.c ${SDL_LIBS} 2>>config.log
 if [ $? != 0 ]; then
-	echo "-> failed: compiler had non-zero exit status" >> $BUILD/config.log
+	echo "-> failed: compiler had non-zero exit status" >> config.log
 	compile="failed"
 fi
 if [ ! -e "conftest" ]; then
-	echo "-> failed: compiler did not produce an executable" >> $BUILD/config.log
+	echo "-> failed: compiler did not produce an executable" >> config.log
 	compile="failed"
 fi
 rm -f conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "-> success" >> $BUILD/config.log
+	echo "-> success" >> config.log
 	echo "#ifndef HAVE_SDL" > engine/config/have_sdl.h
 echo "#define HAVE_SDL" $HAVE_SDL >> engine/config/have_sdl.h
 echo "#endif /* HAVE_SDL */" >> engine/config/have_sdl.h
@@ -682,8 +689,8 @@ echo "The SDL test would not compile."
 exit 1
 fi
 echo -n "checking for FreeType (http://www.freetype.org)..."
-echo -n "checking for FreeType (http://www.freetype.org)..." >> $BUILD/config.log
-echo "checking for FreeType (http://www.freetype.org)..." >> $BUILD/config.log
+echo -n "checking for FreeType (http://www.freetype.org)..." >> config.log
+echo "checking for FreeType (http://www.freetype.org)..." >> config.log
 FREETYPE_VERSION=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/freetype-config" ]; then
@@ -712,13 +719,13 @@ freetype_found=yes
 echo FREETYPE_CFLAGS=$FREETYPE_CFLAGS >> Makefile.config
 echo FREETYPE_LIBS=$FREETYPE_LIBS >> Makefile.config
 echo "yes"
-echo "yes" >> $BUILD/config.log
+echo "yes" >> config.log
 else
 echo "Could not find the FreeType library"
 exit 1
 fi
 echo -n "checking whether FreeType works..."
-echo -n "checking whether FreeType works..." >> $BUILD/config.log
+echo -n "checking whether FreeType works..." >> config.log
 cat << EOT > conftest.c
 #include <stdio.h>
 
@@ -739,19 +746,19 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-echo $CC ${FREETYPE_CFLAGS} -o conftest conftest.c ${FREETYPE_LIBS} >> $BUILD/config.log
-$CC ${FREETYPE_CFLAGS} -o conftest conftest.c ${FREETYPE_LIBS} 2>>$BUILD/config.log
+echo $CC ${FREETYPE_CFLAGS} -o conftest conftest.c ${FREETYPE_LIBS} >> config.log
+$CC ${FREETYPE_CFLAGS} -o conftest conftest.c ${FREETYPE_LIBS} 2>>config.log
 if [ $? != 0 ]; then
-	echo "-> failed: compiler had non-zero exit status" >> $BUILD/config.log
+	echo "-> failed: compiler had non-zero exit status" >> config.log
 	compile="failed"
 fi
 if [ ! -e "conftest" ]; then
-	echo "-> failed: compiler did not produce an executable" >> $BUILD/config.log
+	echo "-> failed: compiler did not produce an executable" >> config.log
 	compile="failed"
 fi
 rm -f conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "-> success" >> $BUILD/config.log
+	echo "-> success" >> config.log
 	echo "#ifndef HAVE_FREETYPE" > engine/config/have_freetype.h
 echo "#define HAVE_FREETYPE" $HAVE_FREETYPE >> engine/config/have_freetype.h
 echo "#endif /* HAVE_FREETYPE */" >> engine/config/have_freetype.h
@@ -773,8 +780,8 @@ fi
 if [ "${with_x11}" != "no" ]
  then
 echo -n "checking for X11 (http://www.xfree86.org/)..."
-echo -n "checking for X11 (http://www.xfree86.org/)..." >> $BUILD/config.log
-echo "checking for X11 (http://www.xfree86.org/)..." >> $BUILD/config.log
+echo -n "checking for X11 (http://www.xfree86.org/)..." >> config.log
+echo "checking for X11 (http://www.xfree86.org/)..." >> config.log
 if [ -d /usr/X11R6 ]; then
 X11BASE=/usr/X11R6
 X11_CFLAGS=-I/usr/X11R6/include
@@ -798,9 +805,9 @@ NONE=1
 fi
 if [ "${X11BASE}" != "" ]; then
 echo -n "ok"
-echo -n "ok" >> $BUILD/config.log
+echo -n "ok" >> config.log
 echo ", $X11BASE"
-echo ", $X11BASE" >> $BUILD/config.log
+echo ", $X11BASE" >> config.log
 x11_found=yes
 echo X11BASE=$X11BASE >> Makefile.config
 echo X11_CFLAGS=$X11_CFLAGS >> Makefile.config
@@ -910,4 +917,4 @@ echo "#ifndef PREFIX" > engine/config/prefix.h
 echo "#define PREFIX \"$PREFIX\"" >> engine/config/prefix.h
 echo "#endif /* PREFIX */" >> engine/config/prefix.h
 echo "Don't forget to run \"make depend\"."
-echo "Don't forget to run \"make depend\"." >> $BUILD/config.log
+echo "Don't forget to run \"make depend\"." >> config.log
