sync; rien
git-svn-id: https://dev.csoft.net/agar/trunk@2009 86a84d31-9702-0410-8f1e-a60cab7bd424

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -96,7 +96,7 @@ else
 fi
 
 if [ "${srcdir}" != "" ]; then
-	echo "Concurrent build (source in ${srcdir})"
+	echo "concurrent build (source in ${srcdir})"
 	if [ ! -e "${srcdir}" ]; then
 		echo "Cannot find source directory: ${srcdir}"
 		exit 1
@@ -107,6 +107,10 @@ if [ "${srcdir}" != "" ]; then
 	fi
 	SRC=${srcdir}
 else
+	if [ ! -e "configure.in" ]; then
+		echo "Missing --srcdir argument"
+		exit 1
+	fi
 	SRC=.
 fi
 
