use the BSDBuild includes preprocessor
git-svn-id: https://dev.csoft.net/agar/trunk@7867 86a84d31-9702-0410-8f1e-a60cab7bd424

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -115,6 +115,9 @@ do
 	--cache=*)
 	    cache=$optarg
 	    ;;
+	--includes=*)
+	    includes=$optarg
+	    ;;
 	*)
 	    echo "invalid argument: $arg"
 	    echo "try ./configure --help"
@@ -150,6 +153,7 @@ if [ "${srcdir}" != "" ]; then
 else
 	SRC=`pwd`
 fi
+BLD=`pwd`
 
 if [ "${testdir}" != "" ]; then
 	echo "Configure tests will be executed in ${testdir}"
@@ -160,6 +164,24 @@ if [ "${testdir}" != "" ]; then
 else
 	testdir="."
 fi
+
+if [ "${includes}" = "" ]; then
+	includes="yes"
+fi
+if [ "${includes}" = "link" ]; then
+	if [ "${with_proj_generation}" ]; then
+		echo "Cannot use --includes=link with --with-proj-generation!"
+		exit 1
+	fi
+elif [ "${includes}" = "yes" ]; then
+	noop=1
+elif [ "${includes}" = "no" ]; then
+	noop=1
+else
+	echo "Usage: --includes [yes|no|link]"
+	exit 1
+fi
+
 if [ "${help}" = "yes" ]; then
 echo "Usage: ./configure [args]"
 echo "    --prefix                  Installation prefix [/usr/local]"
@@ -177,6 +199,7 @@ echo "    --with-manpages           Manual pages (-mdoc) [yes]"
 echo "    --with-manlinks           Manual pages links for functions [no]"
 echo "    --with-ctags              Automatically generate tag files [no]"
 echo "    --with-docs               Printable docs (-me/tbl/eqn/pic/refer) [no]"
+echo "    --includes                Preprocess headers (yes|no|link) [yes]"
 echo "    --with-libtool            Specify path to libtool [use bundled]"
 echo "    --with-cygwin             Add cygwin dependencies under cygwin [no]"
 echo "    --enable-nls              Native Language Support [no]"
@@ -215,12 +238,18 @@ MACHINE=`uname -m 2>/dev/null` || MACHINE=unknown
 OSRELEASE=`uname -r 2>/dev/null` || OSRELEASE=unknown
 SYSTEM=`uname -s 2>/dev/null` || SYSTEM=unknown
 HOST="$SYSTEM-$OSRELEASE-$MACHINE"
-echo "Host: $HOST"
 
 echo "# File generated by configure script (BSDbuild 2.4)." > Makefile.config
+echo "# Host: ${HOST}" >> Makefile.config
+echo "" >> Makefile.config
+echo "SRCDIR=${SRC}" >> Makefile.config
+echo "BLDDIR=${BLD}" >> Makefile.config
+
+echo "Host: $HOST"
 echo "Machine: $MACHINE" > config.log
 echo "Release: $OSRELEASE" >> config.log
 echo "System: $SYSTEM" >> config.log
+
 for arg
 do
 	echo "Argument: $arg" >> config.log
@@ -239,6 +268,7 @@ if [ $? != 0 ]; then
 	exit 1
 fi
 
+# Process built-in documentation options.
 HAVE_MANDOC="no"
 NROFF=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
@@ -274,10 +304,11 @@ else
 		fi
 	fi
 fi
-
 if [ "${with_docs}" = "no" ]; then
 	echo "NODOC=yes" >> Makefile.config
 fi
+
+# Process debug option.
 if [ "${enable_debug}" = "yes" ]; then
 	echo "LDFLAGS+=-g" >> Makefile.config
 	echo "#ifndef DEBUG" > config/debug.h
@@ -287,6 +318,7 @@ else
 	echo "#undef DEBUG" > config/debug.h
 fi
 
+# Process NLS options.
 if [ "${enable_nls}" = "yes" ]; then
 	ENABLE_NLS="yes"
 	echo "#ifndef ENABLE_NLS" > config/enable_nls.h
@@ -311,6 +343,7 @@ fi
 echo "ENABLE_NLS=${ENABLE_NLS}" >> Makefile.config
 echo "HAVE_GETTEXT=${HAVE_GETTEXT}" >> Makefile.config
 
+# Process ctags option.
 CTAGS=""
 if [ "${with_ctags}" = "yes" ]; then
 	for path in `echo $PATH | sed 's/:/ /g'`; do
@@ -328,10 +361,14 @@ if [ "${with_ctags}" = "yes" ]; then
 fi
 echo "CTAGS=${CTAGS}" >> Makefile.config
 
+# Default to bundled libtool.
 LIBTOOL_BUNDLED="yes"
 LIBTOOL=\${TOP}/mk/libtool/libtool
 echo "LIBTOOL=${LIBTOOL}" >> Makefile.config
 
+#
+# Process the installation paths.
+#
 echo "PREFIX?=${PREFIX}" >> Makefile.config
 echo "#ifndef PREFIX" > config/prefix.h
 echo "#define PREFIX \"${PREFIX}\"" >> config/prefix.h
@@ -407,7 +444,7 @@ echo "#ifndef SYSCONFDIR" > config/sysconfdir.h
 echo "#define SYSCONFDIR \"${SYSCONFDIR}\"" >> config/sysconfdir.h
 echo "#endif /* SYSCONFDIR */" >> config/sysconfdir.h
 
-VERSION="1.3.3-rc2"
+VERSION="1.3.3-rc3"
 echo "#ifndef VERSION" > config/version.h
 echo "#define VERSION \"$VERSION\"" >> config/version.h
 echo "#endif" >> config/version.h
@@ -3672,12 +3709,6 @@ echo "CFLAGS=$CFLAGS" >>Makefile.config
 echo "mdefs[\"CFLAGS\"] = \"$CFLAGS\"" >>configure.lua
 echo "CXXFLAGS=$CXXFLAGS" >>Makefile.config
 echo "mdefs[\"CXXFLAGS\"] = \"$CXXFLAGS\"" >>configure.lua
-CFLAGS="$CFLAGS -I$SRC"
-CXXFLAGS="$CXXFLAGS -I$SRC"
-echo "CFLAGS=$CFLAGS" >>Makefile.config
-echo "mdefs[\"CFLAGS\"] = \"$CFLAGS\"" >>configure.lua
-echo "CXXFLAGS=$CXXFLAGS" >>Makefile.config
-echo "mdefs[\"CXXFLAGS\"] = \"$CXXFLAGS\"" >>configure.lua
 if [ "${enable_warnings}" = "yes" ]
  then
 CFLAGS="$CFLAGS -Wall"
@@ -6639,12 +6670,53 @@ else
 echo "#undef QUAD_PRECISION" >config/quad_precision.h
 echo "hdefs[\"QUAD_PRECISION\"] = nil" >>configure.lua
 fi
-if [ "${with_proj_generation}" != "yes" ]
- then
-	if [ ! -e "$SRC/agar" ]
- then (cd $SRC && ln -s . agar)
- fi
-	if [ ! -e "agar" ]
- then ln -s . agar
- fi
+#
+# Preprocess headers for visibility and calling convention stuff. Developers
+# can use the unpreprocessed headers directly with --includes=link.
+# 
+if [ ! -e "include" ]; then
+	mkdir "include"
 fi
+if [ "${includes}" = "link" ]; then
+	echo "* Not preprocessing includes"
+	if [ ! -e "include/agar" ]; then
+		if [ "${srcdir}" != "" ]; then
+			ln -s "$SRC" "include/agar"
+		else
+			ln -s "$BLD" "include/agar"
+		fi
+	fi
+else
+	if [ ! -e "include/agar" ]; then
+		$ECHO_N "* Preprocessing includes..."
+		if [ "${srcdir}" != "" ]; then
+			(cd $SRC && perl mk/gen-includes.pl "$BLD/include/agar" 1>>$BLD/config.log 2>&1)
+			cp -fR config include/agar
+		else
+			perl mk/gen-includes.pl "include/agar" 1>config.log 2>&1
+		fi
+		if [ $? != 0 ]; then
+			echo "perl mk/gen-includes.pl failed";
+			exit 1
+		fi
+		echo "done"
+	else
+		echo "* Using existing includes"
+	fi
+fi
+CFLAGS="$CFLAGS -I$BLD/include"
+CXXFLAGS="$CXXFLAGS -I$BLD/include"
+echo "CFLAGS=$CFLAGS" >>Makefile.config
+echo "mdefs[\"CFLAGS\"] = \"$CFLAGS\"" >>configure.lua
+echo "CXXFLAGS=$CXXFLAGS" >>Makefile.config
+echo "mdefs[\"CXXFLAGS\"] = \"$CXXFLAGS\"" >>configure.lua
+CFLAGS="$CFLAGS -I$BLD/include/agar"
+CXXFLAGS="$CXXFLAGS -I$BLD/include/agar"
+echo "CFLAGS=$CFLAGS" >>Makefile.config
+echo "mdefs[\"CFLAGS\"] = \"$CFLAGS\"" >>configure.lua
+echo "CXXFLAGS=$CXXFLAGS" >>Makefile.config
+echo "mdefs[\"CXXFLAGS\"] = \"$CXXFLAGS\"" >>configure.lua
+echo "*"
+echo "* Configuration successful."
+echo "* Use make && make install to build and install Agar."
+echo "*"
