fail if --enable-threads requested explicitely and not found.
git-svn-id: https://dev.csoft.net/agar/trunk@5888 86a84d31-9702-0410-8f1e-a60cab7bd424

diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -163,8 +163,17 @@ else
 fi
 
 # Don't enable thread safety unless requested explicitely.
+# XXX should we enable if pthreads found? what would users expect?
 if [ "${enable_threads}" = "yes" ]; then
-	HDEFINE(THREADS, 1)
+	if [ "${HAVE_PTHREADS}" = "yes" ]; then
+		HDEFINE(THREADS, 1)
+	else
+		echo "*"
+		echo "* --enable-threads was requested, but a POSIX threads"
+		echo "* library was not found."
+		echo "*"
+		exit 1
+	if
 else
 	HUNDEF(THREADS)
 fi
