sync; rien
git-svn-id: https://dev.csoft.net/agar/trunk@1849 86a84d31-9702-0410-8f1e-a60cab7bd424

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -184,6 +184,10 @@ if [ "$CC" = "" ]; then
 			CC="${i}/gcc"
 		fi
 	done
+	if [ "$CC" = "" ]; then
+		echo "Could not find a compiler."
+		exit 1
+	fi
 fi
 
 cat << 'EOT' > .cctest.c
