sync; rien
git-svn-id: https://dev.csoft.net/agar/trunk@2596 86a84d31-9702-0410-8f1e-a60cab7bd424

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -172,6 +172,9 @@ INST_PSDIR="$PREFIX/share/agar/ps"
 echo INST_PSDIR=$INST_PSDIR >> Makefile.config
 echo -n "checking for a usable C compiler..."
 echo -n "checking for a usable C compiler..." >> config.log
+cc_is_gcc=no
+cc_is_gcc3=no
+
 if [ "$CC" = "" ]; then
 	for i in `echo $PATH |sed 's/:/ /g'`; do
 		if [ -x "${i}/cc" ]; then
@@ -182,6 +185,7 @@ if [ "$CC" = "" ]; then
 	done
 	if [ "$CC" = "" ]; then
 		echo "Could not find a C compiler, try setting CC."
+		echo "CC is unset and cc/gcc is not in PATH." >> config.log
 		exit 1
 	fi
 fi
@@ -190,7 +194,7 @@ cat << 'EOT' > .cctest.c
 int
 main(int argc, char *argv[])
 {
-	#ifdef __GNUC__
+#ifdef __GNUC__
 	return (0);
 #else
 	return (1);
@@ -200,20 +204,24 @@ EOT
 
 $CC -o .cctest .cctest.c 2>>config.log
 if [ $? != 0 -o ! -e .cctest ]; then
-    echo "-> failure" >> config.log
     echo "no"
+	echo "The test C program failed to compile or run."
     exit 1
 fi
 
-cc_is_gcc=no
 if ./.cctest; then
     cc_is_gcc=yes
-    echo "ok (gcc)" >> config.log
-    echo "yes"
+	$CC -Wno-system-headers -o .cctest .cctest.c 2>>config.log
+	if [ $? = 0 ]; then
+		cc_is_gcc3=yes
+    	echo "gcc3" >> config.log
+	else
+    	echo "gcc" >> config.log
+	fi
 else
-    echo "yes"
     echo "ok" >> config.log
 fi
+echo "yes"
 
 rm -f .cctest .cctest.c
 echo -n "checking for IEEE 754 floating point..."
@@ -659,7 +667,7 @@ CFLAGS="$CFLAGS -I$SRC"
 echo CFLAGS=$CFLAGS >> Makefile.config
 if [ "${cc_is_gcc}" = "yes" ]
  then
-CFLAGS="$CFLAGS -Wall -Werror -Wmissing-prototypes -Wno-unused -Wno-system-headers"
+CFLAGS="$CFLAGS -Wall -Werror -Wmissing-prototypes -Wno-unused"
 echo CFLAGS=$CFLAGS >> Makefile.config
 fi
 echo -n "checking for SDL (http://www.libsdl.org)..."
