tri:regen
git-svn-id: https://dev.csoft.net/agar/trunk@7710 86a84d31-9702-0410-8f1e-a60cab7bd424

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -223,7 +223,19 @@ for arg
 do
 	echo "Argument: $arg" >> config.log
 done
-mkdir config 1>/dev/null 2>&1
+if [ -e "config" ]; then
+	if [ -f "config" ]; then
+		echo "File ./config is in the way. Please remove it first."
+		exit 1;
+	else
+		rm -fR config;
+	fi
+fi
+mkdir config
+if [ $? != 0 ]; then
+	echo "Could not create ./config/ directory."
+	exit 1
+fi
 
 HAVE_MANDOC="no"
 NROFF=""
