use #include <agar/foo> instead of #include <foo> in sources. this helps to avoid header conflicts and is more consistent with the convention used by public headers.
git-svn-id: https://dev.csoft.net/agar/trunk@9656 86a84d31-9702-0410-8f1e-a60cab7bd424

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -452,7 +452,11 @@ if [ "${host}" != "${build_guessed}" ]; then
 else
 	CROSS_COMPILING="no"
 fi
-echo "BSDBuild 3.0 (host: $host)"
+echo "BSDBuild 3.0 (http://bsdbuild.hypertriton.com)"
+
+echo "#!/bin/sh" > config.status
+echo "# Generated by configure script (BSDBuild 3.0)." >> config.status
+echo "Generated by configure script (BSDBuild 3.0)." > config.log
 
 if [ -e "Makefile.config" ]; then
 	echo "* Overwriting existing Makefile.config"
@@ -465,14 +469,16 @@ echo "CROSS_COMPILING=${CROSS_COMPILING}" >> Makefile.config
 echo "SRCDIR=${SRC}" >> Makefile.config
 echo "BLDDIR=${BLD}" >> Makefile.config
 
-echo "Generated by configure script" > config.log
-echo "BSDBuild Version: 3.0" >> config.log
-echo "Host: $host" >> config.log
-
+echo -n "./configure" >> config.log
+echo -n "./configure" >> config.status
 for arg
 do
-	echo "Argument: $arg" >> config.log
+	echo -n " $arg" >> config.log
+	echo -n " $arg" >> config.status
 done
+echo "" >> config.log
+echo "" >> config.status
+
 if [ -e "$BLD/include/agar/config" ]; then
 	echo "* Overwriting $BLD/include/agar/config directory"
 	rm -fR "$BLD/include/agar/config"
@@ -1593,15 +1599,14 @@ echo "hdefs[\"_MK_HAVE_SYS_TYPES_H\"] = nil" >>configure.lua
 fi;
 rm -f conftest.c $testdir/conftest$EXECSUFFIX
 if [ "${_MK_HAVE_SYS_TYPES_H}" = "yes" ]; then
-$ECHO_N "checking for 64-bit types..."
-$ECHO_N "checking for 64-bit types..." >> config.log
+$ECHO_N "checking for int64_t type..."
+$ECHO_N "checking for int64_t type..." >> config.log
 MK_COMPILE_STATUS="OK"
 cat << EOT > conftest.c
 #include <sys/types.h>
 int main(int argc, char *argv[]) {
 	int64_t i64 = 0;
 	u_int64_t u64 = 0;
-
 	return (i64 != 0 || u64 != 0);
 }
 
@@ -1615,19 +1620,66 @@ fi
 if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
 echo "yes"
 echo "yes" >> config.log
+HAVE_INT64_T="yes"
+echo "#ifndef HAVE_INT64_T" > $BLD/include/agar/config/have_int64_t.h
+echo "#define HAVE_INT64_T \"$HAVE_INT64_T\"" >> $BLD/include/agar/config/have_int64_t.h
+echo "#endif" >> $BLD/include/agar/config/have_int64_t.h
+echo "hdefs[\"HAVE_INT64_T\"] = \"$HAVE_INT64_T\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_INT64_T="no"
+echo "#undef HAVE_INT64_T" >$BLD/include/agar/config/have_int64_t.h
+echo "hdefs[\"HAVE_INT64_T\"] = nil" >>configure.lua
+fi;
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+$ECHO_N "checking for __int64 type..."
+$ECHO_N "checking for __int64 type..." >> config.log
+MK_COMPILE_STATUS="OK"
+cat << EOT > conftest.c
+#include <sys/types.h>
+int main(int argc, char *argv[]) {
+	__int64 i64 = 0;
+	return (i64 != 0);
+}
+
+EOT
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	MK_COMPILE_STATUS="FAIL($?)"
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE___INT64="yes"
+echo "#ifndef HAVE___INT64" > $BLD/include/agar/config/have___int64.h
+echo "#define HAVE___INT64 \"$HAVE___INT64\"" >> $BLD/include/agar/config/have___int64.h
+echo "#endif" >> $BLD/include/agar/config/have___int64.h
+echo "hdefs[\"HAVE___INT64\"] = \"$HAVE___INT64\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE___INT64="no"
+echo "#undef HAVE___INT64" >$BLD/include/agar/config/have___int64.h
+echo "hdefs[\"HAVE___INT64\"] = nil" >>configure.lua
+fi;
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE_INT64_T}" = "yes" ]; then
 HAVE_64BIT="yes"
 echo "#ifndef HAVE_64BIT" > $BLD/include/agar/config/have_64bit.h
 echo "#define HAVE_64BIT \"$HAVE_64BIT\"" >> $BLD/include/agar/config/have_64bit.h
 echo "#endif" >> $BLD/include/agar/config/have_64bit.h
 echo "hdefs[\"HAVE_64BIT\"] = \"$HAVE_64BIT\"" >>configure.lua
-else
-echo "no"
-echo "no" >> config.log
-HAVE_64BIT="no"
-echo "#undef HAVE_64BIT" >$BLD/include/agar/config/have_64bit.h
-echo "hdefs[\"HAVE_64BIT\"] = nil" >>configure.lua
 fi;
-rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE___INT64}" = "yes" ]; then
+HAVE_64BIT="yes"
+echo "#ifndef HAVE_64BIT" > $BLD/include/agar/config/have_64bit.h
+echo "#define HAVE_64BIT \"$HAVE_64BIT\"" >> $BLD/include/agar/config/have_64bit.h
+echo "#endif" >> $BLD/include/agar/config/have_64bit.h
+echo "hdefs[\"HAVE_64BIT\"] = \"$HAVE_64BIT\"" >>configure.lua
+fi;
 else
 echo "#undef HAVE_64BIT" >$BLD/include/agar/config/have_64bit.h
 echo "hdefs[\"HAVE_64BIT\"] = nil" >>configure.lua
@@ -4042,11 +4094,6 @@ echo "hdefs[\"HAVE_SDL\"] = nil" >>configure.lua
 fi;
 rm -f conftest.c $testdir/conftest$EXECSUFFIX
 if [ "${HAVE_SDL}" = "yes" ]; then
-case "${host}" in
-*-*-mingw*)
-SDL_LIBS="-lSDL.dll -mwindows"
-;;
-esac
 echo "#ifndef SDL_CFLAGS" > $BLD/include/agar/config/sdl_cflags.h
 echo "#define SDL_CFLAGS \"$SDL_CFLAGS\"" >> $BLD/include/agar/config/sdl_cflags.h
 echo "#endif" >> $BLD/include/agar/config/sdl_cflags.h
@@ -9085,8 +9132,6 @@ else
 fi
 CFLAGS="$CFLAGS -I$BLD/include"
 CXXFLAGS="$CXXFLAGS -I$BLD/include"
-CFLAGS="$CFLAGS -I$BLD/include/agar"
-CXXFLAGS="$CXXFLAGS -I$BLD/include/agar"
 config_script_out="agar-config"
 config_script_cflags="-I${INCLDIR} ${SDL_CFLAGS} ${FREETYPE_CFLAGS} ${FONTCONFIG_CFLAGS} ${OPENGL_CFLAGS} ${X11_CFLAGS} ${GLX_CFLAGS} ${XINERAMA_CFLAGS} ${COCOA_CFLAGS} ${MATH_CFLAGS} ${PNG_CFLAGS} ${PTHREADS_CFLAGS} ${DB4_CFLAGS} ${MYSQL_CFLAGS} ${GETTEXT_CFLAGS} ${DSO_CFLAGS} ${CLOCK_CFLAGS} ${UIM_CFLAGS} ${ICONV_CFLAGS}"
 config_script_libs="-L${LIBDIR} -lag_gui -lag_core ${SDL_LIBS} ${FREETYPE_LIBS} ${FONTCONFIG_LIBS} ${OPENGL_LIBS} ${X11_LIBS} ${XINERAMA_LIBS} ${COCOA_LIBS} ${MATH_LIBS} ${JPEG_LIBS} ${PNG_LIBS} ${PTHREADS_LIBS} ${DB4_LIBS} ${MYSQL_LIBS} ${GETTEXT_LIBS} ${DSO_LIBS} ${CLOCK_LIBS} ${UIM_LIBS} ${ICONV_LIBS}"
@@ -9697,6 +9742,8 @@ echo "HAVE_PTHREAD_MUTEX_RECURSIVE_NP=$HAVE_PTHREAD_MUTEX_RECURSIVE_NP" >>Makefi
 echo "mdefs[\"HAVE_PTHREAD_MUTEX_RECURSIVE_NP\"] = \"$HAVE_PTHREAD_MUTEX_RECURSIVE_NP\"" >>configure.lua
 echo "HAVE_COCOA=$HAVE_COCOA" >>Makefile.config
 echo "mdefs[\"HAVE_COCOA\"] = \"$HAVE_COCOA\"" >>configure.lua
+echo "HAVE_INT64_T=$HAVE_INT64_T" >>Makefile.config
+echo "mdefs[\"HAVE_INT64_T\"] = \"$HAVE_INT64_T\"" >>configure.lua
 echo "MATH_CFLAGS=$MATH_CFLAGS" >>Makefile.config
 echo "mdefs[\"MATH_CFLAGS\"] = \"$MATH_CFLAGS\"" >>configure.lua
 echo "HAVE_UIM=$HAVE_UIM" >>Makefile.config
@@ -9717,8 +9764,6 @@ echo "HAVE_XKB=$HAVE_XKB" >>Makefile.config
 echo "mdefs[\"HAVE_XKB\"] = \"$HAVE_XKB\"" >>configure.lua
 echo "MATH_C99_CFLAGS=$MATH_C99_CFLAGS" >>Makefile.config
 echo "mdefs[\"MATH_C99_CFLAGS\"] = \"$MATH_C99_CFLAGS\"" >>configure.lua
-echo "HAVE_64BIT=$HAVE_64BIT" >>Makefile.config
-echo "mdefs[\"HAVE_64BIT\"] = \"$HAVE_64BIT\"" >>configure.lua
 echo "SSE2_CFLAGS=$SSE2_CFLAGS" >>Makefile.config
 echo "mdefs[\"SSE2_CFLAGS\"] = \"$SSE2_CFLAGS\"" >>configure.lua
 echo "HAVE_WARN_UNUSED_RESULT_ATTRIBUTE=$HAVE_WARN_UNUSED_RESULT_ATTRIBUTE" >>Makefile.config
@@ -9741,10 +9786,10 @@ echo "HAVE_LIBOPENGL32=$HAVE_LIBOPENGL32" >>Makefile.config
 echo "mdefs[\"HAVE_LIBOPENGL32\"] = \"$HAVE_LIBOPENGL32\"" >>configure.lua
 echo "HAVE_XINERAMA=$HAVE_XINERAMA" >>Makefile.config
 echo "mdefs[\"HAVE_XINERAMA\"] = \"$HAVE_XINERAMA\"" >>configure.lua
-echo "FREETYPE_LIBS=$FREETYPE_LIBS" >>Makefile.config
-echo "mdefs[\"FREETYPE_LIBS\"] = \"$FREETYPE_LIBS\"" >>configure.lua
 echo "HAVE_SSE3=$HAVE_SSE3" >>Makefile.config
 echo "mdefs[\"HAVE_SSE3\"] = \"$HAVE_SSE3\"" >>configure.lua
+echo "FREETYPE_LIBS=$FREETYPE_LIBS" >>Makefile.config
+echo "mdefs[\"FREETYPE_LIBS\"] = \"$FREETYPE_LIBS\"" >>configure.lua
 echo "ICONV_LIBS=$ICONV_LIBS" >>Makefile.config
 echo "mdefs[\"ICONV_LIBS\"] = \"$ICONV_LIBS\"" >>configure.lua
 echo "MANDIR=$MANDIR" >>Makefile.config
@@ -9825,6 +9870,8 @@ echo "OPENGL_CFLAGS=$OPENGL_CFLAGS" >>Makefile.config
 echo "mdefs[\"OPENGL_CFLAGS\"] = \"$OPENGL_CFLAGS\"" >>configure.lua
 echo "VERSION=$VERSION" >>Makefile.config
 echo "mdefs[\"VERSION\"] = \"$VERSION\"" >>configure.lua
+echo "HAVE___INT64=$HAVE___INT64" >>Makefile.config
+echo "mdefs[\"HAVE___INT64\"] = \"$HAVE___INT64\"" >>configure.lua
 if [ "${srcdir}" != "" ]; then
 	$ECHO_N "* Source is in ${srcdir}. Generating Makefiles..."
 	${PERL} ${SRC}/mk/mkconcurrent.pl ${SRC}
