regen sans `configure.lua`
git-svn-id: https://dev.csoft.net/agar/trunk@11235 86a84d31-9702-0410-8f1e-a60cab7bd424

diff --git a/tests/agarhello/configure b/tests/agarhello/configure
--- a/tests/agarhello/configure
+++ b/tests/agarhello/configure
@@ -664,7 +664,6 @@ if [ "${with_docs}" = 'no' ]; then
 fi
 if [ "${enable_nls}" = "yes" ]; then
 ENABLE_NLS="yes"
-echo "hdefs[\"ENABLE_NLS\"] = \"$ENABLE_NLS\"" >>configure.lua
 msgfmt=''
 bb_save_IFS=$IFS
 IFS=$PATH_SEPARATOR
@@ -684,11 +683,9 @@ if [ "${msgfmt}" != '' ]; then
 else
 	HAVE_GETTEXT='no'
 fi
-echo "hdefs[\"ENABLE_NLS\"] = \"$ENABLE_NLS\"" >>configure.lua
 else
 ENABLE_NLS="no"
 HAVE_GETTEXT="no"
-echo 'hdefs["ENABLE_NLS"] = nil' >>configure.lua
 fi
 CTAGS=''
 bb_save_IFS=$IFS
@@ -744,63 +741,54 @@ if [ "${PKGCONFIG}" != "" ]; then
 		;;
 	esac
 fi
-echo "hdefs[\"PREFIX\"] = \"$PREFIX\"" >>configure.lua
 if [ "${bindir}" != '' ]; then
 	BINDIR="${bindir}"
 	BINDIR_SPECIFIED='yes'
 else
 	BINDIR="${PREFIX}/bin"
 fi
-echo "hdefs[\"BINDIR\"] = \"$BINDIR\"" >>configure.lua
 if [ "${libdir}" != '' ]; then
 	LIBDIR="${libdir}"
 	LIBDIR_SPECIFIED='yes'
 else
 	LIBDIR="${PREFIX}/lib"
 fi
-echo "hdefs[\"LIBDIR\"] = \"$LIBDIR\"" >>configure.lua
 if [ "${moduledir}" != '' ]; then
 	MODULEDIR="${moduledir}"
 	MODULEDIR_SPECIFIED='yes'
 else
 	MODULEDIR="${PREFIX}/lib"
 fi
-echo "hdefs[\"MODULEDIR\"] = \"$MODULEDIR\"" >>configure.lua
 if [ "${libexecdir}" != '' ]; then
 	LIBEXECDIR="${libexecdir}"
 	LIBEXECDIR_SPECIFIED='yes'
 else
 	LIBEXECDIR="${PREFIX}/libexec"
 fi
-echo "hdefs[\"LIBEXECDIR\"] = \"$LIBEXECDIR\"" >>configure.lua
 if [ "${datadir}" != '' ]; then
 	DATADIR="${datadir}"
 	DATADIR_SPECIFIED='yes'
 else
 	DATADIR="${PREFIX}/share"
 fi
-echo "hdefs[\"DATADIR\"] = \"$DATADIR\"" >>configure.lua
 if [ "${statedir}" != '' ]; then
 	STATEDIR="${statedir}"
 	STATEDIR_SPECIFIED='yes'
 else
 	STATEDIR="${PREFIX}/var"
 fi
-echo "hdefs[\"STATEDIR\"] = \"$STATEDIR\"" >>configure.lua
 if [ "${sysconfdir}" != '' ]; then
 	SYSCONFDIR="${sysconfdir}"
 	SYSCONFDIR_SPECIFIED='yes'
 else
 	SYSCONFDIR="${PREFIX}/etc"
 fi
-echo "hdefs[\"SYSCONFDIR\"] = \"$SYSCONFDIR\"" >>configure.lua
 if [ "${localedir}" != '' ]; then
 	LOCALEDIR="${localedir}"
 	LOCALEDIR_SPECIFIED='yes'
 else
 	LOCALEDIR="${DATADIR}/locale"
 fi
-echo "hdefs[\"LOCALEDIR\"] = \"$LOCALEDIR\"" >>configure.lua
 if [ "${mandir}" != '' ]; then
 	MANDIR="${mandir}"
 	MANDIR_SPECIFIED='yes'
@@ -814,11 +802,8 @@ else
 		;;
 	esac
 fi
-echo "hdefs[\"MANDIR\"] = \"$MANDIR\"" >>configure.lua
 PACKAGE="AgarHello"
-echo "hdefs[\"PACKAGE\"] = \"$PACKAGE\"" >>configure.lua
 VERSION="1.0-beta"
-echo "hdefs[\"VERSION\"] = \"$VERSION\"" >>configure.lua
 $ECHO_N 'checking for a C compiler...'
 $ECHO_N '# checking for a C compiler...' >>config.log
 # BEGIN cc
@@ -963,6 +948,8 @@ else
 	esac
 fi
 
+HAVE_CC_ASM="no"
+
 if [ "${HAVE_CC}" = "yes" ]; then
 	$ECHO_N 'checking whether the C compiler works...'
 	$ECHO_N '# checking whether the C compiler works...' >>config.log
@@ -1001,9 +988,6 @@ EOT
 				echo "yes"
 				echo "yes" >>config.log
 			fi
-echo "hdefs[\"HAVE_EMCC\"] = \"$HAVE_EMCC\"" >>configure.lua
-echo "hdefs[\"HAVE_CC65\"] = \"$HAVE_CC65\"" >>configure.lua
-echo "hdefs[\"EXECSUFFIX\"] = \"$EXECSUFFIX\"" >>configure.lua
 		else
 			echo "yes"
 			echo "yes" >>config.log
@@ -1039,15 +1023,16 @@ if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
 echo 'yes'
 echo '# yes' >>config.log
 HAVE_CC_CLANG=yes
-echo "hdefs[\"HAVE_CC_CLANG\"] = \"$HAVE_CC_CLANG\"" >>configure.lua
 else
 echo 'no'
 echo '# no' >>config.log
 HAVE_CC_CLANG=no
-echo 'hdefs["HAVE_CC_CLANG"] = nil' >>configure.lua
 fi
 if [ "${keep_conftest}" != "yes" ]; then
 rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
+fi
+if [ "${HAVE_CC_CLANG}" = "yes" ]; then
+HAVE_CC_ASM="yes"
 fi
 $ECHO_N 'cc: checking whether compiler is cc65...'
 $ECHO_N '# cc: checking whether compiler is cc65...' >>config.log
@@ -1055,23 +1040,51 @@ if [ "${HAVE_CC65}" = "yes" ]; then
 echo "yes"
 echo "# yes" >>config.log
 CC_COMPILE=""
-echo "hdefs[\"HAVE_CC65\"] = \"$HAVE_CC65\"" >>configure.lua
 else
 echo "no"
 echo "# no" >>config.log
 CC_COMPILE="-c"
-echo 'hdefs["HAVE_CC65"] = nil' >>configure.lua
 fi
 $ECHO_N 'cc: checking whether compiler is emcc...'
 $ECHO_N '# cc: checking whether compiler is emcc...' >>config.log
 if [ "${HAVE_EMCC}" = "yes" ]; then
 echo "yes"
 echo "# yes" >>config.log
-echo "hdefs[\"HAVE_EMCC\"] = \"$HAVE_EMCC\"" >>configure.lua
 else
 echo "no"
 echo "# no" >>config.log
-echo 'hdefs["HAVE_EMCC"] = nil' >>configure.lua
+fi
+$ECHO_N 'cc: checking for compiler warning options...'
+$ECHO_N '# cc: checking for compiler warning options...' >>config.log
+MK_COMPILE_STATUS=OK
+cat << EOT >conftest$$.c
+int main(int argc, char *argv[]) { return (0); }
+EOT
+echo >>config.log
+echo '# C: HAVE_CC_WARNINGS' >>config.log
+echo "cat << EOT >conftest$$.c" >>config.log
+cat conftest$$.c>>config.log
+echo EOT >>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS -Wall -o $testdir/conftest$$ conftest$$.c  1>/dev/null 2>>config.log">>config.log
+$CC $CFLAGS $TEST_CFLAGS -Wall -o $testdir/conftest$$ conftest$$.c  1>/dev/null 2>>config.log
+if [ "$?" != "0" ]; then
+echo "# failed $?" >>config.log
+MK_COMPILE_STATUS="FAIL $?"
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo 'yes'
+echo '# yes' >>config.log
+HAVE_CC_WARNINGS=yes
+else
+echo 'no'
+echo '# no' >>config.log
+HAVE_CC_WARNINGS=no
+fi
+if [ "${keep_conftest}" != "yes" ]; then
+rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
+fi
+if [ "${HAVE_CC_WARNINGS}" = "yes" ]; then
+TEST_CFLAGS="-Wall"
 fi
 $ECHO_N 'cc: checking whether compiler is GCC...'
 $ECHO_N '# cc: checking whether compiler is GCC...' >>config.log
@@ -1097,49 +1110,16 @@ if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
 echo 'yes'
 echo '# yes' >>config.log
 HAVE_CC_GCC=yes
-echo "hdefs[\"HAVE_CC_GCC\"] = \"$HAVE_CC_GCC\"" >>configure.lua
 else
 echo 'no'
 echo '# no' >>config.log
 HAVE_CC_GCC=no
-echo 'hdefs["HAVE_CC_GCC"] = nil' >>configure.lua
 fi
 if [ "${keep_conftest}" != "yes" ]; then
 rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
 fi
-$ECHO_N 'cc: checking for compiler warning options...'
-$ECHO_N '# cc: checking for compiler warning options...' >>config.log
-MK_COMPILE_STATUS=OK
-cat << EOT >conftest$$.c
-int main(int argc, char *argv[]) { return (0); }
-EOT
-echo >>config.log
-echo '# C: HAVE_CC_WARNINGS' >>config.log
-echo "cat << EOT >conftest$$.c" >>config.log
-cat conftest$$.c>>config.log
-echo EOT >>config.log
-echo "$CC $CFLAGS $TEST_CFLAGS -Wall -o $testdir/conftest$$ conftest$$.c  1>/dev/null 2>>config.log">>config.log
-$CC $CFLAGS $TEST_CFLAGS -Wall -o $testdir/conftest$$ conftest$$.c  1>/dev/null 2>>config.log
-if [ "$?" != "0" ]; then
-echo "# failed $?" >>config.log
-MK_COMPILE_STATUS="FAIL $?"
-fi
-if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
-echo 'yes'
-echo '# yes' >>config.log
-HAVE_CC_WARNINGS=yes
-echo "hdefs[\"HAVE_CC_WARNINGS\"] = \"$HAVE_CC_WARNINGS\"" >>configure.lua
-else
-echo 'no'
-echo '# no' >>config.log
-HAVE_CC_WARNINGS=no
-echo 'hdefs["HAVE_CC_WARNINGS"] = nil' >>configure.lua
-fi
-if [ "${keep_conftest}" != "yes" ]; then
-rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
-fi
-if [ "${HAVE_CC_WARNINGS}" = "yes" ]; then
-TEST_CFLAGS="-Wall"
+if [ "${HAVE_CC_GCC}" = "yes" ]; then
+HAVE_CC_ASM="yes"
 fi
 $ECHO_N 'cc: checking for float and double...'
 $ECHO_N '# cc: checking for float and double...' >>config.log
@@ -1171,12 +1151,10 @@ if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
 echo 'yes'
 echo '# yes' >>config.log
 HAVE_FLOAT=yes
-echo "hdefs[\"HAVE_FLOAT\"] = \"$HAVE_FLOAT\"" >>configure.lua
 else
 echo 'no'
 echo '# no' >>config.log
 HAVE_FLOAT=no
-echo 'hdefs["HAVE_FLOAT"] = nil' >>configure.lua
 fi
 if [ "${keep_conftest}" != "yes" ]; then
 rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
@@ -1210,12 +1188,10 @@ if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
 echo 'yes'
 echo '# yes' >>config.log
 HAVE_LONG_DOUBLE=yes
-echo "hdefs[\"HAVE_LONG_DOUBLE\"] = \"$HAVE_LONG_DOUBLE\"" >>configure.lua
 else
 echo 'no'
 echo '# no' >>config.log
 HAVE_LONG_DOUBLE=no
-echo 'hdefs["HAVE_LONG_DOUBLE"] = nil' >>configure.lua
 fi
 if [ "${keep_conftest}" != "yes" ]; then
 rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
@@ -1248,12 +1224,10 @@ if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
 echo 'yes'
 echo '# yes' >>config.log
 HAVE_LONG_LONG=yes
-echo "hdefs[\"HAVE_LONG_LONG\"] = \"$HAVE_LONG_LONG\"" >>configure.lua
 else
 echo 'no'
 echo '# no' >>config.log
 HAVE_LONG_LONG=no
-echo 'hdefs["HAVE_LONG_LONG"] = nil' >>configure.lua
 fi
 if [ "${keep_conftest}" != "yes" ]; then
 rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
@@ -1282,12 +1256,10 @@ if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
 echo 'yes'
 echo '# yes' >>config.log
 HAVE_LD_NO_UNDEFINED=yes
-echo "hdefs[\"HAVE_LD_NO_UNDEFINED\"] = \"$HAVE_LD_NO_UNDEFINED\"" >>configure.lua
 else
 echo 'no'
 echo '# no' >>config.log
 HAVE_LD_NO_UNDEFINED=no
-echo 'hdefs["HAVE_LD_NO_UNDEFINED"] = nil' >>configure.lua
 fi
 if [ "${keep_conftest}" != "yes" ]; then
 rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
@@ -1316,12 +1288,10 @@ if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
 echo 'yes'
 echo '# yes' >>config.log
 HAVE_LD_STATIC_LIBGCC=yes
-echo "hdefs[\"HAVE_LD_STATIC_LIBGCC\"] = \"$HAVE_LD_STATIC_LIBGCC\"" >>configure.lua
 else
 echo 'no'
 echo '# no' >>config.log
 HAVE_LD_STATIC_LIBGCC=no
-echo 'hdefs["HAVE_LD_STATIC_LIBGCC"] = nil' >>configure.lua
 fi
 if [ "${keep_conftest}" != "yes" ]; then
 rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
@@ -1336,6 +1306,7 @@ cat << EOT >conftest$$.c
 #include <sys/types.h>
 #include <sys/stat.h>
 #include <windows.h>
+
 int main(int argc, char *argv[]) {
 	struct stat sb;
 	DWORD rv;
@@ -1359,12 +1330,10 @@ if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
 echo 'yes'
 echo '# yes' >>config.log
 HAVE_CYGWIN=yes
-echo "hdefs[\"HAVE_CYGWIN\"] = \"$HAVE_CYGWIN\"" >>configure.lua
 else
 echo 'no'
 echo '# no' >>config.log
 HAVE_CYGWIN=no
-echo 'hdefs["HAVE_CYGWIN"] = nil' >>configure.lua
 fi
 if [ "${keep_conftest}" != "yes" ]; then
 rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
@@ -1373,31 +1342,21 @@ fi
 *)
 PICFLAGS="-fPIC"
 HAVE_CYGWIN="no"
-echo 'hdefs["HAVE_CYGWIN"] = nil' >>configure.lua
 PROG_GUI_FLAGS=""
 PROG_CLI_FLAGS=""
 ;;
 esac
-echo "hdefs[\"HAVE_CC\"] = \"$HAVE_CC\"" >>configure.lua
 else
 HAVE_CC65="no"
 HAVE_EMCC="no"
 HAVE_CC_WARNINGS="no"
+HAVE_CC_ASM="no"
 PROG_GUI_FLAGS=""
 PROG_CLI_FLAGS=""
 TEST_CFLAGS=""
-echo 'hdefs["HAVE_CC"] = nil' >>configure.lua
-echo 'hdefs["HAVE_CC_WARNINGS"] = nil' >>configure.lua
-echo 'hdefs["HAVE_CC_CLANG"] = nil' >>configure.lua
-echo 'hdefs["HAVE_CC_GCC"] = nil' >>configure.lua
-echo 'hdefs["HAVE_CC65"] = nil' >>configure.lua
-echo 'hdefs["HAVE_EMCC"] = nil' >>configure.lua
-echo 'hdefs["HAVE_FLOAT"] = nil' >>configure.lua
-echo 'hdefs["HAVE_LONG_DOUBLE"] = nil' >>configure.lua
-echo 'hdefs["HAVE_LONG_LONG"] = nil' >>configure.lua
-echo 'hdefs["HAVE_CYGWIN"] = nil' >>configure.lua
-echo 'hdefs["HAVE_LD_NO_UNDEFINED"] = nil' >>configure.lua
-echo 'hdefs["HAVE_LD_STATIC_LIBGCC"] = nil' >>configure.lua
+fi
+if [ "${HAVE_CC_ASM}" = "yes" ]; then
+else
 fi
 # END cc
 if [ "${HAVE_CC}" != "yes" ]; then
@@ -1575,12 +1534,10 @@ if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
 echo 'yes'
 echo '# yes' >>config.log
 HAVE_AGAR=yes
-echo "hdefs[\"HAVE_AGAR\"] = \"$HAVE_AGAR\"" >>configure.lua
 else
 echo 'no'
 echo '# no' >>config.log
 HAVE_AGAR=no
-echo 'hdefs["HAVE_AGAR"] = nil' >>configure.lua
 fi
 if [ "${keep_conftest}" != "yes" ]; then
 rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
@@ -1588,13 +1545,11 @@ fi
 if [ "${HAVE_AGAR}" = "no" ]; then
 AGAR_CFLAGS=""
 AGAR_LIBS=""
-echo 'hdefs["HAVE_AGAR"] = nil' >>configure.lua
 fi
 else
 HAVE_AGAR="no"
 AGAR_CFLAGS=""
 AGAR_LIBS=""
-echo 'hdefs["HAVE_AGAR"] = nil' >>configure.lua
 fi
 # END agar
 if [ "${HAVE_AGAR}" != "yes" ]; then
@@ -1602,8 +1557,8 @@ echo '* '
 echo '# * ' >>config.log
 echo "* $PACKAGE requires Agar (version 1.6.0 or newer)."
 echo "# * $PACKAGE requires Agar (version 1.6.0 or newer)." >>config.log
-echo '* WWW: http://libagar.org'
-echo '# * WWW: http://libagar.org' >>config.log
+echo '* WWW: https://libagar.org'
+echo '# * WWW: https://libagar.org' >>config.log
 echo '* '
 echo '# * ' >>config.log
 echo "***"
@@ -1619,8 +1574,8 @@ echo '* This software requires agar version >= 1.6.0,'
 echo '# * This software requires agar version >= 1.6.0,' >>config.log
 echo '* please update that package and try again.'
 echo '# * please update that package and try again.' >>config.log
-echo '* WWW: http://libagar.org'
-echo '# * WWW: http://libagar.org' >>config.log
+echo '* WWW: https://libagar.org'
+echo '# * WWW: https://libagar.org' >>config.log
 echo '* '
 echo '# * ' >>config.log
 echo "***"
@@ -1635,85 +1590,46 @@ CFLAGS="$CFLAGS -Wall -Werror -Wmissing-prototypes"
 CFLAGS="$CFLAGS -Wno-unused -Wno-nullability-completeness"
 fi
 echo "AGAR_CFLAGS=$AGAR_CFLAGS" >>Makefile.config
-echo "mdefs[\"AGAR_CFLAGS\"] = \"$AGAR_CFLAGS\"" >>configure.lua
 echo "AGAR_LIBS=$AGAR_LIBS" >>Makefile.config
-echo "mdefs[\"AGAR_LIBS\"] = \"$AGAR_LIBS\"" >>configure.lua
 echo "BINDIR=$BINDIR" >>Makefile.config
-echo "mdefs[\"BINDIR\"] = \"$BINDIR\"" >>configure.lua
 echo "CC=$CC" >>Makefile.config
-echo "mdefs[\"CC\"] = \"$CC\"" >>configure.lua
 echo "CC_COMPILE=$CC_COMPILE" >>Makefile.config
-echo "mdefs[\"CC_COMPILE\"] = \"$CC_COMPILE\"" >>configure.lua
 echo "CFLAGS=$CFLAGS" >>Makefile.config
-echo "mdefs[\"CFLAGS\"] = \"$CFLAGS\"" >>configure.lua
 echo "DATADIR=$DATADIR" >>Makefile.config
-echo "mdefs[\"DATADIR\"] = \"$DATADIR\"" >>configure.lua
 echo "ENABLE_NLS=$ENABLE_NLS" >>Makefile.config
-echo "mdefs[\"ENABLE_NLS\"] = \"$ENABLE_NLS\"" >>configure.lua
 echo "EXECSUFFIX=$EXECSUFFIX" >>Makefile.config
-echo "mdefs[\"EXECSUFFIX\"] = \"$EXECSUFFIX\"" >>configure.lua
 echo "HAVE_AGAR=$HAVE_AGAR" >>Makefile.config
-echo "mdefs[\"HAVE_AGAR\"] = \"$HAVE_AGAR\"" >>configure.lua
 echo "HAVE_CC=$HAVE_CC" >>Makefile.config
-echo "mdefs[\"HAVE_CC\"] = \"$HAVE_CC\"" >>configure.lua
 echo "HAVE_CC65=$HAVE_CC65" >>Makefile.config
-echo "mdefs[\"HAVE_CC65\"] = \"$HAVE_CC65\"" >>configure.lua
+echo "HAVE_CC_ASM=$HAVE_CC_ASM" >>Makefile.config
 echo "HAVE_CC_CLANG=$HAVE_CC_CLANG" >>Makefile.config
-echo "mdefs[\"HAVE_CC_CLANG\"] = \"$HAVE_CC_CLANG\"" >>configure.lua
 echo "HAVE_CC_GCC=$HAVE_CC_GCC" >>Makefile.config
-echo "mdefs[\"HAVE_CC_GCC\"] = \"$HAVE_CC_GCC\"" >>configure.lua
 echo "HAVE_CC_WARNINGS=$HAVE_CC_WARNINGS" >>Makefile.config
-echo "mdefs[\"HAVE_CC_WARNINGS\"] = \"$HAVE_CC_WARNINGS\"" >>configure.lua
 echo "HAVE_CYGWIN=$HAVE_CYGWIN" >>Makefile.config
-echo "mdefs[\"HAVE_CYGWIN\"] = \"$HAVE_CYGWIN\"" >>configure.lua
 echo "HAVE_EMCC=$HAVE_EMCC" >>Makefile.config
-echo "mdefs[\"HAVE_EMCC\"] = \"$HAVE_EMCC\"" >>configure.lua
 echo "HAVE_GETTEXT=$HAVE_GETTEXT" >>Makefile.config
-echo "mdefs[\"HAVE_GETTEXT\"] = \"$HAVE_GETTEXT\"" >>configure.lua
 echo "HAVE_LD_NO_UNDEFINED=$HAVE_LD_NO_UNDEFINED" >>Makefile.config
-echo "mdefs[\"HAVE_LD_NO_UNDEFINED\"] = \"$HAVE_LD_NO_UNDEFINED\"" >>configure.lua
 echo "HAVE_LD_STATIC_LIBGCC=$HAVE_LD_STATIC_LIBGCC" >>Makefile.config
-echo "mdefs[\"HAVE_LD_STATIC_LIBGCC\"] = \"$HAVE_LD_STATIC_LIBGCC\"" >>configure.lua
 echo "LIBDIR=$LIBDIR" >>Makefile.config
-echo "mdefs[\"LIBDIR\"] = \"$LIBDIR\"" >>configure.lua
 echo "LIBEXECDIR=$LIBEXECDIR" >>Makefile.config
-echo "mdefs[\"LIBEXECDIR\"] = \"$LIBEXECDIR\"" >>configure.lua
 echo "LIBTOOLOPTS_SHARED=$LIBTOOLOPTS_SHARED" >>Makefile.config
-echo "mdefs[\"LIBTOOLOPTS_SHARED\"] = \"$LIBTOOLOPTS_SHARED\"" >>configure.lua
 echo "LOCALEDIR=$LOCALEDIR" >>Makefile.config
-echo "mdefs[\"LOCALEDIR\"] = \"$LOCALEDIR\"" >>configure.lua
 echo "MANDIR=$MANDIR" >>Makefile.config
-echo "mdefs[\"MANDIR\"] = \"$MANDIR\"" >>configure.lua
 echo "MODULEDIR=$MODULEDIR" >>Makefile.config
-echo "mdefs[\"MODULEDIR\"] = \"$MODULEDIR\"" >>configure.lua
 echo "PACKAGE=$PACKAGE" >>Makefile.config
-echo "mdefs[\"PACKAGE\"] = \"$PACKAGE\"" >>configure.lua
 echo "PATH_SEPARATOR=$PATH_SEPARATOR" >>Makefile.config
-echo "mdefs[\"PATH_SEPARATOR\"] = \"$PATH_SEPARATOR\"" >>configure.lua
 echo "PICFLAGS=$PICFLAGS" >>Makefile.config
-echo "mdefs[\"PICFLAGS\"] = \"$PICFLAGS\"" >>configure.lua
 echo "PKGCONFIG=$PKGCONFIG" >>Makefile.config
-echo "mdefs[\"PKGCONFIG\"] = \"$PKGCONFIG\"" >>configure.lua
 echo "PKGCONFIG_LIBDIR=$PKGCONFIG_LIBDIR" >>Makefile.config
-echo "mdefs[\"PKGCONFIG_LIBDIR\"] = \"$PKGCONFIG_LIBDIR\"" >>configure.lua
 echo "PROG_BUNDLE=$PROG_BUNDLE" >>Makefile.config
-echo "mdefs[\"PROG_BUNDLE\"] = \"$PROG_BUNDLE\"" >>configure.lua
 echo "PROG_CLI_FLAGS=$PROG_CLI_FLAGS" >>Makefile.config
-echo "mdefs[\"PROG_CLI_FLAGS\"] = \"$PROG_CLI_FLAGS\"" >>configure.lua
 echo "PROG_GUI_FLAGS=$PROG_GUI_FLAGS" >>Makefile.config
-echo "mdefs[\"PROG_GUI_FLAGS\"] = \"$PROG_GUI_FLAGS\"" >>configure.lua
 echo "PROG_PREFIX=$PROG_PREFIX" >>Makefile.config
-echo "mdefs[\"PROG_PREFIX\"] = \"$PROG_PREFIX\"" >>configure.lua
 echo "PROG_SUFFIX=$PROG_SUFFIX" >>Makefile.config
-echo "mdefs[\"PROG_SUFFIX\"] = \"$PROG_SUFFIX\"" >>configure.lua
 echo "PROG_TRANSFORM=$PROG_TRANSFORM" >>Makefile.config
-echo "mdefs[\"PROG_TRANSFORM\"] = \"$PROG_TRANSFORM\"" >>configure.lua
 echo "STATEDIR=$STATEDIR" >>Makefile.config
-echo "mdefs[\"STATEDIR\"] = \"$STATEDIR\"" >>configure.lua
 echo "SYSCONFDIR=$SYSCONFDIR" >>Makefile.config
-echo "mdefs[\"SYSCONFDIR\"] = \"$SYSCONFDIR\"" >>configure.lua
 echo "VERSION=$VERSION" >>Makefile.config
-echo "mdefs[\"VERSION\"] = \"$VERSION\"" >>configure.lua
 if [ "${srcdir}" != '' ]; then
 	$ECHO_N "preparing build environment (source in ${srcdir})..."
 	${PERL} ${SRC}/mk/mkconcurrent.pl ${SRC}
