tri:regen

diff --git a/trunk/agarrcsd/configure b/trunk/agarrcsd/configure
--- a/trunk/agarrcsd/configure
+++ b/trunk/agarrcsd/configure
@@ -115,6 +115,9 @@ do
 	--cache=*)
 	    cache=$optarg
 	    ;;
+	--includes=*)
+	    includes=$optarg
+	    ;;
 	*)
 	    echo "invalid argument: $arg"
 	    echo "try ./configure --help"
@@ -150,6 +153,7 @@ if [ "${srcdir}" != "" ]; then
 else
 	SRC=`pwd`
 fi
+BLD=`pwd`
 
 if [ "${testdir}" != "" ]; then
 	echo "Configure tests will be executed in ${testdir}"
@@ -160,6 +164,24 @@ if [ "${testdir}" != "" ]; then
 else
 	testdir="."
 fi
+
+if [ "${includes}" = "" ]; then
+	includes="yes"
+fi
+if [ "${includes}" = "link" ]; then
+	if [ "${with_proj_generation}" ]; then
+		echo "Cannot use --includes=link with --with-proj-generation!"
+		exit 1
+	fi
+elif [ "${includes}" = "yes" ]; then
+	noop=1
+elif [ "${includes}" = "no" ]; then
+	noop=1
+else
+	echo "Usage: --includes [yes|no|link]"
+	exit 1
+fi
+
 if [ "${help}" = "yes" ]; then
 echo "Usage: ./configure [args]"
 echo "    --prefix                  Installation prefix [/usr/local]"
@@ -177,6 +199,7 @@ echo "    --with-manpages           Manual pages (-mdoc) [yes]"
 echo "    --with-manlinks           Manual pages links for functions [no]"
 echo "    --with-ctags              Automatically generate tag files [no]"
 echo "    --with-docs               Printable docs (-me/tbl/eqn/pic/refer) [no]"
+echo "    --includes                Preprocess headers (yes|no|link) [yes]"
 echo "    --with-libtool            Specify path to libtool [use bundled]"
 echo "    --with-cygwin             Add cygwin dependencies under cygwin [no]"
 echo "    --enable-nls              Native Language Support [no]"
@@ -190,12 +213,18 @@ MACHINE=`uname -m 2>/dev/null` || MACHINE=unknown
 OSRELEASE=`uname -r 2>/dev/null` || OSRELEASE=unknown
 SYSTEM=`uname -s 2>/dev/null` || SYSTEM=unknown
 HOST="$SYSTEM-$OSRELEASE-$MACHINE"
-echo "Host: $HOST"
 
 echo "# File generated by configure script (BSDbuild 2.4)." > Makefile.config
+echo "# Host: ${HOST}" >> Makefile.config
+echo "" >> Makefile.config
+echo "SRCDIR=${SRC}" >> Makefile.config
+echo "BLDDIR=${BLD}" >> Makefile.config
+
+echo "Host: $HOST"
 echo "Machine: $MACHINE" > config.log
 echo "Release: $OSRELEASE" >> config.log
 echo "System: $SYSTEM" >> config.log
+
 for arg
 do
 	echo "Argument: $arg" >> config.log
@@ -214,6 +243,7 @@ if [ $? != 0 ]; then
 	exit 1
 fi
 
+# Process built-in documentation options.
 HAVE_MANDOC="no"
 NROFF=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
@@ -249,10 +279,11 @@ else
 		fi
 	fi
 fi
-
 if [ "${with_docs}" = "no" ]; then
 	echo "NODOC=yes" >> Makefile.config
 fi
+
+# Process debug option.
 if [ "${enable_debug}" = "yes" ]; then
 	echo "LDFLAGS+=-g" >> Makefile.config
 	echo "#ifndef DEBUG" > config/debug.h
@@ -262,6 +293,7 @@ else
 	echo "#undef DEBUG" > config/debug.h
 fi
 
+# Process NLS options.
 if [ "${enable_nls}" = "yes" ]; then
 	ENABLE_NLS="yes"
 	echo "#ifndef ENABLE_NLS" > config/enable_nls.h
@@ -286,6 +318,7 @@ fi
 echo "ENABLE_NLS=${ENABLE_NLS}" >> Makefile.config
 echo "HAVE_GETTEXT=${HAVE_GETTEXT}" >> Makefile.config
 
+# Process ctags option.
 CTAGS=""
 if [ "${with_ctags}" = "yes" ]; then
 	for path in `echo $PATH | sed 's/:/ /g'`; do
@@ -303,10 +336,14 @@ if [ "${with_ctags}" = "yes" ]; then
 fi
 echo "CTAGS=${CTAGS}" >> Makefile.config
 
+# Default to bundled libtool.
 LIBTOOL_BUNDLED="yes"
 LIBTOOL=\${TOP}/mk/libtool/libtool
 echo "LIBTOOL=${LIBTOOL}" >> Makefile.config
 
+#
+# Process the installation paths.
+#
 echo "PREFIX?=${PREFIX}" >> Makefile.config
 echo "#ifndef PREFIX" > config/prefix.h
 echo "#define PREFIX \"${PREFIX}\"" >> config/prefix.h
@@ -405,32 +442,52 @@ if [ "$CC" = "" ]; then
 		fi
 	done
 	if [ "$CC" = "" ]; then
-		echo "Could not find a C compiler, try setting CC."
-		echo "CC is unset and cc/gcc is not in PATH." >> config.log
+		echo "Unable to find a C compiler in PATH. Please set your compiler"
+		echo "explicitely with the CC environment variable."
+		echo "Unable to find a C compiler in PATH." >> config.log
 		exit 1
 	fi
 fi
 
-cat << 'EOT' > cc-test.c
-int
-main(int argc, char *argv[])
-{
-	return (0);
-}
+cat << 'EOT' > conftest.c
+int main(int argc, char *argv[]) { return (0); }
 EOT
 
-$CC -o cc-test cc-test.c 2>>config.log
+$CC -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
     echo "no"
-	echo "The test C program failed to compile."
-	rm -f cc-test cc-test.c
+	echo "Test C program (conftest.c) failed to compile."
+	echo "Test C program (conftest.c) failed to compile." >> config.log
     exit 1
 fi
+
+EXECSUFFIX=""
+for OUTFILE in conftest.exe conftest conftest.*; do
+	if [ -f $OUTFILE ]; then
+		case $OUTFILE in
+		*.c | *.o | *.obj | *.bb | *.bbg | *.d | *.pdb | *.tds | *.xcoff | *.dSYM | *.xSYM )
+			;;
+		*.* )
+			EXECSUFFIX=`expr "$OUTFILE" : '[^.]*\(\..*\)'`
+			break ;;
+		* )
+			break ;;
+		esac;
+    fi
+done
+if [ "$EXECSUFFIX" != "" ]; then
+	echo "Detected executable suffix: $EXECSUFFIX" >> config.log
+fi
+echo "EXECSUFFIX=$EXECSUFFIX" >> Makefile.config
+echo "#ifndef EXECSUFFIX" > config/execsuffix.h
+echo "#define EXECSUFFIX \"${EXECSUFFIX}\"" >> config/execsuffix.h
+echo "#endif /* EXECSUFFIX */" >> config/execsuffix.h
+
 echo "yes"
-rm -f cc-test cc-test.c
+rm -f conftest.c conftest$EXECSUFFIX
 TEST_CFLAGS=""
-$ECHO_N "checking for compiler warnings..."
-$ECHO_N "checking for compiler warnings..." >> config.log
+$ECHO_N "checking for compiler warning options..."
+$ECHO_N "checking for compiler warning options..." >> config.log
 MK_CACHED="No"
 MK_COMPILE_STATUS="OK"
 if [ "${cache}" != "" ]; then
@@ -475,7 +532,7 @@ if [ "${cache}" != "" ]; then
 	echo "$HAVE_CC_WARNINGS" > ${cache}/ctest-HAVE_CC_WARNINGS
 	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_CC_WARNINGS
 fi
-rm -f $testdir/conftest conftest.c
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
 if [ "${HAVE_CC_WARNINGS}" = "yes" ]; then
 TEST_CFLAGS="-Wall -Werror"
 fi;
@@ -530,7 +587,7 @@ if [ "${cache}" != "" ]; then
 	echo "$HAVE_GCC" > ${cache}/ctest-HAVE_GCC
 	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_GCC
 fi
-rm -f $testdir/conftest conftest.c
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
 $ECHO_N "checking for IEEE754 floating point..."
 $ECHO_N "checking for IEEE754 floating point..." >> config.log
 MK_CACHED="No"
@@ -585,7 +642,7 @@ if [ "${cache}" != "" ]; then
 	echo "$HAVE_IEEE754" > ${cache}/ctest-HAVE_IEEE754
 	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_IEEE754
 fi
-rm -f $testdir/conftest conftest.c
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
 $ECHO_N "checking __bounded__ attribute..."
 $ECHO_N "checking __bounded__ attribute..." >> config.log
 MK_CACHED="No"
@@ -639,7 +696,7 @@ if [ "${cache}" != "" ]; then
 	echo "$HAVE_BOUNDED_ATTRIBUTE" > ${cache}/ctest-HAVE_BOUNDED_ATTRIBUTE
 	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_BOUNDED_ATTRIBUTE
 fi
-rm -f $testdir/conftest conftest.c
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
 $ECHO_N "checking __format__ attribute..."
 $ECHO_N "checking __format__ attribute..." >> config.log
 MK_CACHED="No"
@@ -699,7 +756,7 @@ if [ "${cache}" != "" ]; then
 	echo "$HAVE_FORMAT_ATTRIBUTE" > ${cache}/ctest-HAVE_FORMAT_ATTRIBUTE
 	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_FORMAT_ATTRIBUTE
 fi
-rm -f $testdir/conftest conftest.c
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
 $ECHO_N "checking __nonnull__ attribute..."
 $ECHO_N "checking __nonnull__ attribute..." >> config.log
 MK_CACHED="No"
@@ -752,7 +809,7 @@ if [ "${cache}" != "" ]; then
 	echo "$HAVE_NONNULL_ATTRIBUTE" > ${cache}/ctest-HAVE_NONNULL_ATTRIBUTE
 	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_NONNULL_ATTRIBUTE
 fi
-rm -f $testdir/conftest conftest.c
+rm -f conftest.c $testdir/conftest
 $ECHO_N "checking __aligned__ attribute..."
 $ECHO_N "checking __aligned__ attribute..." >> config.log
 MK_CACHED="No"
@@ -803,7 +860,7 @@ if [ "${cache}" != "" ]; then
 	echo "$HAVE_ALIGNED_ATTRIBUTE" > ${cache}/ctest-HAVE_ALIGNED_ATTRIBUTE
 	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_ALIGNED_ATTRIBUTE
 fi
-rm -f $testdir/conftest conftest.c
+rm -f conftest.c $testdir/conftest
 $ECHO_N "checking __packed__ attribute..."
 $ECHO_N "checking __packed__ attribute..." >> config.log
 MK_CACHED="No"
@@ -854,7 +911,7 @@ if [ "${cache}" != "" ]; then
 	echo "$HAVE_PACKED_ATTRIBUTE" > ${cache}/ctest-HAVE_PACKED_ATTRIBUTE
 	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_PACKED_ATTRIBUTE
 fi
-rm -f $testdir/conftest conftest.c
+rm -f conftest.c $testdir/conftest
 $ECHO_N "checking for long double..."
 $ECHO_N "checking for long double..." >> config.log
 MK_CACHED="No"
@@ -904,7 +961,7 @@ if [ "${cache}" != "" ]; then
 	echo "$HAVE_LONG_DOUBLE" > ${cache}/ctest-HAVE_LONG_DOUBLE
 	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_LONG_DOUBLE
 fi
-rm -f $testdir/conftest conftest.c
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
 $ECHO_N "checking for long long..."
 $ECHO_N "checking for long long..." >> config.log
 MK_CACHED="No"
@@ -955,7 +1012,7 @@ if [ "${cache}" != "" ]; then
 	echo "$HAVE_LONG_LONG" > ${cache}/ctest-HAVE_LONG_LONG
 	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_LONG_LONG
 fi
-rm -f $testdir/conftest conftest.c
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
 $ECHO_N "checking for cygwin environment..."
 $ECHO_N "checking for cygwin environment..." >> config.log
 MK_CACHED="No"
@@ -1013,11 +1070,14 @@ if [ "${cache}" != "" ]; then
 	echo "$HAVE_CYGWIN" > ${cache}/ctest-HAVE_CYGWIN
 	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_CYGWIN
 fi
-rm -f $testdir/conftest conftest.c
+rm -f conftest.c $testdir/conftest
 if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
 	if [ "${with_cygwin}" != "yes" ]; then
+		echo "* Disabling cygwin compatibility layer"
 		CFLAGS="$CFLAGS -mno-cygwin"
 		echo "CFLAGS=$CFLAGS" >> Makefile.config
+	else
+		echo "* Using cygwin compatibility layer"
 	fi
 fi
 $ECHO_N "checking for Agar (http://libagar.org/)..."
@@ -1181,7 +1241,7 @@ if [ "${cache}" != "" ]; then
 	echo "$HAVE_AGAR" > ${cache}/ctest-HAVE_AGAR
 	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_AGAR
 fi
-rm -f $testdir/conftest conftest.c
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
 $ECHO_N "checking for ag_core..."
 $ECHO_N "checking for ag_core..." >> config.log
 MK_EXEC_FOUND="No"
@@ -1320,7 +1380,7 @@ if [ "${cache}" != "" ]; then
 	echo "$HAVE_AGAR_NETWORK" > ${cache}/ctest-HAVE_AGAR_NETWORK
 	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_AGAR_NETWORK
 fi
-rm -f $testdir/conftest conftest.c
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
 else
 echo "no"
 echo "no" >> config.log
@@ -1549,7 +1609,7 @@ if [ "${cache}" != "" ]; then
 	echo "$HAVE_AGAR_DEV" > ${cache}/ctest-HAVE_AGAR_DEV
 	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_AGAR_DEV
 fi
-rm -f $testdir/conftest conftest.c
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
 if [ "${HAVE_AGAR_DEV}" != "" ]; then
 echo "AGAR_DEV_CFLAGS=$AGAR_DEV_CFLAGS" >>Makefile.config
 echo "mdefs[\"AGAR_DEV_CFLAGS\"] = \"$AGAR_DEV_CFLAGS\"" >>configure.lua
@@ -1605,3 +1665,7 @@ CFLAGS="$CFLAGS -Wno-unused"
 echo "CFLAGS=$CFLAGS" >>Makefile.config
 echo "mdefs[\"CFLAGS\"] = \"$CFLAGS\"" >>configure.lua
 fi
+echo "*"
+echo "* Configuration successful."
+echo "* Use make && make install to build and install agarrcsd."
+echo "*"
