SDL now optional

diff --git a/trunk/configure.in b/trunk/configure.in
--- a/trunk/configure.in
+++ b/trunk/configure.in
@@ -17,9 +17,9 @@ REGISTER("--enable-legacy",	"Deprecated interfaces [yes]")
 REGISTER("--enable-network",	"CORE: Network support [check]")
 REGISTER("--with-db4",		"CORE: Berkeley DB support [check]")
 
-REGISTER("--with-sdl",		"GUI: SDL rendering support [check]")
 REGISTER("--with-gl",		"GUI: OpenGL rendering support [check]")
-REGISTER("--enable-<depth>bpp", "GUI: Framebuffer depths (8|16|24|32) [all]")
+REGISTER("--with-glx",		"GUI: GL rendering via GLX [check]")
+REGISTER("--with-sdl",		"GUI: SDL rendering support [check]")
 REGISTER("--with-jpeg",		"GUI: JPEG screenshot support [check]")
 REGISTER("--with-freetype",	"GUI: Enable FreeType support [check]")
 
@@ -127,16 +127,88 @@ if [ "${enable_gui}" != "no" ]; then
 	HDEFINE(ENABLE_GUI, "yes")
 	MDEFINE(SUBDIR_gui, "gui agar-config")
 
-	# SDL is currently required for the event system.
-	CHECK(sdl, 1.2.0)
-	if [ "${HAVE_SDL}" != "yes" ]; then
-		echo "*"
-		echo "* Agar-GUI requires the SDL library. You can download it "
-		echo "* from: http://www.libsdl.org/"
-		echo "*"
-		exit 1
+	# Enable SDL support if the SDL library is found.
+	if [ "${with_sdl}" != "no" ]; then
+		CHECK(sdl, 1.2.0)
+		if [ "${HAVE_SDL}" != "yes" ]; then
+			if [ "${with_sdl}" = "yes" ]; then
+				echo "*"
+				echo "* --with-sdl was requested, but the SDL "
+				echo "* library was not found."
+				echo "*"
+				exit 1
+			else
+				HUNDEF(HAVE_SDL)
+			fi
+		fi
+	else
+		HUNDEF(HAVE_SDL)
+		MDEFINE(SDL_CFLAGS, "")
+		MDEFINE(SDL_LIBS, "")
 	fi
 
+	# Enable OpenGL support if an OpenGL library is found.
+	if [ "${with_gl}" != "no" ]; then
+		CHECK(opengl)
+		if [ "${HAVE_OPENGL}" = "yes" ]; then
+			MDEFINE(SDL_CFLAGS, "$SDL_CFLAGS $OPENGL_CFLAGS")
+		else
+			if [ "${with_gl}" = "yes" ]; then
+				echo "*"
+				echo "* --with-gl was requested, but no OpenGL"
+				echo "* library was found."
+				echo "*"
+				exit 1
+			else
+				HUNDEF(HAVE_OPENGL)
+			fi
+		fi
+	else
+		HUNDEF(HAVE_OPENGL)
+		MDEFINE(OPENGL_CFLAGS, "")
+		MDEFINE(OPENGL_LIBS, "")
+	fi
+	
+	# Enable X Windows support if Xlib is found.
+	if [ "${with_x}" != "no" ]; then
+		CHECK(x11)
+		if [ "${HAVE_X11}" != "yes" ]; then
+			if [ "${with_x}" = "yes" ]; then
+				echo "*"
+				echo "* --with-x was requested, but Xlib "
+				echo "* was not found."
+				echo "*"
+				exit 1
+			else
+				HUNDEF(HAVE_X11)
+			fi
+		fi
+	else
+		HUNDEF(HAVE_X11)
+		MDEFINE(X11_CFLAGS, "")
+		MDEFINE(X11_LIBS, "")
+	fi
+	
+	# Enable GLX support if the GLX library is found.
+	if [ "${with_glx}" != "no" ]; then
+		CHECK(glx, 1.4)
+		if [ "${HAVE_GLX}" != "yes" ]; then
+			if [ "${with_glx}" = "yes" ]; then
+				echo "*"
+				echo "* --with-glx was requested, but no"
+				echo "* compatible GLX library was found."
+				echo "*"
+				exit 1
+			else
+				HUNDEF(HAVE_GLX)
+			fi
+		fi
+	else
+		HUNDEF(HAVE_GLX)
+		MDEFINE(GLX_CFLAGS, "")
+		MDEFINE(GLX_LIBS, "")
+	fi
+	
 	# Enable Freetype support if the Freetype library is found. Otherwise
 	# fall back to the bitmap font engine.
 	if [ "${with_freetype}" != "no" ]; then
@@ -157,40 +229,15 @@ if [ "${enable_gui}" != "no" ]; then
 		MDEFINE(FREETYPE_CFLAGS, "")
 		MDEFINE(FREETYPE_LIBS, "")
 	fi
-
-	# Enable OpenGL support if an OpenGL library is found.
-	if [ "${with_gl}" != "no" ]; then
-		CHECK(opengl)
-		if [ "${HAVE_OPENGL}" = "yes" ]; then
-			MDEFINE(SDL_CFLAGS, "$SDL_CFLAGS $OPENGL_CFLAGS")
-		else
-			if [ "${with_gl}" = "yes" ]; then
-				echo "*"
-				echo "* --with-gl was requested, but no OpenGL"
-				echo "* library was found. Try running the"
-				echo "* configure script again without this"
-				echo "* option."
-				echo "*"
-				exit 1
-			else
-				HUNDEF(HAVE_OPENGL)
-			fi
-		fi
-	else
-		HUNDEF(HAVE_OPENGL)
-		MDEFINE(OPENGL_CFLAGS, "")
-		MDEFINE(OPENGL_LIBS, "")
-	fi
-
-	# Enable JPEG support if libjpeg is found (only used for screenshots).
+	
+	# Enable JPEG format support if libjpeg is found.
 	if [ "${with_jpeg}" != "no" ]; then
 		CHECK(jpeg)
 		if [ "${HAVE_JPEG}" != "yes" ]; then
 			if [ "${with_jpeg}" = "yes" ]; then
 				echo "*"
 				echo "* --with-jpeg was requested, but libjpeg"
-				echo "* was not found. Try running configure"
-				echo "* again without this option."
+				echo "* was not found."
 				echo "*"
 				exit 1
 			else
@@ -206,12 +253,18 @@ else
 	HUNDEF(ENABLE_GUI)
 	MDEFINE(SUBDIR_gui, "")
 
-	HUNDEF(HAVE_FREETYPE)
-	MDEFINE(FREETYPE_CFLAGS, "")
-	MDEFINE(FREETYPE_LIBS, "")
+	HUNDEF(HAVE_SDL)
+	MDEFINE(SDL_CFLAGS, "")
+	MDEFINE(SDL_LIBS, "")
+	HUNDEF(HAVE_GLX)
+	MDEFINE(GLX_CFLAGS, "")
+	MDEFINE(GLX_LIBS, "")
 	HUNDEF(HAVE_OPENGL)
 	MDEFINE(OPENGL_CFLAGS, "")
 	MDEFINE(OPENGL_LIBS, "")
+	HUNDEF(HAVE_FREETYPE)
+	MDEFINE(FREETYPE_CFLAGS, "")
+	MDEFINE(FREETYPE_LIBS, "")
 	HUNDEF(HAVE_JPEG)
 	MDEFINE(JPEG_CFLAGS, "")
 	MDEFINE(JPEG_LIBS, "")
@@ -227,8 +280,7 @@ if [ "${enable_network}" = "yes" ]; then
 		if [ "${enable_network}" = "yes" ]; then
 			echo "*"
 			echo "* --enable-network was requested, but this system"
-			echo "* does not support getaddrinfo(). Try running the"
-			echo "* configure script again without this option."
+			echo "* does not seem to support getaddrinfo()."
 			echo "*"
 			exit 1
 		else
@@ -247,8 +299,7 @@ if [ "${with_db4}" = "yes" ]; then
 		if [ "${with_db4}" = "yes" ]; then
 			echo "*"
 			echo "* --with-db4 was requested, but Berkeley DB v4"
-			echo "* was not found. Try running configure"
-			echo "* again without this option."
+			echo "* was not found."
 			echo "*"
 			exit 1
 		else
@@ -274,10 +325,8 @@ if [ "${enable_threads}" != "no" ]; then
 			if [ "${enable_threads}" = "yes" ]; then
 				echo "*"
 				echo "* --enable-threads was given, but your"
-				echo "* pthreads library lacks support for"
-				echo "* recursive mutexes. Try running the"
-				echo "* configure script again without this"
-				echo "* option."
+				echo "* pthreads library seems to lack support"
+				echo "* for recursive mutexes."
 				echo "*"
 				exit 1
 			fi
@@ -289,8 +338,7 @@ if [ "${enable_threads}" != "no" ]; then
 		if [ "${enable_threads}" = "yes" ]; then
 			echo "*"
 			echo "* --enable-threads was given, but no pthreads"
-			echo "* library was found on your system. Try running"
-			echo "* the configure script again without this option."
+			echo "* library was found on your system."
 			echo "*"
 			exit 1
 		fi
@@ -319,36 +367,12 @@ HUNDEF(ASTRONOMICAL_UNITS)
 # Enable conversion of historical units.
 HDEFINE(HISTORICAL_UNITS, "yes")
 
-# Support 8/16/24/32bpp video displays by default.
-# Disable unused modes to reduce code size and gain some cycles.
-if [ "${enable_8bpp}" != "no" ]; then
-	HDEFINE(VIEW_8BPP, "yes")
-else
-	HUNDEF(VIEW_8BPP)
-fi
-if [ "${enable_16bpp}" != "no" ]; then
-	HDEFINE(VIEW_16BPP, "yes")
-else
-	HUNDEF(VIEW_16BPP)
-fi
-if [ "${enable_24bpp}" != "no" ]; then
-	HDEFINE(VIEW_24BPP, "yes")
-else
-	HUNDEF(VIEW_24BPP)
-fi
-if [ "${enable_32bpp}" != "no" ]; then
-	HDEFINE(VIEW_32BPP, "yes")
-else
-	HUNDEF(VIEW_32BPP)
-fi
-
 # Enable NLS if requested explicitely.
 if [ "${enable_nls}" = "yes" ]; then
 	CHECK(gettext)
 	if [ "${HAVE_GETTEXT}" != "yes" ]; then
 		echo "*"
-		echo "* --enable-nls was given but gettext was not found. Try"
-		echo "* running configure again without this option."
+		echo "* --enable-nls was given but gettext was not found."
 		echo "*"
 		exit 1
 	fi
