sync; rien

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -938,6 +938,40 @@ else
 
 	echo "no"
 fi
+echo -n "checking for the arc4random() random number generator..."
+echo -n "checking for the arc4random() random number generator..." >> config.log
+cat << EOT > conftest.c
+#include <sys/types.h>
+#include <stdlib.h>
+int
+main(int argc, char *argv[])
+{
+	u_int32_t i;
+
+	i = arc4random();
+	return (0);
+}
+
+EOT
+compile="ok"
+$CC -o conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed: non-zero exit status" >> config.log
+	compile="failed"
+fi
+rm -f conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+	echo "ok" >> config.log
+	echo "#ifndef HAVE_ARC4RANDOM" > config/have_arc4random.h
+echo "#define HAVE_ARC4RANDOM" $HAVE_ARC4RANDOM >> config/have_arc4random.h
+echo "#endif /* HAVE_ARC4RANDOM */" >> config/have_arc4random.h
+
+	echo "yes"
+else
+    echo "#undef HAVE_ARC4RANDOM" > config/have_arc4random.h
+
+	echo "no"
+fi
 CFLAGS="$CFLAGS -I$SRC"
 echo "CFLAGS=$CFLAGS" >> Makefile.config
 echo -n "checking for SDL (http://www.libsdl.org)..."
