sync

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -645,10 +645,9 @@ else
 
 	echo "no"
 fi
-echo -n "checking for BSD types..."
-echo -n "checking for BSD types..." >> config.log
+if [ "${HAVE_SYS_TYPES_H}" = "yes" ]; then
 cat << EOT > conftest.c
-#include <stdio.h>
+#include <sys/types.h>
 int main(int argc, char *argv[]) {
 	u_int foo = 0;
 	u_long bar = 0;
@@ -682,7 +681,7 @@ if [ "${HAVE_BSD_TYPES}" != "yes" ]; then
 echo -n "checking whether _BSD_SOURCE is needed..."
 echo -n "checking whether _BSD_SOURCE is needed..." >> config.log
 cat << EOT > conftest.c
-#include <stdio.h>
+#include <sys/types.h>
 int main(int argc, char *argv[]) {
 	u_int foo = 0;
 	u_long bar = 0;
@@ -725,6 +724,85 @@ fi;
 else
 echo "#undef BSD_SOURCE_NEEDED" > config/bsd_source_needed.h
 echo "#undef BSD_TYPES_NEEDED" > config/bsd_types_needed.h
+fi;
+else
+cat << EOT > conftest.c
+int main(int argc, char *argv[]) {
+	u_int foo = 0;
+	u_long bar = 0;
+	u_char baz = 0;
+	return (foo>0?bar:baz);
+}
+
+EOT
+compile="ok"
+$CC $CFLAGS $TEST_CFLAGS  -o conftest conftest.c  2>>config.log
+if [ $? != 0 ]; then
+	echo "failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+	echo "ok" >> config.log
+	echo "#ifndef HAVE_BSD_TYPES" > config/have_bsd_types.h
+echo "#define HAVE_BSD_TYPES" $HAVE_BSD_TYPES >> config/have_bsd_types.h
+echo "#endif" >> config/have_bsd_types.h
+
+	HAVE_BSD_TYPES=yes
+
+	echo "yes"
+else
+	echo "#undef HAVE_BSD_TYPES" > config/have_bsd_types.h
+
+	echo "no"
+fi
+if [ "${HAVE_BSD_TYPES}" != "yes" ]; then
+echo -n "checking whether _BSD_SOURCE is needed..."
+echo -n "checking whether _BSD_SOURCE is needed..." >> config.log
+cat << EOT > conftest.c
+int main(int argc, char *argv[]) {
+	u_int foo = 0;
+	u_long bar = 0;
+	u_char baz = 0;
+	return (foo>0?bar:baz);
+}
+
+EOT
+compile="ok"
+$CC $CFLAGS $TEST_CFLAGS -D_BSD_SOURCE -o conftest conftest.c  2>>config.log
+if [ $? != 0 ]; then
+	echo "failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+	echo "ok" >> config.log
+	echo "#ifndef BSD_SOURCE_NEEDED" > config/bsd_source_needed.h
+echo "#define BSD_SOURCE_NEEDED" $BSD_SOURCE_NEEDED >> config/bsd_source_needed.h
+echo "#endif" >> config/bsd_source_needed.h
+
+	BSD_SOURCE_NEEDED=yes
+
+	echo "yes"
+else
+	echo "#undef BSD_SOURCE_NEEDED" > config/bsd_source_needed.h
+
+	echo "no"
+fi
+if [ "${BSD_SOURCE_NEEDED}" != "yes" ]; then
+echo "#undef BSD_SOURCE_NEEDED" > config/bsd_source_needed.h
+echo "#ifndef BSD_TYPES_NEEDED" > config/bsd_types_needed.h
+echo "#define BSD_TYPES_NEEDED \"$BSD_TYPES_NEEDED\"" >> config/bsd_types_needed.h
+echo "#endif" >> config/bsd_types_needed.h
+else
+CFLAGS="${CFLAGS} -D_BSD_SOURCE"
+echo "CFLAGS=$CFLAGS" >> Makefile.config
+echo "#undef BSD_TYPES_NEEDED" > config/bsd_types_needed.h
+fi;
+else
+echo "#undef BSD_SOURCE_NEEDED" > config/bsd_source_needed.h
+echo "#undef BSD_TYPES_NEEDED" > config/bsd_types_needed.h
+fi;
 fi;
 echo -n "checking for BSD-style __progname..."
 echo -n "checking for BSD-style __progname..." >> config.log
