import Agar-AU library

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -381,7 +381,7 @@ echo "    --enable-warnings         Suggested compiler warnings [no]"
 echo "    --with-db4[=PREFIX]       Berkeley DB support in Agar-Core [check]"
 echo "    --with-pthreads[=PREFIX]  Specify libpthreads location [check]"
 echo ""
-echo "Options specific to Agar-GUI (ag_gui):"
+echo "Options specific to ag_gui library:"
 echo "    --with-freetype[=PREFIX]  Enable FreeType support [check]"
 echo "    --with-gl[=PREFIX]        OpenGL rendering support [check]"
 echo "    --with-glx[=PREFIX]       GL rendering via GLX [check]"
@@ -391,11 +391,15 @@ echo "    --with-sdl[=PREFIX]       SDL rendering support [check]"
 echo "    --with-x[=PREFIX]         X Windows driver support [check]"
 echo "    --with-wgl                GL rendering via WGL [check]"
 echo ""
-echo "Options specific to Agar-MATH (ag_math):"
+echo "Options specific to ag_math library:"
 echo "    --with-altivec            AltiVec optimizations [check]"
 echo "    --with-sse                SSE[123] optimizations [no]"
 echo "    --with-<mode>-fp          Precision (single|double|quad) [double]"
 echo "    --with-<opt>-inline       Inline ops (sse2|sse3|altivec) [no]"
+echo ""
+echo "Options specific to ag_au library:"
+echo "    --enable-au               Build audio interface library [no]"
+echo "    --with-sndfile[=PREFIX]   Use sndfile library [check]"
 exit 1
 fi;
 if [ "${show_version}" = "yes" ]; then
@@ -8397,6 +8401,243 @@ SUBDIR_dev=""
 echo "SUBDIR_dev=$SUBDIR_dev" >>Makefile.config
 echo "mdefs[\"SUBDIR_dev\"] = \"$SUBDIR_dev\"" >>configure.lua
 fi
+if [ "${enable_au}" = "yes" -o "${enable_audio}" = "yes" ]
+ then
+ENABLE_AU="yes"
+echo "#ifndef ENABLE_AU" > $BLD/include/agar/config/enable_au.h
+echo "#define ENABLE_AU \"$ENABLE_AU\"" >> $BLD/include/agar/config/enable_au.h
+echo "#endif" >> $BLD/include/agar/config/enable_au.h
+echo "hdefs[\"ENABLE_AU\"] = \"$ENABLE_AU\"" >>configure.lua
+SUBDIR_au="au"
+echo "SUBDIR_au=$SUBDIR_au" >>Makefile.config
+echo "mdefs[\"SUBDIR_au\"] = \"$SUBDIR_au\"" >>configure.lua
+$ECHO_N "checking for libsndfile (http://www.mega-nerd.com/libsndfile/)..."
+$ECHO_N "checking for libsndfile (http://www.mega-nerd.com/libsndfile/)..." >> config.log
+if [ "${prefix_sndfile}" != "" ]; then
+	MK_EXEC_PKGPREFIX=`pkg-config --variable=prefix sndfile`
+	if [ "$MK_EXEC_PKGPREFIX" != "${prefix_sndfile}" ]; then
+		echo " "
+		echo "* "
+		echo "* ERROR: According to pkg-config, sndfile is installed in prefix: "
+		echo "* $MK_EXEC_PKGPREFIX, but the prefix (${prefix_sndfile}) was specified."
+		echo "* "
+		echo "* Please re-run ./configure again with the correct sndfile prefix"
+		echo "* (or specify no prefix at all to enable auto-detection)."
+		echo "* "
+		exit 1
+	else
+		SNDFILE_VERSION=`pkg-config sndfile --modversion`
+	fi
+else
+	SNDFILE_VERSION=`pkg-config sndfile --modversion`
+fi
+if [ "${prefix_sndfile}" != "" ]; then
+	MK_EXEC_PKGPREFIX=`pkg-config --variable=prefix sndfile`
+	if [ "$MK_EXEC_PKGPREFIX" != "${prefix_sndfile}" ]; then
+		echo " "
+		echo "* "
+		echo "* ERROR: According to pkg-config, sndfile is installed in prefix: "
+		echo "* $MK_EXEC_PKGPREFIX, but the prefix (${prefix_sndfile}) was specified."
+		echo "* "
+		echo "* Please re-run ./configure again with the correct sndfile prefix"
+		echo "* (or specify no prefix at all to enable auto-detection)."
+		echo "* "
+		exit 1
+	else
+		SNDFILE_CFLAGS=`pkg-config sndfile --cflags`
+	fi
+else
+	SNDFILE_CFLAGS=`pkg-config sndfile --cflags`
+fi
+if [ "${prefix_sndfile}" != "" ]; then
+	MK_EXEC_PKGPREFIX=`pkg-config --variable=prefix sndfile`
+	if [ "$MK_EXEC_PKGPREFIX" != "${prefix_sndfile}" ]; then
+		echo " "
+		echo "* "
+		echo "* ERROR: According to pkg-config, sndfile is installed in prefix: "
+		echo "* $MK_EXEC_PKGPREFIX, but the prefix (${prefix_sndfile}) was specified."
+		echo "* "
+		echo "* Please re-run ./configure again with the correct sndfile prefix"
+		echo "* (or specify no prefix at all to enable auto-detection)."
+		echo "* "
+		exit 1
+	else
+		SNDFILE_LIBS=`pkg-config sndfile --libs`
+	fi
+else
+	SNDFILE_LIBS=`pkg-config sndfile --libs`
+fi
+if [ "${SNDFILE_VERSION}" != "" ]; then
+if [ "${prefix_sndfile}" != "" ]; then
+echo "yes ($SNDFILE_VERSION in ${prefix_sndfile})"
+echo "yes ($SNDFILE_VERSION in ${prefix_sndfile})" >> config.log
+else
+echo "yes ($SNDFILE_VERSION)"
+echo "yes ($SNDFILE_VERSION)" >> config.log
+fi;
+if [ "1.0.21" != "" ]; then
+MK_VERSION_MAJOR=`echo "$SNDFILE_VERSION" |sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\).*/\1/'`;
+MK_VERSION_MINOR=`echo "$SNDFILE_VERSION" |sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\).*/\2/'`;
+MK_VERSION_MICRO=`echo "$SNDFILE_VERSION" |sed 's/\([0-9]*\).\([0-9]*\).\([0-9]*\).*/\3/'`;
+MK_VERSION_OK="no"
+if [ $MK_VERSION_MAJOR -gt 1 ]; then
+	MK_VERSION_OK="yes";
+elif [ $MK_VERSION_MAJOR -eq 1 ]; then
+	if [ "$MK_VERSION_MINOR" = "" ]; then
+		MK_VERSION_OK="yes"
+	else
+		if [ $MK_VERSION_MINOR -gt 0 ]; then
+			MK_VERSION_OK="yes";
+		elif [ $MK_VERSION_MINOR -eq 0 ]; then
+			if [ "$MK_VERSION_MICRO" = "" ]; then
+				MK_VERSION_OK="yes"
+			else
+				if [ $MK_VERSION_MICRO -ge 21 ]; then
+					MK_VERSION_OK="yes"
+				fi
+			fi
+		fi
+	fi
+fi
+if [ "${MK_VERSION_OK}" != "yes" ]; then
+echo "Version 1.0.21 or greater is required (found $SNDFILE_VERSION)"
+exit 1
+fi;
+fi;
+$ECHO_N "checking whether libsndfile works..."
+$ECHO_N "checking whether libsndfile works..." >> config.log
+MK_CACHED="No"
+MK_COMPILE_STATUS="OK"
+if [ "${cache}" != "" ]; then
+	if [ -e "${cache}/ctest-HAVE_SNDFILE" ]; then
+		HAVE_SNDFILE=`cat ${cache}/ctest-HAVE_SNDFILE`
+		MK_COMPILE_STATUS=`cat ${cache}/ctest-status-HAVE_SNDFILE`
+		MK_CACHED="Yes"
+	fi
+fi
+if [ "${MK_CACHED}" = "No" ]; then
+	cat << EOT > conftest.c
+#include <stdio.h>
+#include <sndfile.h>
+
+int main(int argc, char *argv[]) {
+	SNDFILE *sf;
+	SF_INFO sfi;
+
+	sfi.format = 0;
+	sf = sf_open("foo", 0, &sfi);
+	sf_close(sf);
+	return (0);
+}
+
+EOT
+	echo "$CC $CFLAGS $TEST_CFLAGS ${SNDFILE_CFLAGS} -o $testdir/conftest conftest.c ${SNDFILE_LIBS}" >>config.log
+	$CC $CFLAGS $TEST_CFLAGS ${SNDFILE_CFLAGS} -o $testdir/conftest conftest.c ${SNDFILE_LIBS} 2>>config.log
+	if [ $? != 0 ]; then
+		echo "-> failed ($?)" >> config.log
+		MK_COMPILE_STATUS="FAIL($?)"
+	fi
+fi
+if [ "${MK_COMPILE_STATUS}" = "OK" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_SNDFILE="yes"
+echo "HAVE_SNDFILE=$HAVE_SNDFILE" >>Makefile.config
+echo "mdefs[\"HAVE_SNDFILE\"] = \"$HAVE_SNDFILE\"" >>configure.lua
+echo "#ifndef HAVE_SNDFILE" > $BLD/include/agar/config/have_sndfile.h
+echo "#define HAVE_SNDFILE \"$HAVE_SNDFILE\"" >> $BLD/include/agar/config/have_sndfile.h
+echo "#endif" >> $BLD/include/agar/config/have_sndfile.h
+echo "hdefs[\"HAVE_SNDFILE\"] = \"$HAVE_SNDFILE\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_SNDFILE="no"
+echo "HAVE_SNDFILE=$HAVE_SNDFILE" >>Makefile.config
+echo "mdefs[\"HAVE_SNDFILE\"] = \"$HAVE_SNDFILE\"" >>configure.lua
+echo "#undef HAVE_SNDFILE" >$BLD/include/agar/config/have_sndfile.h
+echo "hdefs[\"HAVE_SNDFILE\"] = nil" >>configure.lua
+fi;
+if [ "${cache}" != "" ]; then
+	echo "$HAVE_SNDFILE" > ${cache}/ctest-HAVE_SNDFILE
+	echo $MK_COMPILE_STATUS > ${cache}/ctest-status-HAVE_SNDFILE
+fi
+rm -f conftest.c $testdir/conftest$EXECSUFFIX
+if [ "${HAVE_SNDFILE}" = "yes" ]; then
+echo "SNDFILE_CFLAGS=$SNDFILE_CFLAGS" >>Makefile.config
+echo "mdefs[\"SNDFILE_CFLAGS\"] = \"$SNDFILE_CFLAGS\"" >>configure.lua
+echo "#ifndef SNDFILE_CFLAGS" > $BLD/include/agar/config/sndfile_cflags.h
+echo "#define SNDFILE_CFLAGS \"$SNDFILE_CFLAGS\"" >> $BLD/include/agar/config/sndfile_cflags.h
+echo "#endif" >> $BLD/include/agar/config/sndfile_cflags.h
+echo "hdefs[\"SNDFILE_CFLAGS\"] = \"$SNDFILE_CFLAGS\"" >>configure.lua
+echo "SNDFILE_LIBS=$SNDFILE_LIBS" >>Makefile.config
+echo "mdefs[\"SNDFILE_LIBS\"] = \"$SNDFILE_LIBS\"" >>configure.lua
+echo "#ifndef SNDFILE_LIBS" > $BLD/include/agar/config/sndfile_libs.h
+echo "#define SNDFILE_LIBS \"$SNDFILE_LIBS\"" >> $BLD/include/agar/config/sndfile_libs.h
+echo "#endif" >> $BLD/include/agar/config/sndfile_libs.h
+echo "hdefs[\"SNDFILE_LIBS\"] = \"$SNDFILE_LIBS\"" >>configure.lua
+else
+echo "#undef SNDFILE_CFLAGS" >$BLD/include/agar/config/sndfile_cflags.h
+echo "hdefs[\"SNDFILE_CFLAGS\"] = nil" >>configure.lua
+SNDFILE_CFLAGS=""
+echo "#undef SNDFILE_LIBS" >$BLD/include/agar/config/sndfile_libs.h
+echo "hdefs[\"SNDFILE_LIBS\"] = nil" >>configure.lua
+SNDFILE_LIBS=""
+fi;
+else
+if [ "${prefix_sndfile}" != "" ]; then
+echo "no (not in ${prefix_sndfile})"
+echo "no (not in ${prefix_sndfile})" >> config.log
+else
+echo "no"
+echo "no" >> config.log
+fi;
+echo "#undef HAVE_SNDFILE" >$BLD/include/agar/config/have_sndfile.h
+echo "hdefs[\"HAVE_SNDFILE\"] = nil" >>configure.lua
+fi;
+	if [ "${HAVE_SNDFILE}" != "yes" ]
+ then
+		echo "*"
+		echo "* --enable-audio was requested, but the sndfile library "
+		echo "* was not found. You can specify a non-standard path"
+		echo "* to sndfile using --with-sndfile[=PREFIX]."
+		echo "*"
+		exit 1
+	fi
+	echo "*"
+	echo "* AU: Configuring bundled PortAudio..."
+	echo "*"
+	rm -fR au/portaudio
+	mkdir au/portaudio
+	if [ $? != 0 ]
+ then exit 1
+ fi
+	(cd au/portaudio && env CFLAGS="-O2" CXXFLAGS="-O2" \
+	    sh ${SRC}/au/portaudio/configure --prefix=${PREFIX})
+	if [ $? != 0 ]
+ then
+		echo "*"
+		echo "* Failed to configure PortAudio"
+		echo "*"
+		exit 1
+	fi
+	echo "*"
+	echo "* AU: PortAudio configured successfully"
+	echo "*"
+else
+echo "#undef ENABLE_AU" >$BLD/include/agar/config/enable_au.h
+echo "hdefs[\"ENABLE_AU\"] = nil" >>configure.lua
+echo "#undef HAVE_SNDFILE" >$BLD/include/agar/config/have_sndfile.h
+echo "hdefs[\"HAVE_SNDFILE\"] = nil" >>configure.lua
+SNDFILE_CFLAGS=""
+echo "SNDFILE_CFLAGS=$SNDFILE_CFLAGS" >>Makefile.config
+echo "mdefs[\"SNDFILE_CFLAGS\"] = \"$SNDFILE_CFLAGS\"" >>configure.lua
+SNDFILE_LIBS=""
+echo "SNDFILE_LIBS=$SNDFILE_LIBS" >>Makefile.config
+echo "mdefs[\"SNDFILE_LIBS\"] = \"$SNDFILE_LIBS\"" >>configure.lua
+SUBDIR_au=""
+echo "SUBDIR_au=$SUBDIR_au" >>Makefile.config
+echo "mdefs[\"SUBDIR_au\"] = \"$SUBDIR_au\"" >>configure.lua
+fi
 if [ ! -e "$BLD/include/agar" ]; then
 	mkdir -p "$BLD/include/agar"
 fi
@@ -8853,6 +9094,87 @@ EOT
 config_script_out="agar-vg-config"
 config_script_cflags="-I${INCLDIR} ${GETTEXT_CFLAGS}"
 config_script_libs="-L${LIBDIR} -lag_vg ${GETTEXT_LIBS}"
+# Avoid breakage with existing trees compiled before BSDBuild 2.8.
+if [ -d "$config_script_out" ]; then
+	echo "rm -fR $config_script_out"
+	rm -fR $config_script_out
+fi
+if [ "${SRC}" != "" ]; then
+	if [ -d "${SRC}/$config_script_out" ]; then
+		echo "rm -fR ${SRC}/$config_script_out"
+		rm -fR ${SRC}/$config_script_out
+	fi
+fi
+cat << EOT > $config_script_out
+#!/bin/sh
+# Generated for ${PACKAGE} by BSDBuild 2.8.
+# <http://bsdbuild.hypertriton.com>
+
+prefix="${PREFIX}"
+exec_prefix="${EXEC_PREFIX}"
+exec_prefix_set="no"
+libdir="${LIBDIR}"
+
+usage="\
+Usage: $config_script_out [--prefix[=DIR]] [--exec-prefix[=DIR]] [--version] [--cflags] [--libs]"
+
+if test \$# -eq 0; then
+	echo "\${usage}" 1>&2
+	exit 1
+fi
+
+while test \$# -gt 0; do
+	case "\$1" in
+	-*=*)
+		optarg=\`echo "\$1" | LC_ALL="C" sed 's/[-_a-zA-Z0-9]*=//'\`
+		;;
+	*)
+		optarg=
+		;;
+	esac
+
+	case \$1 in
+	--prefix=*)
+		prefix=\$optarg
+		if test \$exec_prefix_set = no ; then
+			exec_prefix=\$optarg
+		fi
+		;;
+	--prefix)
+		echo "\$prefix"
+		;;
+	--exec-prefix=*)
+		exec_prefix=\$optarg
+		exec_prefix_set=yes
+		;;
+	--exec-prefix)
+		echo "\$exec_prefix"
+		;;
+	--version)
+		echo "${VERSION}"
+		;;
+	--cflags)
+		echo "$config_script_cflags"
+		;;
+	--libs | --static-libs)
+		if test x"\${prefix}" != x"/usr" ; then
+			libdirs="-L/usr/lib64"
+		else
+			libdirs=""
+		fi
+		echo "\$libdirs $config_script_libs"
+		;;
+	*)
+		echo "\${usage}" 1>&2
+		exit 1
+		;;
+	esac
+	shift
+done
+EOT
+config_script_out="agar-au-config"
+config_script_cflags="-I${INCLDIR} ${GETTEXT_CFLAGS} ${SNDFILE_CFLAGS}"
+config_script_libs="-L${LIBDIR} -lag_au -lag_au_pa ${GETTEXT_LIBS} ${SNDFILE_LIBS}"
 # Avoid breakage with existing trees compiled before BSDBuild 2.8.
 if [ -d "$config_script_out" ]; then
 	echo "rm -fR $config_script_out"
