cross-platform interface to run-time link editors.

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -1037,6 +1037,7 @@ $ECHO_N "checking for <unistd.h>..."
 $ECHO_N "checking for <unistd.h>..." >> config.log
 cat << EOT > conftest.c
 #include <unistd.h>
+#include <sys/types.h>
 int main(int argc, char *argv[]) {
 	uid_t uid = 0;
 	pid_t pid = 0;
@@ -1071,8 +1072,8 @@ echo "#undef _MK_HAVE_UNISTD_H" >config/_mk_have_unistd_h.h
 echo "hdefs[\"_MK_HAVE_UNISTD_H\"] = nil" >>configure.lua
 fi;
 rm -f $testdir/conftest conftest.c
-$ECHO_N "checking for <limits.h>..."
-$ECHO_N "checking for <limits.h>..." >> config.log
+$ECHO_N "checking for compatible <limits.h>..."
+$ECHO_N "checking for compatible <limits.h>..." >> config.log
 cat << EOT > conftest.c
 #include <limits.h>
 
@@ -1110,6 +1111,45 @@ echo "_MK_HAVE_LIMITS_H=$_MK_HAVE_LIMITS_H" >>Makefile.config
 echo "mdefs[\"_MK_HAVE_LIMITS_H\"] = \"$_MK_HAVE_LIMITS_H\"" >>configure.lua
 echo "#undef _MK_HAVE_LIMITS_H" >config/_mk_have_limits_h.h
 echo "hdefs[\"_MK_HAVE_LIMITS_H\"] = nil" >>configure.lua
+fi;
+rm -f $testdir/conftest conftest.c
+$ECHO_N "checking for compatible <float.h>..."
+$ECHO_N "checking for compatible <float.h>..." >> config.log
+cat << EOT > conftest.c
+#include <float.h>
+
+int main(int argc, char *argv[]) {
+	float flt = 0.0f;
+	double dbl = 0.0;
+
+	flt += FLT_EPSILON;
+	dbl += DBL_EPSILON;
+	return (0);
+}
+
+EOT
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+if [ "$?" = "0" ]; then
+echo "yes"
+echo "yes" >> config.log
+compile="ok"
+_MK_HAVE_FLOAT_H="yes"
+echo "_MK_HAVE_FLOAT_H=$_MK_HAVE_FLOAT_H" >>Makefile.config
+echo "mdefs[\"_MK_HAVE_FLOAT_H\"] = \"$_MK_HAVE_FLOAT_H\"" >>configure.lua
+echo "#ifndef _MK_HAVE_FLOAT_H" > config/_mk_have_float_h.h
+echo "#define _MK_HAVE_FLOAT_H \"$_MK_HAVE_FLOAT_H\"" >> config/_mk_have_float_h.h
+echo "#endif" >> config/_mk_have_float_h.h
+echo "hdefs[\"_MK_HAVE_FLOAT_H\"] = \"$_MK_HAVE_FLOAT_H\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+compile="failed"
+_MK_HAVE_FLOAT_H="no"
+echo "_MK_HAVE_FLOAT_H=$_MK_HAVE_FLOAT_H" >>Makefile.config
+echo "mdefs[\"_MK_HAVE_FLOAT_H\"] = \"$_MK_HAVE_FLOAT_H\"" >>configure.lua
+echo "#undef _MK_HAVE_FLOAT_H" >config/_mk_have_float_h.h
+echo "hdefs[\"_MK_HAVE_FLOAT_H\"] = nil" >>configure.lua
 fi;
 rm -f $testdir/conftest conftest.c
 $ECHO_N "checking for the __progname variable..."
@@ -2329,6 +2369,377 @@ echo "hdefs[\"_MK_BIG_ENDIAN\"] = \"$_MK_BIG_ENDIAN\"" >>configure.lua
 fi;
 fi;
 fi;
+$ECHO_N "checking for dlopen() interface..."
+$ECHO_N "checking for dlopen() interface..." >> config.log
+DSO_CFLAGS=""
+DSO_LIBS=""
+TEST_CFLAGS_ORIG="${TEST_CFLAGS}"
+TEST_HEADERS="Yes"
+echo > conftest.c
+echo "#include <dlfcn.h>" >> conftest.c
+echo "int main (int argc, char *argv[]) { return (0); }" >> conftest.c
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f $testdir/conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+HAVE_DLFCN_H="yes"
+echo "#ifndef HAVE_DLFCN_H" > config/have_dlfcn_h.h
+echo "#define HAVE_DLFCN_H \"$HAVE_DLFCN_H\"" >> config/have_dlfcn_h.h
+echo "#endif" >> config/have_dlfcn_h.h
+echo "hdefs[\"HAVE_DLFCN_H\"] = \"$HAVE_DLFCN_H\"" >>configure.lua
+if [ "${TEST_HEADERS}" = "Yes" ]; then
+TEST_CFLAGS="${TEST_CFLAGS} -DHAVE_DLFCN_H"
+fi;
+else
+HAVE_DLFCN_H="no"
+echo "#undef HAVE_DLFCN_H" >config/have_dlfcn_h.h
+echo "hdefs[\"HAVE_DLFCN_H\"] = nil" >>configure.lua
+fi;
+cat << EOT > conftest.c
+#ifdef HAVE_DLFCN_H
+#include <dlfcn.h>
+#endif
+
+int
+main(int argc, char *argv[])
+{
+	void *handle;
+	char *error;
+	handle = dlopen("foo.so", 0);
+	error = dlerror();
+	(void)dlsym(handle, "foo");
+	return (0);
+}
+
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f $testdir/conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_DLOPEN="yes"
+echo "#ifndef HAVE_DLOPEN" > config/have_dlopen.h
+echo "#define HAVE_DLOPEN \"$HAVE_DLOPEN\"" >> config/have_dlopen.h
+echo "#endif" >> config/have_dlopen.h
+echo "hdefs[\"HAVE_DLOPEN\"] = \"$HAVE_DLOPEN\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_DLOPEN="no"
+echo "#undef HAVE_DLOPEN" >config/have_dlopen.h
+echo "hdefs[\"HAVE_DLOPEN\"] = nil" >>configure.lua
+fi;
+if [ "${HAVE_DLOPEN}" != "yes" ]; then
+$ECHO_N "checking for dlopen() in -ldl..."
+$ECHO_N "checking for dlopen() in -ldl..." >> config.log
+cat << EOT > conftest.c
+#ifdef HAVE_DLFCN_H
+#include <dlfcn.h>
+#endif
+
+int
+main(int argc, char *argv[])
+{
+	void *handle;
+	char *error;
+	handle = dlopen("foo.so", 0);
+	error = dlerror();
+	(void)dlsym(handle, "foo");
+	return (0);
+}
+
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -ldl -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -ldl -o $testdir/conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f $testdir/conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_DLOPEN="yes"
+echo "HAVE_DLOPEN=$HAVE_DLOPEN" >>Makefile.config
+echo "mdefs[\"HAVE_DLOPEN\"] = \"$HAVE_DLOPEN\"" >>configure.lua
+echo "#ifndef HAVE_DLOPEN" > config/have_dlopen.h
+echo "#define HAVE_DLOPEN \"$HAVE_DLOPEN\"" >> config/have_dlopen.h
+echo "#endif" >> config/have_dlopen.h
+echo "hdefs[\"HAVE_DLOPEN\"] = \"$HAVE_DLOPEN\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_DLOPEN="no"
+echo "HAVE_DLOPEN=$HAVE_DLOPEN" >>Makefile.config
+echo "mdefs[\"HAVE_DLOPEN\"] = \"$HAVE_DLOPEN\"" >>configure.lua
+echo "#undef HAVE_DLOPEN" >config/have_dlopen.h
+echo "hdefs[\"HAVE_DLOPEN\"] = nil" >>configure.lua
+fi;
+if [ "${HAVE_DLOPEN}" = "yes" ]; then
+DSO_CFLAGS=""
+DSO_LIBS="-ldl"
+fi;
+fi;
+TEST_CFLAGS="${TEST_CFLAGS_ORIG}"
+TEST_HEADERS=""
+echo "DSO_CFLAGS=$DSO_CFLAGS" >>Makefile.config
+echo "mdefs[\"DSO_CFLAGS\"] = \"$DSO_CFLAGS\"" >>configure.lua
+echo "DSO_LIBS=$DSO_LIBS" >>Makefile.config
+echo "mdefs[\"DSO_LIBS\"] = \"$DSO_LIBS\"" >>configure.lua
+echo "#ifndef DSO_CFLAGS" > config/dso_cflags.h
+echo "#define DSO_CFLAGS \"$DSO_CFLAGS\"" >> config/dso_cflags.h
+echo "#endif" >> config/dso_cflags.h
+echo "hdefs[\"DSO_CFLAGS\"] = \"$DSO_CFLAGS\"" >>configure.lua
+echo "#ifndef DSO_LIBS" > config/dso_libs.h
+echo "#define DSO_LIBS \"$DSO_LIBS\"" >> config/dso_libs.h
+echo "#endif" >> config/dso_libs.h
+echo "hdefs[\"DSO_LIBS\"] = \"$DSO_LIBS\"" >>configure.lua
+$ECHO_N "checking for dyld interface..."
+$ECHO_N "checking for dyld interface..." >> config.log
+DSO_CFLAGS=""
+DSO_LIBS=""
+TEST_CFLAGS_ORIG="${TEST_CFLAGS}"
+TEST_HEADERS="Yes"
+echo > conftest.c
+echo "#include <mach-o/dyld.h>" >> conftest.c
+echo "int main (int argc, char *argv[]) { return (0); }" >> conftest.c
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f $testdir/conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+HAVE_MACH_O_DYLD_H="yes"
+echo "#ifndef HAVE_MACH_O_DYLD_H" > config/have_mach_o_dyld_h.h
+echo "#define HAVE_MACH_O_DYLD_H \"$HAVE_MACH_O_DYLD_H\"" >> config/have_mach_o_dyld_h.h
+echo "#endif" >> config/have_mach_o_dyld_h.h
+echo "hdefs[\"HAVE_MACH_O_DYLD_H\"] = \"$HAVE_MACH_O_DYLD_H\"" >>configure.lua
+if [ "${TEST_HEADERS}" = "Yes" ]; then
+TEST_CFLAGS="${TEST_CFLAGS} -DHAVE_MACH_O_DYLD_H"
+fi;
+else
+HAVE_MACH_O_DYLD_H="no"
+echo "#undef HAVE_MACH_O_DYLD_H" >config/have_mach_o_dyld_h.h
+echo "hdefs[\"HAVE_MACH_O_DYLD_H\"] = nil" >>configure.lua
+fi;
+cat << EOT > conftest.c
+#ifdef HAVE_MACH_O_DYLD_H
+#include <mach-o/dyld.h>
+#endif
+int
+main(int argc, char *argv[])
+{
+	NSObjectFileImage img;
+	NSObjectFileImageReturnCode rv;
+
+	rv = NSCreateObjectFileImageFromFile("foo", &img);
+	return (rv == NSObjectFileImageSuccess);
+}
+
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f $testdir/conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_DYLD="yes"
+echo "#ifndef HAVE_DYLD" > config/have_dyld.h
+echo "#define HAVE_DYLD \"$HAVE_DYLD\"" >> config/have_dyld.h
+echo "#endif" >> config/have_dyld.h
+echo "hdefs[\"HAVE_DYLD\"] = \"$HAVE_DYLD\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_DYLD="no"
+echo "#undef HAVE_DYLD" >config/have_dyld.h
+echo "hdefs[\"HAVE_DYLD\"] = nil" >>configure.lua
+fi;
+if [ "${HAVE_DYLD}" = "Yes" ]; then
+echo "checking for NSLINKMODULE_OPTION_RETURN_ON_ERROR"
+echo "checking for NSLINKMODULE_OPTION_RETURN_ON_ERROR" >> config.log
+cat << EOT > conftest.c
+#ifdef HAVE_MACH_O_DYLD_H
+#include <mach-o/dyld.h>
+#endif
+int
+main(int argc, char *argv[])
+{
+	NSObjectFileImage img;
+	NSObjectFileImageReturnCode rv;
+	void *handle;
+
+	rv = NSCreateObjectFileImageFromFile("foo", &img);
+	handle = (void *)NSLinkModule(img, "foo",
+	    NSLINKMODULE_OPTION_RETURN_ON_ERROR|
+		NSLINKMODULE_OPTION_NONE);
+	if (handle == NULL) {
+		NSLinkEditErrors errs;
+		int n;
+		const char *f, *s = NULL;
+		NSLinkEditError(&errs, &n, &f, &s);
+	}
+	return (0);
+}
+
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f $testdir/conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_DYLD_RETURN_ON_ERROR="yes"
+echo "#ifndef HAVE_DYLD_RETURN_ON_ERROR" > config/have_dyld_return_on_error.h
+echo "#define HAVE_DYLD_RETURN_ON_ERROR \"$HAVE_DYLD_RETURN_ON_ERROR\"" >> config/have_dyld_return_on_error.h
+echo "#endif" >> config/have_dyld_return_on_error.h
+echo "hdefs[\"HAVE_DYLD_RETURN_ON_ERROR\"] = \"$HAVE_DYLD_RETURN_ON_ERROR\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_DYLD_RETURN_ON_ERROR="no"
+echo "#undef HAVE_DYLD_RETURN_ON_ERROR" >config/have_dyld_return_on_error.h
+echo "hdefs[\"HAVE_DYLD_RETURN_ON_ERROR\"] = nil" >>configure.lua
+fi;
+else
+HAVE_DYLD_RETURN_ON_ERROR="no"
+echo "#undef HAVE_DYLD_RETURN_ON_ERROR" >config/have_dyld_return_on_error.h
+echo "hdefs[\"HAVE_DYLD_RETURN_ON_ERROR\"] = nil" >>configure.lua
+fi;
+TEST_CFLAGS="${TEST_CFLAGS_ORIG}"
+TEST_HEADERS=""
+echo "DSO_CFLAGS=$DSO_CFLAGS" >>Makefile.config
+echo "mdefs[\"DSO_CFLAGS\"] = \"$DSO_CFLAGS\"" >>configure.lua
+echo "DSO_LIBS=$DSO_LIBS" >>Makefile.config
+echo "mdefs[\"DSO_LIBS\"] = \"$DSO_LIBS\"" >>configure.lua
+echo "#ifndef DSO_CFLAGS" > config/dso_cflags.h
+echo "#define DSO_CFLAGS \"$DSO_CFLAGS\"" >> config/dso_cflags.h
+echo "#endif" >> config/dso_cflags.h
+echo "hdefs[\"DSO_CFLAGS\"] = \"$DSO_CFLAGS\"" >>configure.lua
+echo "#ifndef DSO_LIBS" > config/dso_libs.h
+echo "#define DSO_LIBS \"$DSO_LIBS\"" >> config/dso_libs.h
+echo "#endif" >> config/dso_libs.h
+echo "hdefs[\"DSO_LIBS\"] = \"$DSO_LIBS\"" >>configure.lua
+$ECHO_N "checking for shl_load() interface..."
+$ECHO_N "checking for shl_load() interface..." >> config.log
+DSO_CFLAGS=""
+DSO_LIBS=""
+TEST_CFLAGS_ORIG="${TEST_CFLAGS}"
+TEST_HEADERS="Yes"
+echo > conftest.c
+echo "#include <dl.h>" >> conftest.c
+echo "int main (int argc, char *argv[]) { return (0); }" >> conftest.c
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f $testdir/conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+HAVE_DL_H="yes"
+echo "#ifndef HAVE_DL_H" > config/have_dl_h.h
+echo "#define HAVE_DL_H \"$HAVE_DL_H\"" >> config/have_dl_h.h
+echo "#endif" >> config/have_dl_h.h
+echo "hdefs[\"HAVE_DL_H\"] = \"$HAVE_DL_H\"" >>configure.lua
+if [ "${TEST_HEADERS}" = "Yes" ]; then
+TEST_CFLAGS="${TEST_CFLAGS} -DHAVE_DL_H"
+fi;
+else
+HAVE_DL_H="no"
+echo "#undef HAVE_DL_H" >config/have_dl_h.h
+echo "hdefs[\"HAVE_DL_H\"] = nil" >>configure.lua
+fi;
+cat << EOT > conftest.c
+#ifdef HAVE_DL_H
+#include <dl.h>
+#endif
+
+int
+main(int argc, char *argv[])
+{
+	void *handle;
+	void **p;
+
+	handle = shl_load("foo.so", BIND_IMMEDIATE, 0);
+	(void)shl_findsym((shl_t *)&handle, "foo", TYPE_PROCEDURE, p);
+	(void)shl_findsym((shl_t *)&handle, "foo", TYPE_DATA, p);
+	shl_unload((shl_t)handle);
+	return (0);
+}
+
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -ldld -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -ldld -o $testdir/conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f $testdir/conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_SHL_LOAD="yes"
+echo "HAVE_SHL_LOAD=$HAVE_SHL_LOAD" >>Makefile.config
+echo "mdefs[\"HAVE_SHL_LOAD\"] = \"$HAVE_SHL_LOAD\"" >>configure.lua
+echo "#ifndef HAVE_SHL_LOAD" > config/have_shl_load.h
+echo "#define HAVE_SHL_LOAD \"$HAVE_SHL_LOAD\"" >> config/have_shl_load.h
+echo "#endif" >> config/have_shl_load.h
+echo "hdefs[\"HAVE_SHL_LOAD\"] = \"$HAVE_SHL_LOAD\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+HAVE_SHL_LOAD="no"
+echo "HAVE_SHL_LOAD=$HAVE_SHL_LOAD" >>Makefile.config
+echo "mdefs[\"HAVE_SHL_LOAD\"] = \"$HAVE_SHL_LOAD\"" >>configure.lua
+echo "#undef HAVE_SHL_LOAD" >config/have_shl_load.h
+echo "hdefs[\"HAVE_SHL_LOAD\"] = nil" >>configure.lua
+fi;
+if [ "${HAVE_SHL_LOAD}" = "yes" ]; then
+DSO_CFLAGS=""
+DSO_LIBS="-ldld"
+fi;
+TEST_CFLAGS="${TEST_CFLAGS_ORIG}"
+TEST_HEADERS=""
+echo "DSO_CFLAGS=$DSO_CFLAGS" >>Makefile.config
+echo "mdefs[\"DSO_CFLAGS\"] = \"$DSO_CFLAGS\"" >>configure.lua
+echo "DSO_LIBS=$DSO_LIBS" >>Makefile.config
+echo "mdefs[\"DSO_LIBS\"] = \"$DSO_LIBS\"" >>configure.lua
+echo "#ifndef DSO_CFLAGS" > config/dso_cflags.h
+echo "#define DSO_CFLAGS \"$DSO_CFLAGS\"" >> config/dso_cflags.h
+echo "#endif" >> config/dso_cflags.h
+echo "hdefs[\"DSO_CFLAGS\"] = \"$DSO_CFLAGS\"" >>configure.lua
+echo "#ifndef DSO_LIBS" > config/dso_libs.h
+echo "#define DSO_LIBS \"$DSO_LIBS\"" >> config/dso_libs.h
+echo "#endif" >> config/dso_libs.h
+echo "hdefs[\"DSO_LIBS\"] = \"$DSO_LIBS\"" >>configure.lua
 CFLAGS="$CFLAGS -D_AGAR_INTERNAL"
 CXXFLAGS="$CXXFLAGS -D_AGAR_INTERNAL"
 echo "CFLAGS=$CFLAGS" >>Makefile.config
