sync; rien

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -158,6 +158,49 @@ FOBJDIR="$PREFIX/share/cave/fob"
 echo FOBJDIR=$FOBJDIR >> Makefile.config
 INST_MANDIR="$PREFIX/share/agar/man"
 echo INST_MANDIR=$INST_MANDIR >> Makefile.config
+echo -n "checking for a usable make(1)..."
+echo -n "checking for a usable make(1)..." >> config.log
+echo "checking for a usable make(1)..." >> config.log
+if [ "$MAKE" = "" ]; then
+	for i in `echo $PATH |sed 's/:/ /g'`; do
+		if [ -x "${i}/make" ]; then
+			MAKE="${i}/make"
+		elif [ -x "${i}/make" ]; then
+			MAKE="${i}/make"
+		fi
+	done
+fi
+
+cat << 'EOT' > .maketest
+ASSIGN= foo
+ASSIGN?= foo
+ASSIGN+= bar
+
+all: write-test
+
+write-test:
+	@echo > .maketest2
+
+.BEGIN:
+	@echo -n
+
+TOP=	.
+include ${TOP}/.maketest3
+EOT
+
+echo >> .maketest3
+
+echo "$MAKE -f .maketest" >>config.log
+$MAKE -f .maketest 2>>config.log
+if [ $? != 0 -o ! -e .maketest2 ]; then
+    echo "-> failure" >> config.log
+    echo "no"
+    exit 1
+else
+    echo "yes"
+    echo "-> success" >> config.log
+fi
+rm -f .maketest .maketest2 .maketest3
 echo -n "checking for a usable C compiler..."
 echo -n "checking for a usable C compiler..." >> config.log
 echo "checking for a usable C compiler..." >> config.log
@@ -576,7 +619,7 @@ else
 
 	echo "no"
 fi
-CFLAGS="$CFLAGS -g -I$SRC"
+CFLAGS="$CFLAGS -g -I$S"
 echo CFLAGS=$CFLAGS >> Makefile.config
 if [ "${cc_is_gcc}" = "yes" ]
  then
