sync; rien

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -173,9 +173,6 @@ INST_PSDIR="$PREFIX/share/agar/ps"
 echo INST_PSDIR=$INST_PSDIR >> Makefile.config
 echo -n "checking for a usable C compiler..."
 echo -n "checking for a usable C compiler..." >> config.log
-cc_is_gcc=no
-cc_is_gcc3=no
-
 if [ "$CC" = "" ]; then
 	for i in `echo $PATH |sed 's/:/ /g'`; do
 		if [ -x "${i}/cc" ]; then
@@ -191,40 +188,24 @@ if [ "$CC" = "" ]; then
 	fi
 fi
 
-cat << 'EOT' > .cctest.c
+cat << 'EOT' > cc-test.c
 int
 main(int argc, char *argv[])
 {
-#ifdef __GNUC__
 	return (0);
-#else
-	return (1);
-#endif
 }
 EOT
 
-$CC -o .cctest .cctest.c 2>>config.log
-if [ $? != 0 -o ! -e .cctest ]; then
+$CC -o cc-test cc-test.c 2>>config.log
+if [ $? != 0 ]; then
     echo "no"
-	echo "The test C program failed to compile or run."
+	echo "The test C program failed to compile."
+	rm -f cc-test cc-test.c
     exit 1
-fi
-
-if ./.cctest; then
-    cc_is_gcc=yes
-	$CC -Wno-system-headers -o .cctest .cctest.c 2>>config.log
-	if [ $? = 0 ]; then
-		cc_is_gcc3=yes
-    	echo "gcc3" >> config.log
-	else
-    	echo "gcc" >> config.log
-	fi
-else
-    echo "ok" >> config.log
 fi
 echo "yes"
 
-rm -f .cctest .cctest.c
+rm -f cc-test cc-test.c
 echo -n "checking for IEEE 754 floating point..."
 echo -n "checking for IEEE 754 floating point..." >> config.log
 cat << EOT > conftest.c
@@ -666,16 +647,6 @@ else
 fi
 CFLAGS="$CFLAGS -I$SRC"
 echo CFLAGS=$CFLAGS >> Makefile.config
-if [ "${cc_is_gcc}" = "yes" ]
- then
-CFLAGS="$CFLAGS -Wall -Werror -Wmissing-prototypes -Wno-unused"
-echo CFLAGS=$CFLAGS >> Makefile.config
-fi
-if [ "${cc_is_gcc3}" = "yes" ]
- then
-CFLAGS="$CFLAGS -Wno-missing-headers"
-echo CFLAGS=$CFLAGS >> Makefile.config
-fi
 echo -n "checking for SDL (http://www.libsdl.org)..."
 echo -n "checking for SDL (http://www.libsdl.org)..." >> config.log
 sdl_version=""
