sync

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -256,37 +256,6 @@ echo "LOCALEDIR=${LOCALEDIR}" >> Makefile.config
 echo "#ifndef LOCALEDIR" > config/localedir.h
 echo "#define LOCALEDIR \"${LOCALEDIR}\"" >> config/localedir.h
 echo "#endif /* LOCALEDIR */" >> config/localedir.h
-
-echo -n "checking for a cygwin environment..."
-echo -n "checking for a cygwin environment..." >> config.log
-cat << EOT > conftest.c
-#include <sys/types.h>
-#include <sys/stat.h>
-#include <windows.h>
-
-int main(int argc, char *argv[]) {
-	struct stat sb;
-	DWORD rv;
-	rv = GetFileAttributes("foo");
-	stat("foo", &sb);
-	return (0);
-}
-EOT
-$CC -o conftest conftest.c 2>>config.log
-if [ $? != 0 ]; then
-	echo "no"
-	echo "no" >> config.log
-	HAVE_CYGWIN="no"
-	echo "#undef HAVE_CYGWIN" > config/have_cygwin.h
-else
-	echo "yes"
-	echo "yes" >> config.log
-	echo "CFLAGS+=-mno-cygwin" >> Makefile.config
-	HAVE_CYGWIN="no"
-	echo "#ifndef HAVE_CYGWIN" > config/have_cygwin.h
-	echo "#define HAVE_CYGWIN 1" >> config/have_cygwin.h
-	echo "#endif /* HAVE_CYGWIN */" >> config/have_cygwin.h
-fi
 VERSION="\"1.0-beta\""
 echo "#ifndef VERSION" > config/version.h
 echo "#define VERSION" $VERSION >> config/version.h
@@ -546,6 +515,43 @@ else
 
 	echo "no"
 fi
+echo -n "checking for cygwin environment..."
+echo -n "checking for cygwin environment..." >> config.log
+cat << EOT > conftest.c
+#include <sys/types.h>
+#include <sys/stat.h>
+#include <windows.h>
+
+int
+main(int argc, char *argv[]) {
+	struct stat sb;
+	DWORD rv;
+	rv = GetFileAttributes("foo");
+	stat("foo", &sb);
+	return (0);
+}
+
+EOT
+compile="ok"
+$CC -mcygwin -o conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed: non-zero exit status" >> config.log
+	compile="failed"
+fi
+rm -f conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+	echo "ok" >> config.log
+	echo "#ifndef HAVE_CYGWIN" > config/have_cygwin.h
+echo "#define HAVE_CYGWIN" $HAVE_CYGWIN >> config/have_cygwin.h
+echo "#endif /* HAVE_CYGWIN */" >> config/have_cygwin.h
+
+	echo "yes"
+else
+    echo "#undef HAVE_CYGWIN" > config/have_cygwin.h
+
+	echo "no"
+fi
+echo "CFLAGS+=-mno-cygwin" >> Makefile.config
 echo -n "checking for BSD-style __progname..."
 echo -n "checking for BSD-style __progname..." >> config.log
 cat << EOT > conftest.c
