add test code for WGL

diff --git a/trunk/configure.in b/trunk/configure.in
--- a/trunk/configure.in
+++ b/trunk/configure.in
@@ -21,7 +21,8 @@ REGISTER("--with-gl",		"GUI: OpenGL rendering support [check]")
 REGISTER("--with-glx",		"GUI: GL rendering via GLX [check]")
 REGISTER("--with-wgl",		"GUI: GL rendering via WGL [check]")
 REGISTER("--with-sdl",		"GUI: SDL rendering support [check]")
-REGISTER("--with-jpeg",		"GUI: JPEG screenshot support [check]")
+REGISTER("--with-jpeg",		"GUI: Built-in JPEG image support [check]")
+REGISTER("--with-png",		"GUI: Built-in PNG image support [check]")
 REGISTER("--with-freetype",	"GUI: Enable FreeType support [check]")
 
 REGISTER("--with-sse",		"M: SSE[123] optimizations [no]")
@@ -190,38 +191,53 @@ if [ "${enable_gui}" != "no" ]; then
 		MDEFINE(X11_CFLAGS, "")
 		MDEFINE(X11_LIBS, "")
 	fi
-	
-	# Enable GLX support if the GLX library is found.
-	if [ "${with_glx}" != "no" ]; then
-		CHECK(glx, 1.4)
-		if [ "${HAVE_GLX}" != "yes" ]; then
-			if [ "${with_glx}" = "yes" ]; then
-				echo "*"
-				echo "* --with-glx was requested, but no"
-				echo "* compatible GLX library was found."
-				echo "*"
-				exit 1
-			else
-				HUNDEF(HAVE_GLX)
+
+	#
+	# Platform-specific OpenGL APIs
+	#
+	if [ "${HAVE_OPENGL}" = "yes" ]; then
+		# Enable GLX support if the GLX library is found.
+		if [ "${with_glx}" != "no" ]; then
+			CHECK(glx, 1.4)
+			if [ "${HAVE_GLX}" != "yes" ]; then
+				if [ "${with_glx}" = "yes" ]; then
+					echo "*"
+					echo "* --with-glx was requested, but no"
+					echo "* compatible GLX library was found."
+					echo "*"
+					exit 1
+				else
+					HUNDEF(HAVE_GLX)
+				fi
 			fi
+		else
+			HUNDEF(HAVE_GLX)
+			MDEFINE(GLX_CFLAGS, "")
+			MDEFINE(GLX_LIBS, "")
+		fi
+		
+		# Enable WGL support on Windows.
+		if [ "${with_wgl}" != "no" ]; then
+			CHECK(wgl)
+			if [ "${HAVE_WGL}" != "yes" ]; then
+				if [ "${with_wgl}" = "yes" ]; then
+					echo "*"
+					echo "* --with-wgl was requested, but the"
+					echo "* WGL test has failed."
+					echo "*"
+					exit 1
+				else
+					HUNDEF(HAVE_WGL)
+				fi
+			fi
+		else
+			HUNDEF(HAVE_WGL)
 		fi
 	else
+		HUNDEF(HAVE_WGL)
 		HUNDEF(HAVE_GLX)
 		MDEFINE(GLX_CFLAGS, "")
 		MDEFINE(GLX_LIBS, "")
-	fi
-	
-	# Enable WGL support if Windows is found and Opengl will be compiled in
-	if [ "$with_wgl" != "no" ] && [ "${HAVE_OPENGL}" == "yes" ] && echo $OS | grep -Eq '^Windows'; then
-		echo "*"
-		echo "* WGL is used since OpenGL was requested and we're building on a Windows platform"
-		echo "*"
-		
-		HDEFINE(HAVE_WGL, "yes")
-	else
-		HUNDEF(HAVE_WGL)
-		MDEFINE(WGL_CFLAGS, "")
-		MDEFINE(WGL_LIBS, "")
 	fi
 	
 	# Enable Freetype support if the Freetype library is found. Otherwise
@@ -229,6 +245,8 @@ if [ "${enable_gui}" != "no" ]; then
 	if [ "${with_freetype}" != "no" ]; then
 		CHECK(freetype, 7.0.1)
 		if [ "${HAVE_FREETYPE}" != "yes" ]; then
+			echo "*"
+			echo "* The FreeType library was not found, aborting!"
 			echo "*"
 			echo "* Agar needs FreeType to display vector fonts"
 			echo "* (http://www.freetype.org/)."
