sync; rien

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -567,9 +567,60 @@ else
 NONE=1
 fi
 if [ "${freetype_found}" = "yes" ]; then
-echo "ok"
+echo -n "yes..."
 else
-echo "Missing FreeType"
+echo "Cannot find FreeType library"
+exit 1
+fi
+cat << EOT > conftest.c
+#include <stdio.h>
+#include <freetype2/freetype/freetype.h>
+#include <freetype2/freetype/ftoutln.h>
+
+int
+main(int argc, char *argv[])
+{
+	FT_UInt uint;
+	FT_Bitmap bitmap;
+	FT_Face face;
+	FT_Library library;
+	FT_Error error;
+
+	error = FT_Init_FreeType(&library);
+	if (error) {
+		fprintf(stderr, "failed to initialize freetype\n");
+		return (1);
+	}
+	return (0);
+}
+
+EOT
+compile="ok"
+echo "cc -o conftest conftest.c" >> config.log
+cc -o conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed: compiler had non-zero exit status" >> config.log
+	compile="failed"
+fi
+if [ ! -e "conftest" ]; then
+	echo "-> failed: compiler did not produce an executable" >> config.log
+	compile="failed"
+fi
+rm -f conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+	echo "-> success" >> config.log
+	echo "#ifndef HAVE_FREETYPE" >> engine/mcconfig.h
+echo "#define HAVE_FREETYPE" $HAVE_FREETYPE >> engine/mcconfig.h
+echo "#endif /* HAVE_FREETYPE */" >> engine/mcconfig.h
+
+	echo "yes"
+else
+	echo "no"
+fi
+if [ "${HAVE_FREETYPE}" = "yes" ]; then
+echo "works"
+else
+echo "FreeType2 test failed to compile"
 exit 1
 fi
 if [ "${with_x11}" != "no" ]
