- don't fail if pthreads is not found and --disable-threads was not given;   reported by nineye. - make error messages more explicit.

diff --git a/trunk/configure.in b/trunk/configure.in
--- a/trunk/configure.in
+++ b/trunk/configure.in
@@ -102,12 +102,16 @@ if [ "${enable_gui}" != "no" ]; then
 		CHECK(freetype, 7.0.1)
 		if [ "${HAVE_FREETYPE}" != "yes" ]; then
 			echo "*"
-			echo "* Agar needs FreeType to display vector fonts."
-			echo "* If you would like to use a low-quality bitmap "
-			echo "* font engine, pass the --without-freetype flag."
+			echo "* Agar needs FreeType to display vector fonts"
+			echo "* (http://www.freetype.org/)."
+			echo "*"
+			echo "* If you really want to use Agar's built-in low"
+			echo "* quality bitmap font engine, run the configure"
+			echo "* script again using the --without-freetype flag."
 			echo "*"
 			echo "* Note that the bundled bitmap font only includes"
-			echo "* the ASCII range."
+			echo "* the basic US-ASCII characters and is not meant"
+			echo "* to be used except for porting to new platforms."
 			echo "*"
 			exit 1
 		fi
@@ -125,8 +129,10 @@ if [ "${enable_gui}" != "no" ]; then
 		else
 			if [ "${with_gl}" = "yes" ]; then
 				echo "*"
-				echo "* --with-gl was explicitely requested, "
-				echo "* but OpenGL was not found."
+				echo "* --with-gl was requested, but no OpenGL"
+				echo "* library was found. Try running the"
+				echo "* configure script again without this"
+				echo "* option."
 				echo "*"
 				exit 1
 			else
@@ -145,8 +151,9 @@ if [ "${enable_gui}" != "no" ]; then
 		if [ "${HAVE_JPEG}" != "yes" ]; then
 			if [ "${with_jpeg}" = "yes" ]; then
 				echo "*"
-				echo "* --with-jpeg was explicitely requested, "
-				echo "* but libjpeg was not found."
+				echo "* --with-jpeg was requested, but libjpeg"
+				echo "* was not found. Try running configure"
+				echo "* again without this option."
 				echo "*"
 				exit 1
 			else
@@ -173,6 +180,7 @@ else
 fi
 
 # Enable network support if system supports getaddrinfo().
+# XXX Should enable check by default
 if [ "${enable_network}" = "yes" ]; then
 	CHECK(getaddrinfo)
 	if [ "${HAVE_GETADDRINFO}" = "yes" ]; then
@@ -181,7 +189,8 @@ if [ "${enable_network}" = "yes" ]; then
 		if [ "${enable_network}" = "yes" ]; then
 			echo "*"
 			echo "* --enable-network was requested, but this system"
-			echo "* does not support getaddrinfo()."
+			echo "* does not support getaddrinfo(). Try running the"
+			echo "* configure script again without this option."
 			echo "*"
 			exit 1
 		else
@@ -202,7 +211,8 @@ if [ "${enable_server}" = "yes" ]; then
 		if [ "${enable_server}" = "yes" ]; then
 			echo "*"
 			echo "* --enable-server was requested, but this system"
-			echo "* does not support getaddrinfo()."
+			echo "* does not support getaddrinfo(). Try running the"
+			echo "* configure script again without this option."
 			echo "*"
 			exit 1
 		else
@@ -222,22 +232,29 @@ if [ "${enable_threads}" != "no" ]; then
 		if [ "${HAVE_PTHREADS_XOPEN}" = "no" ]; then
 		if [ "${HAVE_PTHREAD_MUTEX_RECURSIVE}" = "no" ]; then
 		if [ "${HAVE_PTHREAD_MUTEX_RECURSIVE_NP}" = "no" ]; then
-			echo "*"
-			echo "* --enable-threads was requested, but your"
-			echo "* pthreads implementation does not support"
-			echo "* recursive mutexes."
-			echo "*"
-			exit 1
+			if [ "${enable_threads}" = "yes" ]; then
+				echo "*"
+				echo "* --enable-threads was given, but your"
+				echo "* pthreads library lacks support for"
+				echo "* recursive mutexes. Try running the"
+				echo "* configure script again without this"
+				echo "* option."
+				echo "*"
+				exit 1
+			fi
 		fi
 		fi
 		fi
 		HDEFINE(THREADS, 1)
 	else
-		echo "*"
-		echo "* --enable-threads was requested, but no POSIX threads"
-		echo "* library was found"
-		echo "*"
-		exit 1
+		if [ "${enable_threads}" = "yes" ]; then
+			echo "*"
+			echo "* --enable-threads was given, but no pthreads"
+			echo "* library was found on your system. Try running"
+			echo "* the configure script again without this option."
+			echo "*"
+			exit 1
+		fi
 	fi
 else
 	HUNDEF(THREADS)
