introduce agar HTTP/1.1 application server interface (needs --enable-web)

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -444,9 +444,11 @@ echo ''
 echo 'Options specific to CORE library:'
 echo '    --enable-debug-core         Expensive AG_Object debugging [no]'
 echo '    --enable-network            Network interface [check]'
+echo '    --enable-web                Web application server [no]'
 echo '    --with-db4[=PREFIX]         AG_Db: Berkeley DB backend [check]'
 echo '    --with-mysql[=PREFIX]       AG_Db: MySQL backend [no]'
 echo '    --with-iconv[=PREFIX]       Character set conversion [check]'
+echo '    --with-z[=PREFIX]           zlib compression library [check]'
 echo ''
 echo 'Options specific to MATH library:'
 echo '    --with-<mode>-fp            Precision (single|double|quad) [double]'
@@ -7092,7 +7094,171 @@ echo 'hdefs["HAVE_WINSOCK1"] = nil' >>configure.lua
 echo '#undef HAVE_WINSOCK2' >$BLD/include/agar/config/have_winsock2.h
 echo 'hdefs["HAVE_WINSOCK2"] = nil' >>configure.lua
 fi
-	
+if [ "${enable_web}" = 'yes' ]
+ then
+$ECHO_N 'checking for zlib...'
+$ECHO_N 'checking for zlib...' >> config.log
+ZLIB_CFLAGS=""
+ZLIB_LIBS=""
+if [ "${prefix_z}" != "" ]; then
+ZLIB_CFLAGS="-I${prefix_z}/include"
+ZLIB_LIBS="-L${prefix_z}/lib -lz"
+else
+if [ -f "/usr/local/include/zlib.h" ]; then
+ZLIB_CFLAGS="-I/usr/local/include"
+ZLIB_LIBS="-L/usr/local/lib -lz"
+fi;
+if [ -f "/usr/include/zlib.h" ]; then
+ZLIB_CFLAGS="-I/usr/include"
+ZLIB_LIBS="-L/usr/lib -lz"
+fi;
+fi;
+if [ "${ZLIB_LIBS}" != "" ]; then
+echo 'ok'
+echo 'ok' >> config.log
+$ECHO_N 'checking whether zlib works...'
+$ECHO_N 'checking whether zlib works...' >> config.log
+MK_COMPILE_STATUS='OK'
+cat << EOT > conftest$$.c
+#include <stdio.h>
+#include <string.h>
+#include <zlib.h>
+
+int main(int argc, char *argv[]) {
+	z_stream strm;
+	strm.zalloc = Z_NULL;
+	strm.zfree = Z_NULL;
+	strm.opaque = Z_NULL;
+	return deflateInit(&strm, 0);
+}
+
+EOT
+echo "$CC $CFLAGS $TEST_CFLAGS ${ZLIB_CFLAGS} -o $testdir/conftest conftest.c ${ZLIB_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${ZLIB_CFLAGS} -o $testdir/conftest$$ conftest$$.c ${ZLIB_LIBS} 2>>config.log
+if [ $? != 0 ]; then
+	echo ": failed, code $?" >> config.log
+	MK_COMPILE_STATUS="FAIL $?"
+fi
+if [ "${MK_COMPILE_STATUS}" = 'OK' ]; then
+echo 'yes'
+echo 'yes' >> config.log
+HAVE_ZLIB='yes'
+echo '#ifndef HAVE_ZLIB' > $BLD/include/agar/config/have_zlib.h
+echo "#define HAVE_ZLIB \"$HAVE_ZLIB\"" >> $BLD/include/agar/config/have_zlib.h
+echo '#endif' >> $BLD/include/agar/config/have_zlib.h
+echo "hdefs[\"HAVE_ZLIB\"] = \"$HAVE_ZLIB\"" >>configure.lua
+else
+echo 'no'
+echo 'no' >> config.log
+HAVE_ZLIB='no'
+echo '#undef HAVE_ZLIB' >$BLD/include/agar/config/have_zlib.h
+echo 'hdefs["HAVE_ZLIB"] = nil' >>configure.lua
+fi;
+rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
+if [ "${HAVE_ZLIB}" = "yes" ]; then
+echo '#ifndef ZLIB_CFLAGS' > $BLD/include/agar/config/zlib_cflags.h
+echo "#define ZLIB_CFLAGS \"$ZLIB_CFLAGS\"" >> $BLD/include/agar/config/zlib_cflags.h
+echo '#endif' >> $BLD/include/agar/config/zlib_cflags.h
+echo "hdefs[\"ZLIB_CFLAGS\"] = \"$ZLIB_CFLAGS\"" >>configure.lua
+echo '#ifndef ZLIB_LIBS' > $BLD/include/agar/config/zlib_libs.h
+echo "#define ZLIB_LIBS \"$ZLIB_LIBS\"" >> $BLD/include/agar/config/zlib_libs.h
+echo '#endif' >> $BLD/include/agar/config/zlib_libs.h
+echo "hdefs[\"ZLIB_LIBS\"] = \"$ZLIB_LIBS\"" >>configure.lua
+else
+echo '#undef ZLIB_CFLAGS' >$BLD/include/agar/config/zlib_cflags.h
+echo 'hdefs["ZLIB_CFLAGS"] = nil' >>configure.lua
+ZLIB_CFLAGS=""
+echo '#undef ZLIB_LIBS' >$BLD/include/agar/config/zlib_libs.h
+echo 'hdefs["ZLIB_LIBS"] = nil' >>configure.lua
+ZLIB_LIBS=""
+fi;
+else
+echo '#undef HAVE_ZLIB' >$BLD/include/agar/config/have_zlib.h
+echo 'hdefs["HAVE_ZLIB"] = nil' >>configure.lua
+echo 'no'
+echo 'no' >> config.log
+fi;
+$ECHO_N 'checking for <sys/uio.h> (HAVE_SYS_UIO_H)...'
+$ECHO_N 'checking for <sys/uio.h> (HAVE_SYS_UIO_H)...' >> config.log
+MK_COMPILE_STATUS='OK'
+cat << EOT > conftest$$.c
+#include <sys/uio.h>
+int main (int argc, char *argv[]) { return (0); }
+
+EOT
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest$$ conftest$$.c  2>>config.log
+if [ $? != 0 ]; then
+	echo ": failed, code $?" >> config.log
+	MK_COMPILE_STATUS="FAIL $?"
+fi
+if [ "${MK_COMPILE_STATUS}" = 'OK' ]; then
+echo 'yes'
+echo 'yes' >> config.log
+HAVE_SYS_UIO_H='yes'
+echo '#ifndef HAVE_SYS_UIO_H' > $BLD/include/agar/config/have_sys_uio_h.h
+echo "#define HAVE_SYS_UIO_H \"$HAVE_SYS_UIO_H\"" >> $BLD/include/agar/config/have_sys_uio_h.h
+echo '#endif' >> $BLD/include/agar/config/have_sys_uio_h.h
+echo "hdefs[\"HAVE_SYS_UIO_H\"] = \"$HAVE_SYS_UIO_H\"" >>configure.lua
+else
+echo 'no'
+echo 'no' >> config.log
+HAVE_SYS_UIO_H='no'
+echo '#undef HAVE_SYS_UIO_H' >$BLD/include/agar/config/have_sys_uio_h.h
+echo 'hdefs["HAVE_SYS_UIO_H"] = nil' >>configure.lua
+fi;
+rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
+$ECHO_N 'checking for <sys/param.h> (HAVE_SYS_PARAM_H)...'
+$ECHO_N 'checking for <sys/param.h> (HAVE_SYS_PARAM_H)...' >> config.log
+MK_COMPILE_STATUS='OK'
+cat << EOT > conftest$$.c
+#include <sys/param.h>
+int main (int argc, char *argv[]) { return (0); }
+
+EOT
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest$$ conftest$$.c  2>>config.log
+if [ $? != 0 ]; then
+	echo ": failed, code $?" >> config.log
+	MK_COMPILE_STATUS="FAIL $?"
+fi
+if [ "${MK_COMPILE_STATUS}" = 'OK' ]; then
+echo 'yes'
+echo 'yes' >> config.log
+HAVE_SYS_PARAM_H='yes'
+echo '#ifndef HAVE_SYS_PARAM_H' > $BLD/include/agar/config/have_sys_param_h.h
+echo "#define HAVE_SYS_PARAM_H \"$HAVE_SYS_PARAM_H\"" >> $BLD/include/agar/config/have_sys_param_h.h
+echo '#endif' >> $BLD/include/agar/config/have_sys_param_h.h
+echo "hdefs[\"HAVE_SYS_PARAM_H\"] = \"$HAVE_SYS_PARAM_H\"" >>configure.lua
+else
+echo 'no'
+echo 'no' >> config.log
+HAVE_SYS_PARAM_H='no'
+echo '#undef HAVE_SYS_PARAM_H' >$BLD/include/agar/config/have_sys_param_h.h
+echo 'hdefs["HAVE_SYS_PARAM_H"] = nil' >>configure.lua
+fi;
+rm -f conftest$$.c $testdir/conftest$$$EXECSUFFIX
+HAVE_WEB="yes"
+AG_WEB="yes"
+echo '#ifndef AG_WEB' > $BLD/include/agar/config/ag_web.h
+echo "#define AG_WEB \"$AG_WEB\"" >> $BLD/include/agar/config/ag_web.h
+echo '#endif' >> $BLD/include/agar/config/ag_web.h
+echo "hdefs[\"AG_WEB\"] = \"$AG_WEB\"" >>configure.lua
+else
+echo '#undef HAVE_ZLIB' >$BLD/include/agar/config/have_zlib.h
+echo 'hdefs["HAVE_ZLIB"] = nil' >>configure.lua
+echo '#undef ZLIB_CFLAGS' >$BLD/include/agar/config/zlib_cflags.h
+echo 'hdefs["ZLIB_CFLAGS"] = nil' >>configure.lua
+echo '#undef ZLIB_LIBS' >$BLD/include/agar/config/zlib_libs.h
+echo 'hdefs["ZLIB_LIBS"] = nil' >>configure.lua
+echo '#undef HAVE_SYS_UIO_H' >$BLD/include/agar/config/have_sys_uio_h.h
+echo 'hdefs["HAVE_SYS_UIO_H"] = nil' >>configure.lua
+echo '#undef HAVE_SYS_PARAM_H' >$BLD/include/agar/config/have_sys_param_h.h
+echo 'hdefs["HAVE_SYS_PARAM_H"] = nil' >>configure.lua
+HAVE_WEB="no"
+echo '#undef AG_WEB' >$BLD/include/agar/config/ag_web.h
+echo 'hdefs["AG_WEB"] = nil' >>configure.lua
+fi
 if [ "${with_db4}" != 'no' ]
  then
 $ECHO_N 'checking for Berkeley DB 4.x...'
@@ -9830,6 +9996,10 @@ if [ "${HAVE_CSIDL}" = 'yes' ]
  then
 SRCS_CORE="${SRCS_CORE} user_win32.c"
 fi
+if [ "${HAVE_WEB}" = 'yes' ]
+ then
+SRCS_CORE="${SRCS_CORE} web.c web_auth.c web_var.c"
+fi
 SRCS_GUI=""
 if [ "${HAVE_SDL}" = 'yes' ]
  then
@@ -9906,8 +10076,8 @@ fi
 CFLAGS="$CFLAGS -I$BLD/include"
 CXXFLAGS="$CXXFLAGS -I$BLD/include"
 config_script_out="agar-config"
-config_script_cflags="-I${INCLDIR} ${SDL_CFLAGS} ${FREETYPE_CFLAGS} ${FONTCONFIG_CFLAGS} ${OPENGL_CFLAGS} ${X11_CFLAGS} ${GLX_CFLAGS} ${XINERAMA_CFLAGS} ${COCOA_CFLAGS} ${MATH_CFLAGS} ${PNG_CFLAGS} ${PTHREADS_CFLAGS} ${DB4_CFLAGS} ${MYSQL_CFLAGS} ${GETTEXT_CFLAGS} ${DSO_CFLAGS} ${CLOCK_CFLAGS} ${UIM_CFLAGS} ${ICONV_CFLAGS}"
-config_script_libs="-L${LIBDIR} -lag_gui -lag_core ${SDL_LIBS} ${FREETYPE_LIBS} ${FONTCONFIG_LIBS} ${OPENGL_LIBS} ${X11_LIBS} ${XINERAMA_LIBS} ${COCOA_LIBS} ${MATH_LIBS} ${JPEG_LIBS} ${PNG_LIBS} ${PTHREADS_LIBS} ${DB4_LIBS} ${MYSQL_LIBS} ${GETTEXT_LIBS} ${DSO_LIBS} ${CLOCK_LIBS} ${UIM_LIBS} ${ICONV_LIBS}"
+config_script_cflags="-I${INCLDIR} ${SDL_CFLAGS} ${FREETYPE_CFLAGS} ${FONTCONFIG_CFLAGS} ${OPENGL_CFLAGS} ${X11_CFLAGS} ${GLX_CFLAGS} ${XINERAMA_CFLAGS} ${COCOA_CFLAGS} ${MATH_CFLAGS} ${PNG_CFLAGS} ${PTHREADS_CFLAGS} ${DB4_CFLAGS} ${MYSQL_CFLAGS} ${GETTEXT_CFLAGS} ${DSO_CFLAGS} ${CLOCK_CFLAGS} ${UIM_CFLAGS} ${ICONV_CFLAGS} ${ZLIB_CFLAGS}"
+config_script_libs="-L${LIBDIR} -lag_gui -lag_core ${SDL_LIBS} ${FREETYPE_LIBS} ${FONTCONFIG_LIBS} ${OPENGL_LIBS} ${X11_LIBS} ${XINERAMA_LIBS} ${COCOA_LIBS} ${MATH_LIBS} ${JPEG_LIBS} ${PNG_LIBS} ${PTHREADS_LIBS} ${DB4_LIBS} ${MYSQL_LIBS} ${GETTEXT_LIBS} ${DSO_LIBS} ${CLOCK_LIBS} ${UIM_LIBS} ${ICONV_LIBS} ${ZLIB_LIBS}"
 # Avoid breakage with existing trees compiled before BSDBuild 2.8.
 if [ -d "$config_script_out" ]; then
 	echo "rm -fR $config_script_out"
@@ -9982,8 +10152,8 @@ while test \$# -gt 0; do
 done
 EOT
 config_script_out="agar-core-config"
-config_script_cflags="-I${INCLDIR} ${MATH_CFLAGS} ${GETTEXT_CFLAGS} ${DSO_CFLAGS} ${CLOCK_CFLAGS} ${ICONV_CFLAGS}"
-config_script_libs="-L${LIBDIR} -lag_core ${MATH_LIBS} ${PTHREADS_LIBS} ${DB4_LIBS} ${MYSQL_LIBS} ${GETTEXT_LIBS} ${DSO_LIBS} ${CLOCK_LIBS} ${ICONV_LIBS}"
+config_script_cflags="-I${INCLDIR} ${MATH_CFLAGS} ${GETTEXT_CFLAGS} ${DSO_CFLAGS} ${CLOCK_CFLAGS} ${ZLIB_CFLAGS} ${ICONV_CFLAGS} ${ZLIB_CFLAGS}"
+config_script_libs="-L${LIBDIR} -lag_core ${MATH_LIBS} ${PTHREADS_LIBS} ${DB4_LIBS} ${MYSQL_LIBS} ${GETTEXT_LIBS} ${DSO_LIBS} ${CLOCK_LIBS} ${ICONV_LIBS} ${ZLIB_LIBS}"
 # Avoid breakage with existing trees compiled before BSDBuild 2.8.
 if [ -d "$config_script_out" ]; then
 	echo "rm -fR $config_script_out"
@@ -10513,6 +10683,10 @@ echo "HAVE_SSE2=$HAVE_SSE2" >>Makefile.config
 echo "mdefs[\"HAVE_SSE2\"] = \"$HAVE_SSE2\"" >>configure.lua
 echo "HAVE_SSE3=$HAVE_SSE3" >>Makefile.config
 echo "mdefs[\"HAVE_SSE3\"] = \"$HAVE_SSE3\"" >>configure.lua
+echo "HAVE_SYS_PARAM_H=$HAVE_SYS_PARAM_H" >>Makefile.config
+echo "mdefs[\"HAVE_SYS_PARAM_H\"] = \"$HAVE_SYS_PARAM_H\"" >>configure.lua
+echo "HAVE_SYS_UIO_H=$HAVE_SYS_UIO_H" >>Makefile.config
+echo "mdefs[\"HAVE_SYS_UIO_H\"] = \"$HAVE_SYS_UIO_H\"" >>configure.lua
 echo "HAVE_UIM=$HAVE_UIM" >>Makefile.config
 echo "mdefs[\"HAVE_UIM\"] = \"$HAVE_UIM\"" >>configure.lua
 echo "HAVE_UNUSED_VARIABLE_ATTRIBUTE=$HAVE_UNUSED_VARIABLE_ATTRIBUTE" >>Makefile.config
@@ -10521,6 +10695,8 @@ echo "HAVE_VASPRINTF=$HAVE_VASPRINTF" >>Makefile.config
 echo "mdefs[\"HAVE_VASPRINTF\"] = \"$HAVE_VASPRINTF\"" >>configure.lua
 echo "HAVE_WARN_UNUSED_RESULT_ATTRIBUTE=$HAVE_WARN_UNUSED_RESULT_ATTRIBUTE" >>Makefile.config
 echo "mdefs[\"HAVE_WARN_UNUSED_RESULT_ATTRIBUTE\"] = \"$HAVE_WARN_UNUSED_RESULT_ATTRIBUTE\"" >>configure.lua
+echo "HAVE_WEB=$HAVE_WEB" >>Makefile.config
+echo "mdefs[\"HAVE_WEB\"] = \"$HAVE_WEB\"" >>configure.lua
 echo "HAVE_WGL=$HAVE_WGL" >>Makefile.config
 echo "mdefs[\"HAVE_WGL\"] = \"$HAVE_WGL\"" >>configure.lua
 echo "HAVE_X11=$HAVE_X11" >>Makefile.config
@@ -10529,6 +10705,8 @@ echo "HAVE_XINERAMA=$HAVE_XINERAMA" >>Makefile.config
 echo "mdefs[\"HAVE_XINERAMA\"] = \"$HAVE_XINERAMA\"" >>configure.lua
 echo "HAVE_XKB=$HAVE_XKB" >>Makefile.config
 echo "mdefs[\"HAVE_XKB\"] = \"$HAVE_XKB\"" >>configure.lua
+echo "HAVE_ZLIB=$HAVE_ZLIB" >>Makefile.config
+echo "mdefs[\"HAVE_ZLIB\"] = \"$HAVE_ZLIB\"" >>configure.lua
 echo "HAVE___INT64=$HAVE___INT64" >>Makefile.config
 echo "mdefs[\"HAVE___INT64\"] = \"$HAVE___INT64\"" >>configure.lua
 echo "ICONV_CFLAGS=$ICONV_CFLAGS" >>Makefile.config
@@ -10659,6 +10837,10 @@ echo "XINERAMA_CFLAGS=$XINERAMA_CFLAGS" >>Makefile.config
 echo "mdefs[\"XINERAMA_CFLAGS\"] = \"$XINERAMA_CFLAGS\"" >>configure.lua
 echo "XINERAMA_LIBS=$XINERAMA_LIBS" >>Makefile.config
 echo "mdefs[\"XINERAMA_LIBS\"] = \"$XINERAMA_LIBS\"" >>configure.lua
+echo "ZLIB_CFLAGS=$ZLIB_CFLAGS" >>Makefile.config
+echo "mdefs[\"ZLIB_CFLAGS\"] = \"$ZLIB_CFLAGS\"" >>configure.lua
+echo "ZLIB_LIBS=$ZLIB_LIBS" >>Makefile.config
+echo "mdefs[\"ZLIB_LIBS\"] = \"$ZLIB_LIBS\"" >>configure.lua
 echo "_MK_HAVE_FLOAT_H=$_MK_HAVE_FLOAT_H" >>Makefile.config
 echo "mdefs[\"_MK_HAVE_FLOAT_H\"] = \"$_MK_HAVE_FLOAT_H\"" >>configure.lua
 echo "_MK_HAVE_LIMITS_H=$_MK_HAVE_LIMITS_H" >>Makefile.config
