sync

diff --git a/trunk/demos/gamemenu/configure b/trunk/demos/gamemenu/configure
--- a/trunk/demos/gamemenu/configure
+++ b/trunk/demos/gamemenu/configure
@@ -102,24 +102,9 @@ do
 done
 
 if [ "${prefix}" != "" ]; then
-    PREFIX=$prefix
+    PREFIX="$prefix"
 else
-    PREFIX=/usr/local
-fi
-if [ "${sysconfdir}" != "" ]; then
-    SYSCONFDIR=$sysconfdir
-else
-    SYSCONFDIR=/etc
-fi
-if [ "${sharedir}" != "" ]; then
-    SHAREDIR=$sharedir
-else
-    SHAREDIR=${PREFIX}/share
-fi
-if [ "${localedir}" != "" ]; then
-    LOCALEDIR=$localedir
-else
-    LOCALEDIR=${SHAREDIR}/locale
+    PREFIX="/usr/local"
 fi
 
 if [ "${srcdir}" != "" ]; then
@@ -143,10 +128,6 @@ if [ "${srcdir}" != "" ]; then
 		exit 1;
 	fi
 else
-#	if [ ! -e "configure.in" ]; then
-#		echo "Missing --srcdir argument"
-#		exit 1
-#	fi
 	SRC=`pwd`
 fi
 if [ "${help}" = "yes" ]; then
@@ -172,7 +153,7 @@ SYSTEM=`uname -s 2>/dev/null` || SYSTEM=unknown
 HOST="$SYSTEM-$RELEASE-$MACHINE"
 echo "Host: $HOST"
 
-echo > Makefile.config
+echo "# File generated by csoft-mk 2.0." > Makefile.config
 echo "Machine: $MACHINE" > config.log
 echo "Release: $RELEASE" >> config.log
 echo "System: $SYSTEM" >> config.log
@@ -185,7 +166,7 @@ if [ "${with_docs}" = "no" ]; then
     echo "NODOC=yes" >> Makefile.config
 fi
 if [ "${enable_debug}" = "yes" ]; then
-	echo "LDFLAGS=-g" >> Makefile.config
+	echo "LDFLAGS+=-g" >> Makefile.config
 	echo "#ifndef DEBUG" > config/debug.h
 	echo "#define DEBUG 1" >> config/debug.h
 	echo "#endif /* DEBUG */" >> config/debug.h
@@ -206,46 +187,68 @@ if [ "${enable_nls}" = "yes" ]; then
 	done
 	if [ "${msgfmt}" != "" ]; then
 		HAVE_GETTEXT="yes"
-		echo "LOCALEDIR=${LOCALEDIR}" >> Makefile.config
-		echo "#ifndef LOCALEDIR" > config/localedir.h
-		echo "#define LOCALEDIR \"${LOCALEDIR}\"" >> config/localedir.h
-		echo "#endif /* LOCALEDIR */" >> config/localedir.h
 	else
 		HAVE_GETTEXT="no"
-		echo "#undef LOCALEDIR" > config/localedir.h
 	fi
 else
 	ENABLE_NLS="no"
 	HAVE_GETTEXT="no"
 	echo "#undef ENABLE_NLS" > config/enable_nls.h
-	echo "#undef LOCALEDIR" > config/localedir.h
 fi
 echo "ENABLE_NLS=${ENABLE_NLS}" >> Makefile.config
 echo "HAVE_GETTEXT=${HAVE_GETTEXT}" >> Makefile.config
 
-echo "PREFIX=${PREFIX}" >> Makefile.config
+echo "PREFIX?=${PREFIX}" >> Makefile.config
 echo "#ifndef PREFIX" > config/prefix.h
 echo "#define PREFIX \"${PREFIX}\"" >> config/prefix.h
 echo "#endif /* PREFIX */" >> config/prefix.h
 
-echo "SHAREDIR=${SHAREDIR}" >> Makefile.config
-echo "#ifndef SHAREDIR" > config/sharedir.h
-echo "#define SHAREDIR \"${SHAREDIR}\"" >> config/sharedir.h
-echo "#endif /* SHAREDIR */" >> config/sharedir.h
+if [ "${sharedir}" != "" ]; then
+	echo "SHAREDIR=${sharedir}" >> Makefile.config
+	echo "#ifndef SHAREDIR" > config/sharedir.h
+	echo "#define SHAREDIR \"${sharedir}\"" >> config/sharedir.h
+	echo "#endif /* SHAREDIR */" >> config/sharedir.h
+	SHAREDIR="${sharedir}"
+else
+	echo "SHAREDIR=\${PREFIX}/share" >> Makefile.config
+	echo "#ifndef SHAREDIR" > config/sharedir.h
+	echo "#define SHAREDIR \"${SHAREDIR}\"" >> config/sharedir.h
+	echo "#endif /* SHAREDIR */" >> config/sharedir.h
+	SHAREDIR="${PREFIX}/share"
+fi
 
-echo "SYSCONFDIR=${SYSCONFDIR}" >> Makefile.config
-echo "#ifndef SYSCONFDIR" > config/sysconfdir.h
-echo "#define SYSCONFDIR \"${SYSCONFDIR}\"" >> config/sysconfdir.h
-echo "#endif /* SYSCONFDIR */" >> config/sysconfdir.h
+if [ "${localedir}" != "" ]; then
+	LOCALEDIR="${localedir}"
+	echo "LOCALEDIR=${LOCALEDIR}" >> Makefile.config
+	echo "#ifndef LOCALEDIR" > config/localedir.h
+	echo "#define LOCALEDIR \"${LOCALEDIR}\"" >> config/localedir.h
+	echo "#endif /* LOCALEDIR */" >> config/localedir.h
+else
+	LOCALEDIR="${SHAREDIR}/locale"
+	echo "LOCALEDIR=\${SHAREDIR}/locale" >> Makefile.config
+	echo "#ifndef LOCALEDIR" > config/localedir.h
+	echo "#define LOCALEDIR \"${LOCALEDIR}\"" >> config/localedir.h
+	echo "#endif /* LOCALEDIR */" >> config/localedir.h
+fi
 
-echo "LOCALEDIR=${LOCALEDIR}" >> Makefile.config
-echo "#ifndef LOCALEDIR" > config/localedir.h
-echo "#define LOCALEDIR \"${LOCALEDIR}\"" >> config/localedir.h
-echo "#endif /* LOCALEDIR */" >> config/localedir.h
+if [ "${sysconfdir}" != "" ]; then
+	SYSCONFDIR="${sysconfdir}"
+	echo "SYSCONFDIR=${sysconfdir}" >> Makefile.config
+	echo "#ifndef SYSCONFDIR" > config/sysconfdir.h
+	echo "#define SYSCONFDIR \"${SYSCONFDIR}\"" >> config/sysconfdir.h
+	echo "#endif /* SYSCONFDIR */" >> config/sysconfdir.h
+else
+	SYSCONFDIR="${PREFIX}/etc"
+	echo "SYSCONFDIR=\${PREFIX}/etc" >> Makefile.config
+	echo "#ifndef SYSCONFDIR" > config/sysconfdir.h
+	echo "#define SYSCONFDIR \"${SYSCONFDIR}\"" >> config/sysconfdir.h
+	echo "#endif /* SYSCONFDIR */" >> config/sysconfdir.h
+fi
+
 VERSION="\"1.0\""
 echo "#ifndef VERSION" > config/version.h
 echo "#define VERSION" $VERSION >> config/version.h
-echo "#endif /* VERSION */" >> config/version.h
+echo "#endif" >> config/version.h
 echo -n "checking for a usable C compiler..."
 echo -n "checking for a usable C compiler..." >> config.log
 if [ "$CC" = "" ]; then
@@ -297,7 +300,7 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-$CC -o conftest conftest.c 2>>config.log
+$CC $CFLAGS -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
 	echo "-> failed: non-zero exit status" >> config.log
 	compile="failed"
@@ -307,7 +310,7 @@ if [ "${compile}" = "ok" ]; then
 	echo "ok" >> config.log
 	echo "#ifndef HAVE_IEEE754" > config/have_ieee754.h
 echo "#define HAVE_IEEE754" $HAVE_IEEE754 >> config/have_ieee754.h
-echo "#endif /* HAVE_IEEE754 */" >> config/have_ieee754.h
+echo "#endif" >> config/have_ieee754.h
 
 	echo "yes"
 else
@@ -329,7 +332,7 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-$CC -o conftest conftest.c 2>>config.log
+$CC $CFLAGS -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
 	echo "-> failed: non-zero exit status" >> config.log
 	compile="failed"
@@ -339,7 +342,7 @@ if [ "${compile}" = "ok" ]; then
 	echo "ok" >> config.log
 	echo "#ifndef HAVE_LONG_DOUBLE" > config/have_long_double.h
 echo "#define HAVE_LONG_DOUBLE" $HAVE_LONG_DOUBLE >> config/have_long_double.h
-echo "#endif /* HAVE_LONG_DOUBLE */" >> config/have_long_double.h
+echo "#endif" >> config/have_long_double.h
 
 	echo "yes"
 else
@@ -369,7 +372,7 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-$CC -Wall -Werror -o conftest conftest.c 2>>config.log
+$CC $CFLAGS -Wall -Werror -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
 	echo "-> failed: non-zero exit status" >> config.log
 	compile="failed"
@@ -379,7 +382,7 @@ if [ "${compile}" = "ok" ]; then
 	echo "ok" >> config.log
 	echo "#ifndef HAVE_BOUNDED_ATTRIBUTE" > config/have_bounded_attribute.h
 echo "#define HAVE_BOUNDED_ATTRIBUTE" $HAVE_BOUNDED_ATTRIBUTE >> config/have_bounded_attribute.h
-echo "#endif /* HAVE_BOUNDED_ATTRIBUTE */" >> config/have_bounded_attribute.h
+echo "#endif" >> config/have_bounded_attribute.h
 
 	echo "yes"
 else
@@ -411,7 +414,7 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-$CC -Wall -Werror -o conftest conftest.c 2>>config.log
+$CC $CFLAGS -Wall -Werror -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
 	echo "-> failed: non-zero exit status" >> config.log
 	compile="failed"
@@ -421,7 +424,7 @@ if [ "${compile}" = "ok" ]; then
 	echo "ok" >> config.log
 	echo "#ifndef HAVE_FORMAT_ATTRIBUTE" > config/have_format_attribute.h
 echo "#define HAVE_FORMAT_ATTRIBUTE" $HAVE_FORMAT_ATTRIBUTE >> config/have_format_attribute.h
-echo "#endif /* HAVE_FORMAT_ATTRIBUTE */" >> config/have_format_attribute.h
+echo "#endif" >> config/have_format_attribute.h
 
 	echo "yes"
 else
@@ -449,7 +452,7 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-$CC -Wall -Werror -o conftest conftest.c 2>>config.log
+$CC $CFLAGS -Wall -Werror -o conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
 	echo "-> failed: non-zero exit status" >> config.log
 	compile="failed"
@@ -459,13 +462,53 @@ if [ "${compile}" = "ok" ]; then
 	echo "ok" >> config.log
 	echo "#ifndef HAVE_NONNULL_ATTRIBUTE" > config/have_nonnull_attribute.h
 echo "#define HAVE_NONNULL_ATTRIBUTE" $HAVE_NONNULL_ATTRIBUTE >> config/have_nonnull_attribute.h
-echo "#endif /* HAVE_NONNULL_ATTRIBUTE */" >> config/have_nonnull_attribute.h
+echo "#endif" >> config/have_nonnull_attribute.h
 
 	echo "yes"
 else
     echo "#undef HAVE_NONNULL_ATTRIBUTE" > config/have_nonnull_attribute.h
 
 	echo "no"
+fi
+echo -n "checking for cygwin environment..."
+echo -n "checking for cygwin environment..." >> config.log
+cat << EOT > conftest.c
+#include <sys/types.h>
+#include <sys/stat.h>
+#include <windows.h>
+
+int
+main(int argc, char *argv[]) {
+	struct stat sb;
+	DWORD rv;
+	rv = GetFileAttributes("foo");
+	stat("foo", &sb);
+	return (0);
+}
+
+EOT
+compile="ok"
+$CC $CFLAGS -mcygwin -o conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed: non-zero exit status" >> config.log
+	compile="failed"
+fi
+rm -f conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+	echo "ok" >> config.log
+	echo "#ifndef HAVE_CYGWIN" > config/have_cygwin.h
+echo "#define HAVE_CYGWIN" $HAVE_CYGWIN >> config/have_cygwin.h
+echo "#endif" >> config/have_cygwin.h
+
+	echo "yes"
+else
+    echo "#undef HAVE_CYGWIN" > config/have_cygwin.h
+
+	echo "no"
+fi
+if [ "${compile}" = "ok" ]; then
+	CFLAGS="$CFLAGS -mno-cygwin"
+	echo "CFLAGS=$CFLAGS" >> Makefile.config
 fi
 echo -n "checking for Agar (http://agar.csoft.org/)..."
 echo -n "checking for Agar (http://agar.csoft.org/)..." >> config.log
@@ -494,13 +537,13 @@ echo "AGAR_CFLAGS=$AGAR_CFLAGS" >> Makefile.config
 echo "AGAR_LIBS=$AGAR_LIBS" >> Makefile.config
 echo "#ifndef HAVE_AGAR" > config/have_agar.h
 echo "#define HAVE_AGAR" $HAVE_AGAR >> config/have_agar.h
-echo "#endif /* HAVE_AGAR */" >> config/have_agar.h
+echo "#endif" >> config/have_agar.h
 echo "#ifndef AGAR_CFLAGS" > config/agar_cflags.h
 echo "#define AGAR_CFLAGS \"$AGAR_CFLAGS\"" >> config/agar_cflags.h
-echo "#endif /* AGAR_CFLAGS */" >> config/agar_cflags.h
+echo "#endif" >> config/agar_cflags.h
 echo "#ifndef AGAR_LIBS" > config/agar_libs.h
 echo "#define AGAR_LIBS \"$AGAR_LIBS\"" >> config/agar_libs.h
-echo "#endif /* AGAR_LIBS */" >> config/agar_libs.h
+echo "#endif" >> config/agar_libs.h
 else
 echo "no"
 echo "no" >> config.log
@@ -525,7 +568,7 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-$CC ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_LIBS} 2>>config.log
+$CC $CFLAGS ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_LIBS} 2>>config.log
 if [ $? != 0 ]; then
 	echo "failed" >> config.log
 	compile="failed"
@@ -535,7 +578,7 @@ if [ "${compile}" = "ok" ]; then
 	echo "ok" >> config.log
 	echo "#ifndef HAVE_AGAR" > config/have_agar.h
 echo "#define HAVE_AGAR" $HAVE_AGAR >> config/have_agar.h
-echo "#endif /* HAVE_AGAR */" >> config/have_agar.h
+echo "#endif" >> config/have_agar.h
 
 	HAVE_AGAR=yes
 
