unbreak NLS
git-svn-id: https://dev.csoft.net/agar/trunk@7164 86a84d31-9702-0410-8f1e-a60cab7bd424

diff --git a/agarpaint/configure.in b/agarpaint/configure.in
--- a/agarpaint/configure.in
+++ b/agarpaint/configure.in
@@ -55,3 +55,15 @@ fi
 if [ "${enable_static}" = "yes" ]; then
 	MDEFINE(LDFLAGS, "-static")
 fi
+
+# Enable NLS if requested explicitely.
+if [ "${enable_nls}" = "yes" ]; then
+	CHECK(gettext)
+	if [ "${HAVE_GETTEXT}" != "yes" ]; then
+		echo "*"
+		echo "* --enable-nls was given but gettext was not found. Try"
+		echo "* running configure again without this option."
+		echo "*"
+		exit 1
+	fi
+fi
diff --git a/configure.in b/configure.in
--- a/configure.in
+++ b/configure.in
@@ -309,3 +309,15 @@ if [ "${enable_32bpp}" != "no" ]; then
 else
 	HUNDEF(VIEW_32BPP)
 fi
+
+# Enable NLS if requested explicitely.
+if [ "${enable_nls}" = "yes" ]; then
+	CHECK(gettext)
+	if [ "${HAVE_GETTEXT}" != "yes" ]; then
+		echo "*"
+		echo "* --enable-nls was given but gettext was not found. Try"
+		echo "* running configure again without this option."
+		echo "*"
+		exit 1
+	fi
+fi
