unbreak NLS

diff --git a/trunk/agarpaint/configure b/trunk/agarpaint/configure
--- a/trunk/agarpaint/configure
+++ b/trunk/agarpaint/configure
@@ -2099,5 +2099,211 @@ LDFLAGS="-static"
 echo "LDFLAGS=$LDFLAGS" >>Makefile.config
 echo "mdefs[\"LDFLAGS\"] = \"$LDFLAGS\"" >>configure.lua
 fi
+if [ "${enable_nls}" = "yes" ]
+ then
+$ECHO_N "checking for a gettext library..."
+$ECHO_N "checking for a gettext library..." >> config.log
+GETTEXT_CFLAGS=""
+GETTEXT_LIBS=""
+cat << EOT > conftest.c
+#include <libintl.h>
+int main(int argc, char *argv[])
+{
+	char *s;
+	bindtextdomain("foo", "/foo");
+	textdomain("foo");
+	s = gettext("string");
+	s = dgettext("foo","string");
+	return (0);
+}
+
+EOT
+echo "$CC $CFLAGS $TEST_CFLAGS ${GETTEXT_CFLAGS} -o $testdir/conftest conftest.c ${GETTEXT_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${GETTEXT_CFLAGS} -o $testdir/conftest conftest.c ${GETTEXT_LIBS} 2>>config.log
+if [ "$?" = "0" ]; then
+echo "yes"
+echo "yes" >> config.log
+compile="ok"
+HAVE_GETTEXT="yes"
+echo "HAVE_GETTEXT=$HAVE_GETTEXT" >>Makefile.config
+echo "mdefs[\"HAVE_GETTEXT\"] = \"$HAVE_GETTEXT\"" >>configure.lua
+echo "#ifndef HAVE_GETTEXT" > config/have_gettext.h
+echo "#define HAVE_GETTEXT \"$HAVE_GETTEXT\"" >> config/have_gettext.h
+echo "#endif" >> config/have_gettext.h
+echo "hdefs[\"HAVE_GETTEXT\"] = \"$HAVE_GETTEXT\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+compile="failed"
+HAVE_GETTEXT="no"
+echo "HAVE_GETTEXT=$HAVE_GETTEXT" >>Makefile.config
+echo "mdefs[\"HAVE_GETTEXT\"] = \"$HAVE_GETTEXT\"" >>configure.lua
+echo "#undef HAVE_GETTEXT" >config/have_gettext.h
+echo "hdefs[\"HAVE_GETTEXT\"] = nil" >>configure.lua
+fi;
+rm -f $testdir/conftest conftest.c
+if [ "${HAVE_GETTEXT}" = "no" ]; then
+$ECHO_N "checking whether gettext requires -lintl..."
+$ECHO_N "checking whether gettext requires -lintl..." >> config.log
+if [ -e /usr/include/libintl.h ]; then
+GETTEXT_CFLAGS="-I/usr/include"
+GETTEXT_LIBS="-L/usr/lib -lintl"
+fi;
+if [ -e /usr/local/include/libintl.h ]; then
+GETTEXT_CFLAGS="-I/usr/local/include"
+GETTEXT_LIBS="-L/usr/local/lib -lintl"
+fi;
+if [ -e /opt/include/libintl.h ]; then
+GETTEXT_CFLAGS="-I/opt/include"
+GETTEXT_LIBS="-L/opt/lib -lintl"
+fi;
+if [ -e /opt/local/include/libintl.h ]; then
+GETTEXT_CFLAGS="-I/opt/local/include"
+GETTEXT_LIBS="-L/opt/local/lib -lintl"
+fi;
+cat << EOT > conftest.c
+#include <libintl.h>
+int main(int argc, char *argv[])
+{
+	char *s;
+	bindtextdomain("foo", "/foo");
+	textdomain("foo");
+	s = gettext("string");
+	s = dgettext("foo","string");
+	return (0);
+}
+
+EOT
+echo "$CC $CFLAGS $TEST_CFLAGS ${GETTEXT_CFLAGS} -o $testdir/conftest conftest.c ${GETTEXT_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${GETTEXT_CFLAGS} -o $testdir/conftest conftest.c ${GETTEXT_LIBS} 2>>config.log
+if [ "$?" = "0" ]; then
+echo "yes"
+echo "yes" >> config.log
+compile="ok"
+HAVE_GETTEXT="yes"
+echo "HAVE_GETTEXT=$HAVE_GETTEXT" >>Makefile.config
+echo "mdefs[\"HAVE_GETTEXT\"] = \"$HAVE_GETTEXT\"" >>configure.lua
+echo "#ifndef HAVE_GETTEXT" > config/have_gettext.h
+echo "#define HAVE_GETTEXT \"$HAVE_GETTEXT\"" >> config/have_gettext.h
+echo "#endif" >> config/have_gettext.h
+echo "hdefs[\"HAVE_GETTEXT\"] = \"$HAVE_GETTEXT\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+compile="failed"
+HAVE_GETTEXT="no"
+echo "HAVE_GETTEXT=$HAVE_GETTEXT" >>Makefile.config
+echo "mdefs[\"HAVE_GETTEXT\"] = \"$HAVE_GETTEXT\"" >>configure.lua
+echo "#undef HAVE_GETTEXT" >config/have_gettext.h
+echo "hdefs[\"HAVE_GETTEXT\"] = nil" >>configure.lua
+fi;
+rm -f $testdir/conftest conftest.c
+if [ "${HAVE_GETTEXT}" = "yes" ]; then
+echo "#ifndef GETTEXT_CFLAGS" > config/gettext_cflags.h
+echo "#define GETTEXT_CFLAGS \"$GETTEXT_CFLAGS\"" >> config/gettext_cflags.h
+echo "#endif" >> config/gettext_cflags.h
+echo "hdefs[\"GETTEXT_CFLAGS\"] = \"$GETTEXT_CFLAGS\"" >>configure.lua
+echo "#ifndef GETTEXT_LIBS" > config/gettext_libs.h
+echo "#define GETTEXT_LIBS \"$GETTEXT_LIBS\"" >> config/gettext_libs.h
+echo "#endif" >> config/gettext_libs.h
+echo "hdefs[\"GETTEXT_LIBS\"] = \"$GETTEXT_LIBS\"" >>configure.lua
+echo "GETTEXT_CFLAGS=$GETTEXT_CFLAGS" >>Makefile.config
+echo "mdefs[\"GETTEXT_CFLAGS\"] = \"$GETTEXT_CFLAGS\"" >>configure.lua
+echo "GETTEXT_LIBS=$GETTEXT_LIBS" >>Makefile.config
+echo "mdefs[\"GETTEXT_LIBS\"] = \"$GETTEXT_LIBS\"" >>configure.lua
+else
+$ECHO_N "checking whether -lintl requires -liconv..."
+$ECHO_N "checking whether -lintl requires -liconv..." >> config.log
+if [ -e /usr/include/iconv.h ]; then
+GETTEXT_CFLAGS="${GETTEXT_CFLAGS} -I/usr/include"
+GETTEXT_LIBS="${GETTEXT_LIBS} -L/usr/lib -liconv"
+fi;
+if [ -e /usr/local/include/iconv.h ]; then
+GETTEXT_CFLAGS="${GETTEXT_CFLAGS} -I/usr/local/include"
+GETTEXT_LIBS="${GETTEXT_LIBS} -L/usr/local/lib -liconv"
+fi;
+if [ -e /opt/include/iconv.h ]; then
+GETTEXT_CFLAGS="${GETTEXT_CFLAGS} -I/opt/include"
+GETTEXT_LIBS="${GETTEXT_LIBS} -L/opt/lib -liconv"
+fi;
+if [ -e /opt/local/include/iconv.h ]; then
+GETTEXT_CFLAGS="${GETTEXT_CFLAGS} -I/opt/local/include"
+GETTEXT_LIBS="${GETTEXT_LIBS} -L/opt/local/lib -liconv"
+fi;
+cat << EOT > conftest.c
+#include <libintl.h>
+int main(int argc, char *argv[])
+{
+	char *s;
+	bindtextdomain("foo", "/foo");
+	textdomain("foo");
+	s = gettext("string");
+	s = dgettext("foo","string");
+	return (0);
+}
+
+EOT
+echo "$CC $CFLAGS $TEST_CFLAGS ${GETTEXT_CFLAGS} -o $testdir/conftest conftest.c ${GETTEXT_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${GETTEXT_CFLAGS} -o $testdir/conftest conftest.c ${GETTEXT_LIBS} 2>>config.log
+if [ "$?" = "0" ]; then
+echo "yes"
+echo "yes" >> config.log
+compile="ok"
+HAVE_GETTEXT="yes"
+echo "HAVE_GETTEXT=$HAVE_GETTEXT" >>Makefile.config
+echo "mdefs[\"HAVE_GETTEXT\"] = \"$HAVE_GETTEXT\"" >>configure.lua
+echo "#ifndef HAVE_GETTEXT" > config/have_gettext.h
+echo "#define HAVE_GETTEXT \"$HAVE_GETTEXT\"" >> config/have_gettext.h
+echo "#endif" >> config/have_gettext.h
+echo "hdefs[\"HAVE_GETTEXT\"] = \"$HAVE_GETTEXT\"" >>configure.lua
+else
+echo "no"
+echo "no" >> config.log
+compile="failed"
+HAVE_GETTEXT="no"
+echo "HAVE_GETTEXT=$HAVE_GETTEXT" >>Makefile.config
+echo "mdefs[\"HAVE_GETTEXT\"] = \"$HAVE_GETTEXT\"" >>configure.lua
+echo "#undef HAVE_GETTEXT" >config/have_gettext.h
+echo "hdefs[\"HAVE_GETTEXT\"] = nil" >>configure.lua
+fi;
+rm -f $testdir/conftest conftest.c
+if [ "${HAVE_GETTEXT}" != "" ]; then
+echo "#ifndef GETTEXT_CFLAGS" > config/gettext_cflags.h
+echo "#define GETTEXT_CFLAGS \"$GETTEXT_CFLAGS\"" >> config/gettext_cflags.h
+echo "#endif" >> config/gettext_cflags.h
+echo "hdefs[\"GETTEXT_CFLAGS\"] = \"$GETTEXT_CFLAGS\"" >>configure.lua
+echo "#ifndef GETTEXT_LIBS" > config/gettext_libs.h
+echo "#define GETTEXT_LIBS \"$GETTEXT_LIBS\"" >> config/gettext_libs.h
+echo "#endif" >> config/gettext_libs.h
+echo "hdefs[\"GETTEXT_LIBS\"] = \"$GETTEXT_LIBS\"" >>configure.lua
+echo "GETTEXT_CFLAGS=$GETTEXT_CFLAGS" >>Makefile.config
+echo "mdefs[\"GETTEXT_CFLAGS\"] = \"$GETTEXT_CFLAGS\"" >>configure.lua
+echo "GETTEXT_LIBS=$GETTEXT_LIBS" >>Makefile.config
+echo "mdefs[\"GETTEXT_LIBS\"] = \"$GETTEXT_LIBS\"" >>configure.lua
+fi;
+fi;
+else
+echo "#ifndef GETTEXT_CFLAGS" > config/gettext_cflags.h
+echo "#define GETTEXT_CFLAGS \"$GETTEXT_CFLAGS\"" >> config/gettext_cflags.h
+echo "#endif" >> config/gettext_cflags.h
+echo "hdefs[\"GETTEXT_CFLAGS\"] = \"$GETTEXT_CFLAGS\"" >>configure.lua
+echo "#ifndef GETTEXT_LIBS" > config/gettext_libs.h
+echo "#define GETTEXT_LIBS \"$GETTEXT_LIBS\"" >> config/gettext_libs.h
+echo "#endif" >> config/gettext_libs.h
+echo "hdefs[\"GETTEXT_LIBS\"] = \"$GETTEXT_LIBS\"" >>configure.lua
+echo "GETTEXT_CFLAGS=$GETTEXT_CFLAGS" >>Makefile.config
+echo "mdefs[\"GETTEXT_CFLAGS\"] = \"$GETTEXT_CFLAGS\"" >>configure.lua
+echo "GETTEXT_LIBS=$GETTEXT_LIBS" >>Makefile.config
+echo "mdefs[\"GETTEXT_LIBS\"] = \"$GETTEXT_LIBS\"" >>configure.lua
+fi;
+	if [ "${HAVE_GETTEXT}" != "yes" ]
+ then
+		echo "*"
+		echo "* --enable-nls was given but gettext was not found. Try"
+		echo "* running configure again without this option."
+		echo "*"
+		exit 1
+	fi
+fi
 echo "Don't forget to run \"make depend\"."
 echo "Don't forget to run \"make depend\"." >> config.log
