abort ./configure if configure fails in a subdir; thanks Olivier Boudeville!
git-svn-id: https://dev.csoft.net/agar/trunk@8620 86a84d31-9702-0410-8f1e-a60cab7bd424

diff --git a/demos/Makefile b/demos/Makefile
--- a/demos/Makefile
+++ b/demos/Makefile
@@ -43,17 +43,23 @@ install:
 	@exit 1
 
 configure:
-	if [ ! -e ".cache" ]; then \
-		echo "mkdir .cache"; \
-		mkdir .cache; \
+	if [ -e ".configurecache" ]; then \
+		echo "rm -fR .configurecache"; \
+		rm -fR .configurecache; \
 	fi
+	echo "mkdir .configurecache"; \
+	mkdir .configurecache; \
 	for D in ${SUBDIR}; do \
 		echo "==> $$D"; \
-		(cd $$D && ./configure --cache=../.cache); \
+		(cd $$D && ./configure --cache=../.configurecache); \
+		if [ $$? != 0 ]; then \
+			echo "$$D: configure failed; aborting"; \
+			exit 1; \
+		fi; \
 	done
 
 cleandir-cache:
-	rm -fR .cache
+	rm -fR .configurecache
 
 configure-scripts:
 	for D in ${SUBDIR}; do \
