regen

diff --git a/trunk/agar-bench/configure b/trunk/agar-bench/configure
--- a/trunk/agar-bench/configure
+++ b/trunk/agar-bench/configure
@@ -6,7 +6,7 @@
 # To regenerate this file, get the latest BSDbuild release from
 # http://hypertriton.com/bsdbuild/, and use the command:
 #
-#      configure.in | mkconfigure > configure
+#     $ cat configure.in | mkconfigure > configure
 #
 # Copyright (c) 2001-2007 Hypertriton, Inc. <http://hypertriton.com/>
 # All rights reserved.
@@ -97,6 +97,9 @@ do
 	--srcdir=*)
 	    srcdir=$optarg
 	    ;;
+	--testdir=*)
+	    testdir=$optarg
+	    ;;
 	*)
 	    echo "invalid argument: $arg"
 	    echo "try ./configure --help"
@@ -121,6 +124,16 @@ if [ "${srcdir}" != "" ]; then
 else
 	SRC=`pwd`
 fi
+
+if [ "${testdir}" != "" ]; then
+	echo "Configure tests will be executed in ${testdir}"
+	if [ ! -e "${testdir}" ]; then
+		echo "Creating ${testdir}"
+		mkdir ${testdir}
+	fi
+else
+	testdir="."
+fi
 if [ "${help}" = "yes" ]; then
 echo "Usage: ./configure [args]"
 echo "    --prefix                       Installation prefix [/usr/local]"
@@ -128,9 +141,11 @@ echo "    --sysconfdir                   System-wide configuration prefix [/etc]
 echo "    --sharedir                     Share prefix [$PREFIX/share]"
 echo "    --localedir                    Locale prefix [$PREFIX/share/locale]"
 echo "    --srcdir                       Source tree for concurrent build [.]"
+echo "    --testdir                      Directory in which to execute tests [.]"
 echo "    --help                         Display this message"
 echo "    --enable-nls                   Native Language Support [no]"
 echo "    --with-gettext                 Use gettext tools (msgmerge, ...) [check]"
+echo "    --with-libtool                 Specify path to libtool [check]"
 echo "    --with-manpages                Manual pages (-mdoc) [yes]"
 echo "    --with-docs                    Printable docs (-me/tbl/eqn/pic/refer) [no]"
 echo "    --enable-debug                 Include debugging code [no]"
@@ -139,15 +154,19 @@ exit 1
 fi
 
 MACHINE=`uname -m 2>/dev/null` || MACHINE=unknown
-RELEASE=`uname -r 2>/dev/null` || RELEASE=unknown
+OSRELEASE=`uname -r 2>/dev/null` || OSRELEASE=unknown
 SYSTEM=`uname -s 2>/dev/null` || SYSTEM=unknown
-HOST="$SYSTEM-$RELEASE-$MACHINE"
+HOST="$SYSTEM-$OSRELEASE-$MACHINE"
 echo "Host: $HOST"
 
 echo "# File generated by configure script (BSDbuild 2.1)." > Makefile.config
 echo "Machine: $MACHINE" > config.log
-echo "Release: $RELEASE" >> config.log
+echo "Release: $OSRELEASE" >> config.log
 echo "System: $SYSTEM" >> config.log
+for arg
+do
+	echo "Argument: $arg" >> config.log
+done
 mkdir config 1>/dev/null 2>&1
 
 HAVE_MANDOC="no"
@@ -159,7 +178,7 @@ for path in `echo $PATH | sed 's/:/ /g'`; do
 done
 if [ "${NROFF}" != "" ]; then
 	echo | ${NROFF} -Tmandoc >/dev/null
-	if [ $? == 0 ]; then
+	if [ "$?" = "0" ]; then
 		HAVE_MANDOC="yes"
 	fi
 fi
@@ -217,6 +236,48 @@ fi
 echo "ENABLE_NLS=${ENABLE_NLS}" >> Makefile.config
 echo "HAVE_GETTEXT=${HAVE_GETTEXT}" >> Makefile.config
 
+LIBTOOL_BUNDLED="yes"
+LIBTOOL=\${TOP}/mk/libtool/libtool
+echo "LIBTOOL=${LIBTOOL}" >> Makefile.config
+
+#
+# (insert defamatory comment about libtool here)
+#
+#echo -n "checking for libtool..."
+#if [ "${with_libtool}" != "" ]; then
+#	LIBTOOL=${with_libtool}
+#else
+#	ltool=""
+#	for path in `echo $PATH | sed 's/:/ /g'`; do
+#		if [ -x "${path}/libtool" ]; then
+#			ltool=${path}/libtool
+#		fi
+#	done
+#	if [ "${ltool}" != "" ]; then
+#		${ltool} --version 1>/dev/null 2>&1
+#		if [ "$?" = "0" ]; then
+#			LIBTOOL=${ltool}
+#		else
+#			LIBTOOL=\${TOP}/mk/libtool/libtool
+#			LIBTOOL_BUNDLED="yes"
+#		fi
+#	else
+#		LIBTOOL=\${TOP}/mk/libtool/libtool
+#		LIBTOOL_BUNDLED="yes"
+#	fi
+#fi
+#if [ "${LIBTOOL_BUNDLED}" = "yes" ]; then
+#	echo "yes (bundled)"
+#else
+#	grep ^VERSION=1.5 "${LIBTOOL}" 1>/dev/null 2>&1
+#	if [ "$?" = "0" ]; then
+#		echo "yes (GNU libtool 1.5)"
+#		echo "LIBTOOLFLAGS=-prefer-pic" >> Makefile.config
+#	else
+#		echo "yes (GNU libtool)"
+#	fi
+#fi
+
 echo "PREFIX?=${PREFIX}" >> Makefile.config
 echo "#ifndef PREFIX" > config/prefix.h
 echo "#define PREFIX \"${PREFIX}\"" >> config/prefix.h
@@ -264,9 +325,9 @@ else
 	echo "#endif /* SYSCONFDIR */" >> config/sysconfdir.h
 fi
 
-VERSION="\"1.0\""
+VERSION="1.0"
 echo "#ifndef VERSION" > config/version.h
-echo "#define VERSION" $VERSION >> config/version.h
+echo "#define VERSION \"$VERSION\"" >> config/version.h
 echo "#endif" >> config/version.h
 echo -n "checking for a usable C compiler..."
 echo -n "checking for a usable C compiler..." >> config.log
@@ -309,9 +370,9 @@ cat << EOT > conftest.c
 int main(int argc, char *argv[]) { return (0); }
 
 EOT
-echo "$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o conftest conftest.c " >>config.log
-$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o conftest conftest.c  2>>config.log
-if [ $? == 0 ]; then
+echo "$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o $testdir/conftest conftest.c " >>config.log
+$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o $testdir/conftest conftest.c  2>>config.log
+if [ "$?" = "0" ]; then
 echo "yes"
 echo "yes" >> config.log
 compile="ok"
@@ -328,7 +389,7 @@ HAVE_CC_WARNINGS="no"
 echo "HAVE_CC_WARNINGS=$HAVE_CC_WARNINGS" >> Makefile.config
 echo "#undef HAVE_CC_WARNINGS" > config/have_cc_warnings.h
 fi;
-rm -f conftest conftest.c
+rm -f $testdir/conftest conftest.c
 if [ "${HAVE_CC_WARNINGS}" = "yes" ]; then
 TEST_CFLAGS="-Wall -Werror"
 fi;
@@ -347,9 +408,9 @@ main(int argc, char *argv[])
 }
 
 EOT
-echo "$CC $CFLAGS $TEST_CFLAGS  -o conftest conftest.c " >>config.log
-$CC $CFLAGS $TEST_CFLAGS  -o conftest conftest.c  2>>config.log
-if [ $? == 0 ]; then
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+if [ "$?" = "0" ]; then
 echo "yes"
 echo "yes" >> config.log
 compile="ok"
@@ -366,7 +427,7 @@ HAVE_IEEE754="no"
 echo "HAVE_IEEE754=$HAVE_IEEE754" >> Makefile.config
 echo "#undef HAVE_IEEE754" > config/have_ieee754.h
 fi;
-rm -f conftest conftest.c
+rm -f $testdir/conftest conftest.c
 echo -n "checking __bounded__ attribute..."
 echo -n "checking __bounded__ attribute..." >> config.log
 cat << EOT > conftest.c
@@ -380,9 +441,9 @@ int main(int argc, char *argv[])
 }
 
 EOT
-echo "$CC $CFLAGS $TEST_CFLAGS  -o conftest conftest.c " >>config.log
-$CC $CFLAGS $TEST_CFLAGS  -o conftest conftest.c  2>>config.log
-if [ $? == 0 ]; then
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+if [ "$?" = "0" ]; then
 echo "yes"
 echo "yes" >> config.log
 compile="ok"
@@ -399,7 +460,7 @@ HAVE_BOUNDED_ATTRIBUTE="no"
 echo "HAVE_BOUNDED_ATTRIBUTE=$HAVE_BOUNDED_ATTRIBUTE" >> Makefile.config
 echo "#undef HAVE_BOUNDED_ATTRIBUTE" > config/have_bounded_attribute.h
 fi;
-rm -f conftest conftest.c
+rm -f $testdir/conftest conftest.c
 echo -n "checking __format__ attribute..."
 echo -n "checking __format__ attribute..." >> config.log
 cat << EOT > conftest.c
@@ -419,9 +480,9 @@ int main(int argc, char *argv[])
 }
 
 EOT
-echo "$CC $CFLAGS $TEST_CFLAGS  -o conftest conftest.c " >>config.log
-$CC $CFLAGS $TEST_CFLAGS  -o conftest conftest.c  2>>config.log
-if [ $? == 0 ]; then
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c " >>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c  2>>config.log
+if [ "$?" = "0" ]; then
 echo "yes"
 echo "yes" >> config.log
 compile="ok"
@@ -438,7 +499,7 @@ HAVE_FORMAT_ATTRIBUTE="no"
 echo "HAVE_FORMAT_ATTRIBUTE=$HAVE_FORMAT_ATTRIBUTE" >> Makefile.config
 echo "#undef HAVE_FORMAT_ATTRIBUTE" > config/have_format_attribute.h
 fi;
-rm -f conftest conftest.c
+rm -f $testdir/conftest conftest.c
 echo -n "checking __nonnull__ attribute..."
 echo -n "checking __nonnull__ attribute..." >> config.log
 cat << EOT > conftest.c
@@ -452,13 +513,13 @@ int main(int argc, char *argv[])
 
 EOT
 compile="ok"
-echo "$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o conftest conftest.c" >>config.log
-$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o conftest conftest.c 2>>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o $testdir/conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
 	echo "-> failed ($?)" >> config.log
 	compile="failed"
 fi
-rm -f conftest conftest.c
+rm -f $testdir/conftest conftest.c
 if [ "${compile}" = "ok" ]; then
 echo "yes"
 echo "yes" >> config.log
@@ -474,6 +535,72 @@ HAVE_NONNULL_ATTRIBUTE="no"
 echo "HAVE_NONNULL_ATTRIBUTE=$HAVE_NONNULL_ATTRIBUTE" >> Makefile.config
 echo "#undef HAVE_NONNULL_ATTRIBUTE" > config/have_nonnull_attribute.h
 fi;
+echo -n "checking __aligned__ attribute..."
+echo -n "checking __aligned__ attribute..." >> config.log
+cat << EOT > conftest.c
+int main(int argc, char *argv[])
+{
+	struct s1 { int x,y,z; } __attribute__ ((aligned(16)));
+	return (0);
+}
+
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o $testdir/conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f $testdir/conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_ALIGNED_ATTRIBUTE="yes"
+echo "HAVE_ALIGNED_ATTRIBUTE=$HAVE_ALIGNED_ATTRIBUTE" >> Makefile.config
+echo "#ifndef HAVE_ALIGNED_ATTRIBUTE" > config/have_aligned_attribute.h
+echo "#define HAVE_ALIGNED_ATTRIBUTE \"$HAVE_ALIGNED_ATTRIBUTE\"" >> config/have_aligned_attribute.h
+echo "#endif" >> config/have_aligned_attribute.h
+else
+echo "no"
+echo "no" >> config.log
+HAVE_ALIGNED_ATTRIBUTE="no"
+echo "HAVE_ALIGNED_ATTRIBUTE=$HAVE_ALIGNED_ATTRIBUTE" >> Makefile.config
+echo "#undef HAVE_ALIGNED_ATTRIBUTE" > config/have_aligned_attribute.h
+fi;
+echo -n "checking __packed__ attribute..."
+echo -n "checking __packed__ attribute..." >> config.log
+cat << EOT > conftest.c
+int main(int argc, char *argv[])
+{
+	struct s1 { char c; int x,y,z; } __attribute__ ((packed));
+	return (0);
+}
+
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -Wall -Werror -o $testdir/conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
+fi
+rm -f $testdir/conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_PACKED_ATTRIBUTE="yes"
+echo "HAVE_PACKED_ATTRIBUTE=$HAVE_PACKED_ATTRIBUTE" >> Makefile.config
+echo "#ifndef HAVE_PACKED_ATTRIBUTE" > config/have_packed_attribute.h
+echo "#define HAVE_PACKED_ATTRIBUTE \"$HAVE_PACKED_ATTRIBUTE\"" >> config/have_packed_attribute.h
+echo "#endif" >> config/have_packed_attribute.h
+else
+echo "no"
+echo "no" >> config.log
+HAVE_PACKED_ATTRIBUTE="no"
+echo "HAVE_PACKED_ATTRIBUTE=$HAVE_PACKED_ATTRIBUTE" >> Makefile.config
+echo "#undef HAVE_PACKED_ATTRIBUTE" > config/have_packed_attribute.h
+fi;
 echo -n "checking for long double..."
 echo -n "checking for long double..." >> config.log
 cat << EOT > conftest.c
@@ -488,27 +615,61 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-echo "$CC $CFLAGS $TEST_CFLAGS -o conftest conftest.c" >>config.log
-$CC $CFLAGS $TEST_CFLAGS -o conftest conftest.c 2>>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
 	echo "-> failed ($?)" >> config.log
 	compile="failed"
 fi
-rm -f conftest conftest.c
+rm -f $testdir/conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "ok" >> config.log
-	echo "#ifndef HAVE_LONG_DOUBLE" > config/have_long_double.h
-echo "#define HAVE_LONG_DOUBLE" $HAVE_LONG_DOUBLE >> config/have_long_double.h
+echo "yes"
+echo "yes" >> config.log
+HAVE_LONG_DOUBLE="yes"
+echo "#ifndef HAVE_LONG_DOUBLE" > config/have_long_double.h
+echo "#define HAVE_LONG_DOUBLE \"$HAVE_LONG_DOUBLE\"" >> config/have_long_double.h
 echo "#endif" >> config/have_long_double.h
-
-	HAVE_LONG_DOUBLE="yes"
-	echo "yes"
 else
-    echo "#undef HAVE_LONG_DOUBLE" > config/have_long_double.h
+echo "no"
+echo "no" >> config.log
+HAVE_LONG_DOUBLE="no"
+echo "#undef HAVE_LONG_DOUBLE" > config/have_long_double.h
+fi;
+echo -n "checking for long long..."
+echo -n "checking for long long..." >> config.log
+cat << EOT > conftest.c
+int
+main(int argc, char *argv[])
+{
+	long long ll = 0.0;
+	unsigned long long ull = 0.0;
+	ll = 1.0;
+	ull = 1.0;
+	return (0);
+}
 
-	HAVE_LONG_DOUBLE="no"
-	echo "no"
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
 fi
+rm -f $testdir/conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_LONG_LONG="yes"
+echo "#ifndef HAVE_LONG_LONG" > config/have_long_long.h
+echo "#define HAVE_LONG_LONG \"$HAVE_LONG_LONG\"" >> config/have_long_long.h
+echo "#endif" >> config/have_long_long.h
+else
+echo "no"
+echo "no" >> config.log
+HAVE_LONG_LONG="no"
+echo "#undef HAVE_LONG_LONG" > config/have_long_long.h
+fi;
 echo -n "checking for cygwin environment..."
 echo -n "checking for cygwin environment..." >> config.log
 cat << EOT > conftest.c
@@ -527,13 +688,13 @@ main(int argc, char *argv[]) {
 
 EOT
 compile="ok"
-echo "$CC $CFLAGS $TEST_CFLAGS -mcygwin -o conftest conftest.c" >>config.log
-$CC $CFLAGS $TEST_CFLAGS -mcygwin -o conftest conftest.c 2>>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS -mcygwin -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -mcygwin -o $testdir/conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
 	echo "-> failed ($?)" >> config.log
 	compile="failed"
 fi
-rm -f conftest conftest.c
+rm -f $testdir/conftest conftest.c
 if [ "${compile}" = "ok" ]; then
 echo "yes"
 echo "yes" >> config.log
@@ -567,13 +728,13 @@ main(int argc, char *argv[]) {
 
 EOT
 compile="ok"
-echo "$CC $CFLAGS $TEST_CFLAGS  -o conftest conftest.c" >>config.log
-$CC $CFLAGS $TEST_CFLAGS  -o conftest conftest.c 2>>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS  -o $testdir/conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
 	echo "-> failed ($?)" >> config.log
 	compile="failed"
 fi
-rm -f conftest conftest.c
+rm -f $testdir/conftest conftest.c
 if [ "${compile}" = "ok" ]; then
 echo "yes"
 echo "yes" >> config.log
@@ -593,8 +754,8 @@ if [ "${compile}" = "ok" ]; then
 	CFLAGS="$CFLAGS -mno-cygwin"
 	echo "CFLAGS=$CFLAGS" >> Makefile.config
 fi
-echo -n "checking for Agar (http://hypertriton.com/agar/)..."
-echo -n "checking for Agar (http://hypertriton.com/agar/)..." >> config.log
+echo -n "checking for Agar (http://libagar.org/)..."
+echo -n "checking for Agar (http://libagar.org/)..." >> config.log
 AGAR_VERSION=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
 	if [ -x "${path}/agar-config" ]; then
@@ -634,6 +795,7 @@ echo -n "checking whether Agar works..."
 echo -n "checking whether Agar works..." >> config.log
 cat << EOT > conftest.c
 #include <agar/core.h>
+#include <agar/gui.h>
 
 int
 main(int argc, char *argv[])
@@ -646,9 +808,9 @@ main(int argc, char *argv[])
 }
 
 EOT
-echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_LIBS}" >>config.log
-$CC $CFLAGS $TEST_CFLAGS ${AGAR_CFLAGS} -o conftest conftest.c ${AGAR_LIBS} 2>>config.log
-if [ $? == 0 ]; then
+echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_CFLAGS} -o $testdir/conftest conftest.c ${AGAR_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${AGAR_CFLAGS} -o $testdir/conftest conftest.c ${AGAR_LIBS} 2>>config.log
+if [ "$?" = "0" ]; then
 echo "yes"
 echo "yes" >> config.log
 compile="ok"
@@ -665,7 +827,7 @@ HAVE_AGAR="no"
 echo "HAVE_AGAR=$HAVE_AGAR" >> Makefile.config
 echo "#undef HAVE_AGAR" > config/have_agar.h
 fi;
-rm -f conftest conftest.c
+rm -f $testdir/conftest conftest.c
 echo -n "checking for agar-sg (http://hypertriton.com/agar-sg/)..."
 echo -n "checking for agar-sg (http://hypertriton.com/agar-sg/)..." >> config.log
 AGAR_VERSION=""
@@ -713,15 +875,16 @@ cat << EOT > conftest.c
 #include <agar/core.h>
 #include <agar/sg.h>
 int main(int argc, char *argv[]) {
-	SG sg;
-	SG_Init(&sg, "sg");
+	SG *sg;
+	sg = SG_New(NULL, "foo");
+	AG_ObjectDestroy(sg);
 	return (0);
 }
 
 EOT
-echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_CFLAGS} ${AGAR_SG_CFLAGS} -o conftest conftest.c ${AGAR_LIBS} ${AGAR_SG_LIBS}" >>config.log
-$CC $CFLAGS $TEST_CFLAGS ${AGAR_CFLAGS} ${AGAR_SG_CFLAGS} -o conftest conftest.c ${AGAR_LIBS} ${AGAR_SG_LIBS} 2>>config.log
-if [ $? == 0 ]; then
+echo "$CC $CFLAGS $TEST_CFLAGS ${AGAR_SG_CFLAGS} ${AGAR_CFLAGS} -o $testdir/conftest conftest.c ${AGAR_SG_LIBS} ${AGAR_LIBS}" >>config.log
+$CC $CFLAGS $TEST_CFLAGS ${AGAR_SG_CFLAGS} ${AGAR_CFLAGS} -o $testdir/conftest conftest.c ${AGAR_SG_LIBS} ${AGAR_LIBS} 2>>config.log
+if [ "$?" = "0" ]; then
 echo "yes"
 echo "yes" >> config.log
 compile="ok"
@@ -738,7 +901,7 @@ HAVE_AGAR_SG="no"
 echo "HAVE_AGAR_SG=$HAVE_AGAR_SG" >> Makefile.config
 echo "#undef HAVE_AGAR_SG" > config/have_agar_sg.h
 fi;
-rm -f conftest conftest.c
+rm -f $testdir/conftest conftest.c
 if [ "${HAVE_AGAR_SG}" != "" ]; then
 echo "AGAR_SG_CFLAGS=$AGAR_SG_CFLAGS" >> Makefile.config
 echo "AGAR_SG_LIBS=$AGAR_SG_LIBS" >> Makefile.config
@@ -773,27 +936,26 @@ main(int argc, char *argv[])
 
 EOT
 compile="ok"
-echo "$CC $CFLAGS $TEST_CFLAGS -o conftest conftest.c" >>config.log
-$CC $CFLAGS $TEST_CFLAGS -o conftest conftest.c 2>>config.log
+echo "$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -o $testdir/conftest conftest.c 2>>config.log
 if [ $? != 0 ]; then
 	echo "-> failed ($?)" >> config.log
 	compile="failed"
 fi
-rm -f conftest conftest.c
+rm -f $testdir/conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "ok" >> config.log
-	echo "#ifndef HAVE_PCTR" > config/have_pctr.h
-echo "#define HAVE_PCTR" $HAVE_PCTR >> config/have_pctr.h
+echo "yes"
+echo "yes" >> config.log
+HAVE_PCTR="yes"
+echo "#ifndef HAVE_PCTR" > config/have_pctr.h
+echo "#define HAVE_PCTR \"$HAVE_PCTR\"" >> config/have_pctr.h
 echo "#endif" >> config/have_pctr.h
-
-	HAVE_PCTR="yes"
-	echo "yes"
 else
-    echo "#undef HAVE_PCTR" > config/have_pctr.h
-
-	HAVE_PCTR="no"
-	echo "no"
-fi
+echo "no"
+echo "no" >> config.log
+HAVE_PCTR="no"
+echo "#undef HAVE_PCTR" > config/have_pctr.h
+fi;
 CFLAGS="$CFLAGS -I$SRC"
 echo "CFLAGS=$CFLAGS" >> Makefile.config
 if [ "${enable_static}" = "yes" ]
