use the BSDBuild includes preprocessor

diff --git a/trunk/agar-disasm/configure b/trunk/agar-disasm/configure
--- a/trunk/agar-disasm/configure
+++ b/trunk/agar-disasm/configure
@@ -115,6 +115,9 @@ do
 	--cache=*)
 	    cache=$optarg
 	    ;;
+	--includes=*)
+	    includes=$optarg
+	    ;;
 	*)
 	    echo "invalid argument: $arg"
 	    echo "try ./configure --help"
@@ -150,6 +153,7 @@ if [ "${srcdir}" != "" ]; then
 else
 	SRC=`pwd`
 fi
+BLD=`pwd`
 
 if [ "${testdir}" != "" ]; then
 	echo "Configure tests will be executed in ${testdir}"
@@ -160,6 +164,24 @@ if [ "${testdir}" != "" ]; then
 else
 	testdir="."
 fi
+
+if [ "${includes}" = "" ]; then
+	includes="yes"
+fi
+if [ "${includes}" = "link" ]; then
+	if [ "${with_proj_generation}" ]; then
+		echo "Cannot use --includes=link with --with-proj-generation!"
+		exit 1
+	fi
+elif [ "${includes}" = "yes" ]; then
+	noop=1
+elif [ "${includes}" = "no" ]; then
+	noop=1
+else
+	echo "Usage: --includes [yes|no|link]"
+	exit 1
+fi
+
 if [ "${help}" = "yes" ]; then
 echo "Usage: ./configure [args]"
 echo "    --prefix                  Installation prefix [/usr/local]"
@@ -177,6 +199,7 @@ echo "    --with-manpages           Manual pages (-mdoc) [yes]"
 echo "    --with-manlinks           Manual pages links for functions [no]"
 echo "    --with-ctags              Automatically generate tag files [no]"
 echo "    --with-docs               Printable docs (-me/tbl/eqn/pic/refer) [no]"
+echo "    --includes                Preprocess headers (yes|no|link) [yes]"
 echo "    --with-libtool            Specify path to libtool [use bundled]"
 echo "    --with-cygwin             Add cygwin dependencies under cygwin [no]"
 echo "    --enable-nls              Native Language Support [no]"
@@ -190,12 +213,18 @@ MACHINE=`uname -m 2>/dev/null` || MACHINE=unknown
 OSRELEASE=`uname -r 2>/dev/null` || OSRELEASE=unknown
 SYSTEM=`uname -s 2>/dev/null` || SYSTEM=unknown
 HOST="$SYSTEM-$OSRELEASE-$MACHINE"
-echo "Host: $HOST"
 
 echo "# File generated by configure script (BSDbuild 2.4)." > Makefile.config
+echo "# Host: ${HOST}" >> Makefile.config
+echo "" >> Makefile.config
+echo "SRCDIR=${SRC}" >> Makefile.config
+echo "BLDDIR=${BLD}" >> Makefile.config
+
+echo "Host: $HOST"
 echo "Machine: $MACHINE" > config.log
 echo "Release: $OSRELEASE" >> config.log
 echo "System: $SYSTEM" >> config.log
+
 for arg
 do
 	echo "Argument: $arg" >> config.log
@@ -214,6 +243,7 @@ if [ $? != 0 ]; then
 	exit 1
 fi
 
+# Process built-in documentation options.
 HAVE_MANDOC="no"
 NROFF=""
 for path in `echo $PATH | sed 's/:/ /g'`; do
@@ -249,10 +279,11 @@ else
 		fi
 	fi
 fi
-
 if [ "${with_docs}" = "no" ]; then
 	echo "NODOC=yes" >> Makefile.config
 fi
+
+# Process debug option.
 if [ "${enable_debug}" = "yes" ]; then
 	echo "LDFLAGS+=-g" >> Makefile.config
 	echo "#ifndef DEBUG" > config/debug.h
@@ -262,6 +293,7 @@ else
 	echo "#undef DEBUG" > config/debug.h
 fi
 
+# Process NLS options.
 if [ "${enable_nls}" = "yes" ]; then
 	ENABLE_NLS="yes"
 	echo "#ifndef ENABLE_NLS" > config/enable_nls.h
@@ -286,6 +318,7 @@ fi
 echo "ENABLE_NLS=${ENABLE_NLS}" >> Makefile.config
 echo "HAVE_GETTEXT=${HAVE_GETTEXT}" >> Makefile.config
 
+# Process ctags option.
 CTAGS=""
 if [ "${with_ctags}" = "yes" ]; then
 	for path in `echo $PATH | sed 's/:/ /g'`; do
@@ -303,10 +336,14 @@ if [ "${with_ctags}" = "yes" ]; then
 fi
 echo "CTAGS=${CTAGS}" >> Makefile.config
 
+# Default to bundled libtool.
 LIBTOOL_BUNDLED="yes"
 LIBTOOL=\${TOP}/mk/libtool/libtool
 echo "LIBTOOL=${LIBTOOL}" >> Makefile.config
 
+#
+# Process the installation paths.
+#
 echo "PREFIX?=${PREFIX}" >> Makefile.config
 echo "#ifndef PREFIX" > config/prefix.h
 echo "#define PREFIX \"${PREFIX}\"" >> config/prefix.h
@@ -2748,3 +2785,7 @@ echo "mdefs[\"CFLAGS\"] = \"$CFLAGS\"" >>configure.lua
 echo "CXXFLAGS=$CXXFLAGS" >>Makefile.config
 echo "mdefs[\"CXXFLAGS\"] = \"$CXXFLAGS\"" >>configure.lua
 fi
+echo "*"
+echo "* Configuration successful."
+echo "* Use make && make install to build and install agar-disasm."
+echo "*"
