regenerate

diff --git a/trunk/demos/velcurve/configure b/trunk/demos/velcurve/configure
--- a/trunk/demos/velcurve/configure
+++ b/trunk/demos/velcurve/configure
@@ -6,7 +6,7 @@
 # To regenerate this file, get the latest BSDbuild release from
 # http://hypertriton.com/bsdbuild/, and use the command:
 #
-#      configure.in | mkconfigure > configure
+#     $ cat configure.in | mkconfigure > configure
 #
 # Copyright (c) 2001-2007 Hypertriton, Inc. <http://hypertriton.com/>
 # All rights reserved.
@@ -131,6 +131,7 @@ echo "    --srcdir                       Source tree for concurrent build [.]"
 echo "    --help                         Display this message"
 echo "    --enable-nls                   Native Language Support [no]"
 echo "    --with-gettext                 Use gettext tools (msgmerge, ...) [check]"
+echo "    --with-libtool                 Specify path to libtool [check]"
 echo "    --with-manpages                Manual pages (-mdoc) [yes]"
 echo "    --with-docs                    Printable docs (-me/tbl/eqn/pic/refer) [no]"
 echo "    --enable-debug                 Include debugging code [no]"
@@ -139,15 +140,19 @@ exit 1
 fi
 
 MACHINE=`uname -m 2>/dev/null` || MACHINE=unknown
-RELEASE=`uname -r 2>/dev/null` || RELEASE=unknown
+OSRELEASE=`uname -r 2>/dev/null` || OSRELEASE=unknown
 SYSTEM=`uname -s 2>/dev/null` || SYSTEM=unknown
-HOST="$SYSTEM-$RELEASE-$MACHINE"
+HOST="$SYSTEM-$OSRELEASE-$MACHINE"
 echo "Host: $HOST"
 
 echo "# File generated by configure script (BSDbuild 2.1)." > Makefile.config
 echo "Machine: $MACHINE" > config.log
-echo "Release: $RELEASE" >> config.log
+echo "Release: $OSRELEASE" >> config.log
 echo "System: $SYSTEM" >> config.log
+for arg
+do
+	echo "Argument: $arg" >> config.log
+done
 mkdir config 1>/dev/null 2>&1
 
 HAVE_MANDOC="no"
@@ -217,6 +222,23 @@ fi
 echo "ENABLE_NLS=${ENABLE_NLS}" >> Makefile.config
 echo "HAVE_GETTEXT=${HAVE_GETTEXT}" >> Makefile.config
 
+if [ "${with_libtool}" != "" ]; then
+	echo "LIBTOOL=${with_libtool}" >> Makefile.config
+else
+	ltool=""
+	for path in `echo $PATH | sed 's/:/ /g'`; do
+		if [ -x "${path}/libtool" ]; then
+			ltool=${path}/libtool
+		fi
+	done
+	if [ "${ltool}" != "" ]; then
+		echo "LIBTOOL=${ltool}" >> Makefile.config
+	else
+		echo "Warning: libtool not found on system, using bundled copy"
+		echo "LIBTOOL=\${TOP}/mk/libtool/libtool" >> Makefile.config
+	fi
+fi
+
 echo "PREFIX?=${PREFIX}" >> Makefile.config
 echo "#ifndef PREFIX" > config/prefix.h
 echo "#define PREFIX \"${PREFIX}\"" >> config/prefix.h
@@ -266,7 +288,7 @@ fi
 
 VERSION="\"1.0\""
 echo "#ifndef VERSION" > config/version.h
-echo "#define VERSION" $VERSION >> config/version.h
+echo "#define VERSION \"$VERSION\"" >> config/version.h
 echo "#endif" >> config/version.h
 echo -n "checking for a usable C compiler..."
 echo -n "checking for a usable C compiler..." >> config.log
@@ -562,19 +584,53 @@ if [ $? != 0 ]; then
 fi
 rm -f conftest conftest.c
 if [ "${compile}" = "ok" ]; then
-	echo "ok" >> config.log
-	echo "#ifndef HAVE_LONG_DOUBLE" > config/have_long_double.h
-echo "#define HAVE_LONG_DOUBLE" $HAVE_LONG_DOUBLE >> config/have_long_double.h
+echo "yes"
+echo "yes" >> config.log
+HAVE_LONG_DOUBLE="yes"
+echo "#ifndef HAVE_LONG_DOUBLE" > config/have_long_double.h
+echo "#define HAVE_LONG_DOUBLE \"$HAVE_LONG_DOUBLE\"" >> config/have_long_double.h
 echo "#endif" >> config/have_long_double.h
-
-	HAVE_LONG_DOUBLE="yes"
-	echo "yes"
 else
-    echo "#undef HAVE_LONG_DOUBLE" > config/have_long_double.h
+echo "no"
+echo "no" >> config.log
+HAVE_LONG_DOUBLE="no"
+echo "#undef HAVE_LONG_DOUBLE" > config/have_long_double.h
+fi;
+echo -n "checking for long long..."
+echo -n "checking for long long..." >> config.log
+cat << EOT > conftest.c
+int
+main(int argc, char *argv[])
+{
+	long long ll = 0.0;
+	unsigned long long ull = 0.0;
+	ll = 1.0;
+	ull = 1.0;
+	return (0);
+}
 
-	HAVE_LONG_DOUBLE="no"
-	echo "no"
+EOT
+compile="ok"
+echo "$CC $CFLAGS $TEST_CFLAGS -o conftest conftest.c" >>config.log
+$CC $CFLAGS $TEST_CFLAGS -o conftest conftest.c 2>>config.log
+if [ $? != 0 ]; then
+	echo "-> failed ($?)" >> config.log
+	compile="failed"
 fi
+rm -f conftest conftest.c
+if [ "${compile}" = "ok" ]; then
+echo "yes"
+echo "yes" >> config.log
+HAVE_LONG_LONG="yes"
+echo "#ifndef HAVE_LONG_LONG" > config/have_long_long.h
+echo "#define HAVE_LONG_LONG \"$HAVE_LONG_LONG\"" >> config/have_long_long.h
+echo "#endif" >> config/have_long_long.h
+else
+echo "no"
+echo "no" >> config.log
+HAVE_LONG_LONG="no"
+echo "#undef HAVE_LONG_LONG" > config/have_long_long.h
+fi;
 echo -n "checking for cygwin environment..."
 echo -n "checking for cygwin environment..." >> config.log
 cat << EOT > conftest.c
@@ -700,6 +756,7 @@ echo -n "checking whether Agar works..."
 echo -n "checking whether Agar works..." >> config.log
 cat << EOT > conftest.c
 #include <agar/core.h>
+#include <agar/gui.h>
 
 int
 main(int argc, char *argv[])
